### ISSUE TITLE
Loss is significantly worse when calculated manually in train_step compared to passed into model.compile

### ISSUE THREAD

**Issue by Yacalis** [keras-team/keras#16836] opened 2022-07-26 17:15 UTC
#<details><summary>Click to expand!</summary> 
 
 ### Issue Type
Bug

#### Source
binary

#### Tensorflow Version
2.8.2

#### Custom Code
Yes

#### OS Platform and Distribution
Linux Ubuntu 18.04.5

#### Python version
Python 3.7.13

#### Current Behavior
I am following the steps here for customizing what happens in `train_step` when you customize a model:

https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit

The issue is, I am getting very different results for the loss when I am using the exact same `tensorflow.keras.losses.mean_squared_error` function in different locations.

When I use `mean_squared_error` "manually" during `train_step` (I am calling this the non-compiled mse), the loss is significantly worse than if I  pass it into the compile method, e.g. `model.compile(optimizer="adam", loss=mean_squared_error)` (I am calling this the compiled mse).

`tensorflow.keras.metrics.MeanSquaredError` yields roughly the same result as the compiled version of mse, but it is still not exactly the same.

#### Expected Behavior
My expectation is that the loss should be the same whether it is passed into `.compile`, defined during `train_step`, or used as a metric. But it is significantly worse if I do not pass it into `.compile` and I don't know why. I am following the documentation, and as far as I can tell am not doing anything incorrectly.

Why is the loss so different when it is and is not passed into `.compile`?

#### Colab Notebook
I have reproduced this behavior in this google colab notebook, link below. The plot shows that non-compiled mse is systematically worse than compiled mse. 

https://colab.research.google.com/drive/1c1L8KJYQbAldphKvFvmw5cHi9EyBQP0X?usp=sharing

Originally I opened a ticket at tensorflow/tensorflow [here](https://github.com/tensorflow/tensorflow/issues/56866), and they were able to reproduce the issue. This is the gist:

https://colab.research.google.com/gist/sushreebarsa/f1144243be9eed060c39c60611811811/56866.ipynb

#### Standalone code to reproduce behavior
This is the same as what is in the Colab notebooks. 
```
import tensorflow as tf
from tensorflow.keras.metrics import Mean, MeanSquaredError
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Dropout, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import mean_squared_error
import matplotlib.pyplot as plt


seed = 113
epochs = 30
batch_size = 10

n = 5
history_dict = {}

# load dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.boston_housing.load_data(
    path="boston_housing.npz", test_split=0.2, seed=seed,
)
n_validate = int(0.1 * len(x_train))
train_dataset = tf.data.Dataset.from_tensor_slices(
    (x_train[:-n_validate], y_train[:-n_validate])
).batch(batch_size)
valid_dataset = tf.data.Dataset.from_tensor_slices(
    (x_train[-n_validate:], y_train[-n_validate:])
).batch(batch_size)
test_dataset = tf.data.Dataset.from_tensor_slices(
    (x_test, y_test)
).batch(batch_size)

for i in range(n):
    
    tf.keras.backend.clear_session()
    
    mse_tracker = Mean(name="non_compiled_mse")
    mse_tracker_metric = MeanSquaredError(name="mse_metric")
    
    class CustomModel(Model):
        
        @tf.function
        def train_step(self, data):
            x, y_true = data
            with tf.GradientTape() as tape:
                y_pred = self(x, training=True)
                compiled_mse = self.compiled_loss(y_true, y_pred)
                non_compiled_mse = mean_squared_error(y_true, y_pred)
                mse_tracker.update_state(non_compiled_mse)
                mse_tracker_metric.update_state(y_true, y_pred)
            gradients = tape.gradient(compiled_mse, self.trainable_variables)
            self.optimizer.apply_gradients(zip(gradients, self.trainable_variables))
            return {m.name: m.result() for m in self.metrics}
        
        @tf.function()
        def test_step(self, data):
            x, y_true = data
            y_pred = self(x, training=False)
            compiled_mse = self.compiled_loss(y_true, y_pred)
            non_compiled_mse = mean_squared_error(y_true, y_pred)
            mse_tracker.update_state(non_compiled_mse)
            mse_tracker_metric.update_state(y_true, y_pred)
            return {m.name: m.result() for m in self.metrics}

        @property
        def metrics(self):
            return super().metrics + [mse_tracker, mse_tracker_metric]
    
    input_layer = Input(shape=x_train.shape[1:])
    x = Dense(8, activation='linear')(input_layer)
    x = Dense(8, activation='linear')(x)
    output_layer = Dense(units=1, activation='linear')(x)
    model = CustomModel(input_layer, output_layer)
    model.compile(optimizer=Adam(learning_rate=1e-3), loss=mean_squared_error)
    history = model.fit(
        train_dataset,
        validation_data=valid_dataset,
        epochs=epochs,
        verbose=0,
    )
    history_dict[f"compiled_mse_{i}"] = history.history["loss"]
    history_dict[f"non_compiled_mse_{i}"] = history.history["non_compiled_mse"]
    history_dict[f"mse_metric_{i}"] = history.history["mse_metric"]


plot_start_epoch = 5
plt.figure(figsize=(12, 6))
for i in range(n):
    plt.plot(
        range(epochs)[plot_start_epoch:],
        history_dict[f"compiled_mse_{i}"][plot_start_epoch:],
        label=f"compiled_mse" if i == 0 else None,
        color="black",
    )
    plt.plot(
        range(epochs)[plot_start_epoch:],
        history_dict[f"non_compiled_mse_{i}"][plot_start_epoch:],
        label=f"non_compiled_mse" if i == 0 else None,
        color="orange",
    )
    plt.plot(
        range(epochs)[plot_start_epoch:],
        history_dict[f"mse_metric_{i}"][plot_start_epoch:],
        label=f"mse_metric" if i == 0 else None,
        color="red",
        linestyle="dashed",
    )
plt.ylabel("loss")
plt.xlabel("epoch")
plt.title("compiled vs non-compiled mse vs mse metric")
plt.legend()
plt.show()
```

#### Related Issues
I could not find an issue that was the same as this one, but [16834](https://github.com/keras-team/keras/issues/16834) might be related, as it also notes a difference between compiled mean squared error and manually calculated mean squared error: 

> When using keras for regression problems, loss uses mean squared error. The loss displayed by the network fit in the last epoch during training is inconsistent with the loss calculated from the input data after the model is saved.

I have not tested whether or not this behavior is reproduced when using a loss other than mean squared error.</details>

**Comment by sushreebarsa** [comment] 2022-07-27 05:41
@gadagashwini I was able to replicate this issue, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f1144243be9eed060c39c60611811811/56866.ipynb) .Thank you!

**Comment by lucasdavid** [comment] 2022-07-28 00:39
I believe the snippet below is a simpler way to reproduce this error.
```py
import numpy as np
from keras import Sequential
from keras.layers import Dense
from keras.metrics import Mean, MeanSquaredError, mean_squared_error

x=np.concatenate((
    np.zeros((40, 1)),
    np.ones((40, 1))
))
y_true = np.random.rand(80) * 100

model = Sequential([
  Dense(1, input_dim=1)
])
y_pred = model(x, training=True)

mean = Mean(name="mean")
mse = MeanSquaredError(name="msem")

mean.update_state(mean_squared_error(y_true, y_pred))
mse.update_state(y_true, y_pred)

print('name total count result ',
  *(f'{metric.name} {metric.total.numpy():11.4f} {metric.count.numpy():2.0f} {metric.result().numpy():10.4f}'
    for metric in (mean, mse)),
      sep='\n')

np.testing.assert_allclose(
  mean.result().numpy(),
  mse.result().numpy()
)
```
```py
name total count result
mean 228341.4062 80  2854.2676
msem   2857.3472  1  2857.3472

---------------------------------------------------------------------------
... # stack

AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 3.0795898
Max relative difference: 0.00107778
 x: array(2854.2676, dtype=float32)
 y: array(2857.3472, dtype=float32)
```

**Comment by lucasdavid** [comment] 2022-07-28 02:00
#### TDLR

You must pass y_true as a 2-D tensor `[batch, target_vars]`, because `mean_squared_error` will average the signal over the last axis. For the 1-D case, this means reducing all samples in the batch into a single value, which confuses the `MeanMetricWrapper` into thinking all batches only have 1 sample.
Adding this line fixes the differences between the losses and yields the correct history chart (lines are coincident):
```py
y_train, y_test = y_train.reshape(-1, 1), y_test.reshape(-1, 1)
```
Chart: https://user-images.githubusercontent.com/1595030/181395395-01c972f1-529c-4595-bdcb-f1bdad4f05d0.png

---
#### Why this is happening

1. When using `Mean` and `mean_absolute_error`:
    Although your labels have an incorrect rank, the output of the network is correct (`[batch, 1]`). Calling `mean_squared_error` with both values results in the broadcasting that fixes the issue:
    ```py
    shape(y_true) == [batch]
    shape(y_pred) == [batch, 1]

    losses = mean_squared_error(y_true, y_pred)  # [batch]
    # mse =>
    #   diff = y_true - y_pred  # [batch] - [batch, 1] -- broadcast --> [batch, 1]
    #   return backend.mean(diff ** 2, axis=-1)  # [batch]
    ```
2. When using `MeanSquaredError`:
    The `MeanSquaredError#update_state` method (implemented in `base_metric.MeanMetricWrapper`) is invoking `losses_utils.squeeze_or_expand_dimensions`, which reduces `shape(y_pred) == [batch, 1]` to conform with `shape(y_true) == [batch]`. The function `mean_squared_error` then reduces the last dim, resulting in a single value instead of *batch* that should be reduced inside `Mean`.
3. When using compiled metric:
    `LossesContainer` invokes `losses_utils.squeeze_or_expand_dimensions`, resulting in the same value as if you were using `MeanSquaredError`.

**Comment by lucasdavid** [comment] 2022-07-28 02:02
Turns out this is a duplicate of #14627. So many minutes wasted debugging it... :disappointed:

**Comment by Yacalis** [comment] 2022-07-28 20:08
I see, so just to make sure I totally understand what you are saying:

`y_pred.shape == [batch, 1]` after `y_pred = self(x)`. `y_true.shape == [batch]` _before_ being passed to `mean_squared_error`, but is broadcast to be shape `[batch, 1]` _during_ `mean_squared_error`.

In both the compiled and non-compiled cases, `losses.shape == [batch]` after `losses = mean_squared_error(y_true, y_pred).` The difference is that the compiled function then broadcasts it to `losses.shape == [batch, 1]` before passing it to `Mean`, but in the manual case it was still `losses.shape == [batch]` when it was passed to `Mean`.

If `y_train`, `y_test` (and `y_pred`) were 2D ahead of time all of this is avoided.

Is all this right?

I think this issue arose because the shape of the data in the documentation is not revealed, and it assumes your data is in the correct shape. Which is probably not an issue of the documentation, but is an assumption it makes to where you can't just pass it any dataset and expect it to work.

Also, I'm sorry this issue is a duplicate, I might not have found the other one because I was focused on `.compile`.

**Comment by lucasdavid** [comment] 2022-07-28 22:33
> y_pred.shape == [batch, 1] after y_pred = self(x). y_true.shape == [batch] before being passed [...]

This is correct.
```py
{y_pred [batch, 1], y_true [batch]} -- mean_squared_error(y_true - y_pred) --> loss [batch]   <=>
{y_pred [batch, 1], y_true [batch]} -- mean((y_true - y_pred)**2, axis=-1) --> loss [batch]
```

> In both the compiled and non-compiled cases, losses.shape == [batch] after losses = mean_squared_error(y_true, y_pred).

No. `loss.shape == [batch]` for the non-compiled (the sequence above).
`loss.shape == [1]` for both compiled and `mse_tracker_metric <MeanSquaredError>`, because both invoke `losses_utils.squeeze_or_expand_dimensions` before/during `MeanMetricWrapper#update_state`.

The only correct value here is the non-compiled one; and this bug is actually pretty funny. I don't think it would be easy to spot without the custom train_step.

> I think this issue arose because the [...]

I agree. Maybe something could be done to improve on this. Either by documenting better or creating a version of squared error that didn't reduce any axis.

And I apologize. I didn't mean to complain that you hadn't looked for it, but rather that I forgot to check before start debugging.

**Comment by Yacalis** [comment] 2022-07-28 23:01
Oh no problem, I took it as you intended. Thank you for clarifying all this.

I've never closed an issue before, but I'm feeling like maybe this should be closed. The easiest step would be just to include what the shapes of the data are (or the data itself) in the documentation. It's a very specific problem, but my experience is that MSE alongside a single target variable is not uncommon for regression models. On the other hand, I don't know how I'd even go about changing it even if I had the ability to do so.

**Comment by gadagashwini** [comment] 2022-08-01 06:05
Hi @Yacalis, Can move this issue to closed status, if it resolved for you. Thank you!

**Closed** 2022-08-09 22:49 UTC
Labels: stat:awaiting response from contributor, stalled, type:Bug
