### ISSUE TITLE
Problem with RNN with multiple states

### ISSUE THREAD

**Issue by henrypinkard** [keras-team/keras#12026] opened 2019-01-11 21:42 UTC
I'm trying to create a custom RNN cell that takes in a list of input tensors (e.g. feature blocks from a convolutional layer) and has multiple tensors in its state (with the same dimensions as the inputs). My approach for doing this was to create a custom RNN cell and pass it to the RNN layer. However, an error occurs because RNN.input_spec is set to [None] rather than the actual size of the input. Looking through source code of RNN and it's super class, I don't see anywhere where this input_spec would be correctly set, so I'm wondering if this is a bug in its implementation. The code to reproduce it is copied below. It doesn't seem to have anything to do with the custom RNN cell I wrote, so for brevity I replaced it with SimpleRNNCell (even though the architecture this gives probably won't work for other reasons).

```
from tensorflow import keras as ks
from pyramid_rnn import PyramidRNNCell

# Build initial featurizer which takes an image as an input and outputs a list of features
inputs = ks.layers.Input(shape=(512, 512, 1))
outputs = [ks.layers.Conv2D(32, 5)(inputs), ks.layers.Conv2D(54, 10)(inputs)]
featurizer = ks.models.Model(inputs=inputs, outputs=outputs)
feature_shapes = [tensor.shape for tensor in featurizer.outputs]

# make list of time series for inputs to RNN
time_series_input = ks.layers.Input(shape=(None, 512, 512, 1))
rnn_inputs = []
# apply TimeDistributed to each feature block
for feature_block in featurizer.outputs:
    rnn_inputs.append(ks.layers.TimeDistributed(
        ks.models.Model(featurizer.input, feature_block))(time_series_input))

# create initial state for RNN, which are same dimensionality as inputs
rnn_initial_state = []
for shapes in feature_shapes:
    rnn_initial_state.append(ks.layers.Input(shape=shapes[1:]))

cell = ks.layers.SimpleRNNCell(10)
rnn_output = ks.layers.RNN(cell)([rnn_inputs, *rnn_initial_state])

```

**Comment by msymp** [comment] 2019-01-15 01:17
Hello @henrypinkard , can you please provide us your system details in the below template.

System information:

- Have I written custom code (as opposed to using example directory):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow backend (yes / no):
- TensorFlow version (CPU / GPU):
- Python version:
- CUDA/cuDNN version:
- GPU model and memory (Full Specifications):

You can obtain the TensorFlow version with:
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in Keras or a feature request.

Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by henrypinkard** [comment] 2019-01-15 14:17
**System information:**

- This is with custom code using the functional API
- OS is MacOS Mojave 10.14
- Using TensorFlow backend
- TensorFlow version: v1.12.0-rc2-3-ga6d8ffae09 1.12.0 
- Python 3.6.7
- No GPU/CUDA

**Description of problem**
I'm trying to create a custom RNN cell that takes in a list of input tensors (e.g. feature blocks from a convolutional layer) and has multiple tensors in its state (with the same dimensions as the inputs). My approach for doing this was to create a custom RNN cell and pass it to the `RNN` layer. However, an error occurs because `RNN.input_spec` is set to `[None]` rather than the actual size of the input. Looking through source code of `RNN` and it's super class, `Layer`, I don't see anywhere where this `input_spec` would be correctly set, so I'm wondering if this is a bug in its implementation. The minimum code to reproduce it is copied below. It doesn't seem to have anything to do with the custom RNN cell I wrote, so for brevity I replaced it with `SimpleRNNCell` (even though the architecture this gives probably won't work for other reasons once this bug is solved).

**Source code**
Minimum code to reproduce problem 
```
from tensorflow import keras as ks
from pyramid_rnn import PyramidRNNCell

# Build initial featurizer which takes an image as an input and outputs a list of features
inputs = ks.layers.Input(shape=(512, 512, 1))
outputs = [ks.layers.Conv2D(32, 5)(inputs), ks.layers.Conv2D(54, 10)(inputs)]
featurizer = ks.models.Model(inputs=inputs, outputs=outputs)
feature_shapes = [tensor.shape for tensor in featurizer.outputs]

# make list of time series for inputs to RNN
time_series_input = ks.layers.Input(shape=(None, 512, 512, 1))
rnn_inputs = []
# apply TimeDistributed to each feature block
for feature_block in featurizer.outputs:
    rnn_inputs.append(ks.layers.TimeDistributed(
        ks.models.Model(featurizer.input, feature_block))(time_series_input))

# create initial state for RNN, which are same dimensionality as inputs
rnn_initial_state = []
for shapes in feature_shapes:
    rnn_initial_state.append(ks.layers.Input(shape=shapes[1:]))

cell = ks.layers.SimpleRNNCell(10)
rnn_output = ks.layers.RNN(cell)([rnn_inputs, *rnn_initial_state])
```

Which gives the following error when run
```
Traceback (most recent call last):
  File "/Users/henrypinkard/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-ba121e4205c3>", line 1, in <module>
    runfile('/Users/henrypinkard/Google Drive/Code/GitRepos/TimelapseDenoise/keras_bug.py', wdir='/Users/henrypinkard/Google Drive/Code/GitRepos/TimelapseDenoise')
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/henrypinkard/Google Drive/Code/GitRepos/TimelapseDenoise/keras_bug.py", line 24, in <module>
    rnn_output = ks.layers.RNN(ks.layers.SimpleRNNCell(10))([rnn_inputs, *rnn_initial_state])
  File "/Users/henrypinkard/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/recurrent.py", line 659, in __call__
    output = super(RNN, self).__call__(full_input, **kwargs)
  File "/Users/henrypinkard/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 730, in __call__
    self._assert_input_compatibility(inputs)
  File "/Users/henrypinkard/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1455, in _assert_input_compatibility
    ' input tensors. Inputs received: ' + str(inputs))
ValueError: Layer rnn expects 3 inputs, but it received 4 input tensors. Inputs received: [<tf.Tensor 'time_distributed/Reshape_1:0' shape=(?, ?, 508, 508, 32) dtype=float32>, <tf.Tensor 'time_distributed_1/Reshape_1:0' shape=(?, ?, 503, 503, 54) dtype=float32>, <tf.Tensor 'input_3:0' shape=(?, 508, 508, 32) dtype=float32>, <tf.Tensor 'input_4:0' shape=(?, 503, 503, 54) dtype=float32>]
```

**Comment by msymp** [comment] 2019-01-16 00:22
Hello @anj-s (anjalisridhar), user is inquiring if the input_spec is explicitly set some place, so that they can pass a custom RNN cell to the RNN layer. When they do that now, it throws a shape mismatch error on the input to RNN layer. Thanks

**Comment by yinawang28** [comment] 2019-01-31 00:32
Run into similar problem when creating a custom RNN cell. Do you guys have any updates? @anj-s Thanks.

**Comment by qlzh727** [comment] 2019-01-31 15:46
Thanks for reporting this issue. First, for a standard RNN layer, it only accepts one input, not a list. Even u change the input_spec of rnn manually, there are still more logic need to be updated in rnn.call() since it was expecting to have only one input too.

In tensorflow.keras, we updated the RNN to support nested input. It is still not a list, but can be used to fit your use case. eg. your input can be a namedtuple like {'t1': tensor1, 't2':tensor2...}. The rnn.call() is also updated to properly slide each of the tensor within the nest structure on timestep dim, and feed to  cell.call().

We will sync back this feature back to keras soon. If you need it now, you can try out with tensorflow.keras.rnn.

**Comment by henrypinkard** [comment] 2019-03-06 18:07
@qlzh727 Thanks for your help! I was able to get this working by switching over to a dictionary instead of a list as you suggested. 

I did find one part of the code that could be improved though. My initial thought when switching to to use a dictionary was to just make the keys of that dictionary integer strings, as in:
```
{'0': TensorShape([Dimension(None), Dimension(None), Dimension(24), Dimension(24)]),
 '1': TensorShape([Dimension(None), Dimension(None), Dimension(48), Dimension(48)]),
 '2': TensorShape([Dimension(None), Dimension(None), Dimension(96), Dimension(96)])}
```

However, this gives a confusing error, because, the in code at line 591 in recurrent:
```
  try:
      input_shape = tensor_shape.as_shape(input_shape)
    except (ValueError, TypeError):
      # A nested tensor input
      pass
```

`tensor_shape.as_shape` fails to raise an exception, instead returning: 

```
TensorShape([Dimension(0), Dimension(1), Dimension(2), Dimension(3), Dimension(4)])
```

I fixed this by switching to different strings as keys, i.e.

```
{'a': TensorShape([Dimension(None), Dimension(None), Dimension(24), Dimension(24)]),
 'b': TensorShape([Dimension(None), Dimension(None), Dimension(48), Dimension(48)]),
 'c': TensorShape([Dimension(None), Dimension(None), Dimension(96), Dimension(96)])}
```

but it might be useful to make a more robust way to check for nested inputs

**Comment by qlzh727** [comment] 2019-04-15 16:39
Thanks for the information. I think tensor_shape.as_shape just get all the keys of the dict, which then convert the 0, 1, 2 to actual shape. I will send a fix for that separately. 

Assume the multi state issue is solved here, I am closing this bug for now. Feel free to reopen this issue if you hit any further problems.

Thanks.

**Closed by qlzh727** 2019-04-15 16:39 UTC
Labels: stat:awaiting tensorflower, type:support
