### ISSUE TITLE
Inconsistency in DepthwiseConv2D output shape

### ISSUE THREAD

**Issue by Golbstein** [keras-team/keras#12972] opened 2019-06-17 07:38 UTC
given the following example:

```
from keras.layers import DepthwiseConv2D
from keras import backend as K
x = Input((256,512,3))
x = DepthwiseConv2D(kernel_size=3, dilation_rate=(2, 2),
                   strides=1, padding='valid')(x)
print(x, K.int_shape(x))
```

it prints:
Tensor("depthwise_conv2d_2/BiasAdd:0", **shape=(?, 252, 508, 3)**, dtype=float32) 
**(None, 254, 510, 3)**

keras = 2.2.4

**Comment by gowtham-kp** [comment] 2019-07-22 22:42
@tanzhenyu Can you PTAL. Thanks!

**Comment by tanzhenyu** [comment] 2019-07-23 00:01
You Input should not have batch size?

**Comment by tanzhenyu** [comment] 2019-07-23 00:04
I cannot reproduce this error on colab, it seems to be fine with:
Tensor("depthwise_conv2d_1/BiasAdd:0", shape=(?, 252, 508, 3), dtype=float32) (None, 254, 510, 3)

**Comment by gowtham-kp** [comment] 2019-07-23 19:05
@tanzhenyu Correct me if I am wrong, but I can reproduce the issue. Here's the link to my [colab notebook](https://colab.research.google.com/drive/1sTdj_dR9TeIN9f5bT4IyDWZAhm4_A14h). Thanks!

**Comment by tanzhenyu** [comment] 2019-07-23 19:34
Oh sorry -- it seems a bug to me

**Comment by tanzhenyu** [comment] 2019-07-23 19:35
I'm not sure how the keras bug assign works, if you can assign to me then go ahead and do it, if not you can duplicate the bug in tensorflow github and assign to me.

**Closed** 2021-06-24 22:38 UTC
Labels: type:bug/performance
