### ISSUE TITLE
Can't load weights of a keras model saved with old keras version using new keras version

### ISSUE THREAD

**Issue by RANG1991** [keras-team/keras#14602] opened 2021-04-18 21:18 UTC
I'm trying to set weights of a keras model (loaded with new keras version - 2.2.4-tf, which is now under tensorflow package) which was saved to a DB using old keras, but it is failing with the error:
**ValueError: Layer weight shape (8,) not compatible with provided weight shape (1, 9, 8, 4)**
Here is a code snippet depicting what we were trying to do:
```
model = keras.models.model_from_json(...)
model.compile(...)
model.set_weights(...)
```
As stated before, the code is crashing in the model.set_weights(...) function, producing the above error.
We found out that the same layers exist both in the model loaded using an old keras version (2.3.1) - which also succeeded to set the weights properly - and also with the model loaded using new keras version (2.2.4-tf), **but not in the same order**.
Below is the output of the code -` collection.Counter([ww.shape for ww in m_old.get_weights()'])` and the code - `collection.Counter([ww.shape for ww in m_new.get_weights()'])`
where m_old is the model loaded by the old keras version and the m_new is the model loaded by the new keras version:
```
Out[20]:
Counter({(7, 1, 1, 8): 5,
         (8,): 20,
         (1, 9, 8, 4): 5,
         (4,): 20,
         (120, 1): 5,
         (1,): 5})
Out[21]:
Counter({(7, 1, 1, 8): 5,
         (8,): 20,
         (1, 9, 8, 4): 5,
         (4,): 20,
         (120, 1): 5,
         (1,): 5})
```
We will appreciate any help.

**Comment by jvishnuvardhan** [comment] 2021-08-05 01:06
@RANG1991 Is this still an issue for you? Can you please test with recent version (`TF2.5` and `tf-nightly`) and let us know whether it is reproducible or not. 

If this is reproducible with recent TF versions, can you please share a simple standalone code to reproduce the issue? Thanks

**Comment by jvishnuvardhan** [comment] 2021-08-23 23:59
Closing due to lack of recent activity. Please feel free to reopen when you have more information. Thanks!

**Closed by jvishnuvardhan** 2021-08-23 23:59 UTC
Labels: type:support, stat:awaiting response
