### ISSUE TITLE
fit_generator not working in Keras 2.2.4 with python 3.6.8

### ISSUE THREAD

**Issue by aerijman** [keras-team/keras#12741] opened 2019-04-26 02:06 UTC
**fit_generator**. 

It does work in:  
Python 3.6.5
Keras 2.1.6

But doesn't in:
Python 3.6.8
Keras 2.2.4

Unless related to version of other modules.

**Comment by aerijman** [comment] 2019-04-27 20:29
In case this is just a product of my ignorance and not a malfunctioning, this is the output and error:

```
2019-04-27 16:24:12.660651: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2019-04-27 16:24:12.661810: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 12. Tune using inter_op_parallelism_threads for best performance.

```
Epoch 1/100
```
OMP: Error #15: Initializing libiomp5.dylib, but found libiomp5.dylib already initialized.
OMP: Hint: This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
Abort trap: 6
```

**Comment by jvishnuvardhan** [comment] 2019-05-02 22:19
Please fill the issue [template](https://github.com/keras-team/keras/issues/new?template=a--tensorflow-backend-users.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-08 20:28
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-08 20:28 UTC
Labels: backend:tensorflow, stat:awaiting response, type:support
