### ISSUE TITLE
ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.

### ISSUE THREAD

**Issue by dzhao123** [keras-team/keras#12931] opened 2019-06-07 21:33 UTC
```
def build_model(input_shape, num_classes):
    x = Input(input_shape)
    x = Embedding(10000, 64)(x)#, input_length=28)(x)
    print(x.shape)
    #x = Bidirectional(GRU(14, input_shape=(28, 64), return_sequences=True))(x)
    x = Bidirectional(GRU(14, return_sequences=True))(x)
    print(x.shape)
    #forw = GRU(14, return_sequences=True)(x)
    #forw = GRU(14)(forw)
    #back = GRU(14, return_sequences=True, go_backwards=True)(x)
    #back = GRU(14, go_backward=True)(x)
    #y = Concatenate(-1)([forw, back])
    y = Reshape((None,28,28,1))(x)
    y = Conv2D(32, (3, 3), activation='relu')(y)
    y = MaxPooling2D((2,2))(y)
    y = Conv2D(64, (3, 3), activation='relu')(y)
    y = MaxPooling2D((2,2))(y)
    y = Flatten()(y)
    y = Dense(num_classes, activation='softmax')(y)
    return Model(x,y)

```

Hi there, I am trying to build this model ,but the error returns as follow:
```
(?, 28, 64)
(?, ?, 28)

ValueErrorTraceback (most recent call last)
<ipython-input-16-66bdf6604ccd> in <module>()
    105 
    106 
--> 107 model = build_model(image_shape, num_classes)
    108 
    109 model.summary()

5 frames
/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.pyc in _apply_op_helper(self, op_type_name, name, **keywords)
    526               raise ValueError(
    527                   "Tried to convert '%s' to a tensor and failed. Error: %s" %
--> 528                   (input_name, err))
    529             prefix = ("Input '%s' of '%s' Op has type %s that does not match" %
    530                       (input_name, op_type_name, observed))

ValueError: Tried to convert 'shape' to a tensor and failed. Error: None values not supported.
```

I print the shape of the data after word embedding and gru. The shape of the output gru is (?,?,28) which is so wierd. Can anyone give some hints? Thanks.

**Comment by VirtualKley** [comment] 2019-06-09 17:11
And if you try to resize the variable x using the "resize" method of opencv:
cv2.resize(v1, v2, input_shape)

O numpy with methods 
".reshape" or ".resize"

**Comment by jvishnuvardhan** [comment] 2019-06-12 21:18
Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-21 23:05
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-21 23:05 UTC
Labels: backend:tensorflow, stat:awaiting response, type:bug/performance
