### ISSUE TITLE
when value is not float, tf.keras.backend.set_epsilon doesnt throw exception

### ISSUE THREAD

**Issue by cheyennee** [keras-team/keras#16968] opened 2022-08-31 09:22 UTC
value should be float written on [documentation](https://tensorflow.google.cn/versions/r2.4/api_docs/python/tf/keras/backend/set_epsilon#arguments) However, I find when value is string, the code also works and doesnt throw exception.

```
import tensorflow as tf
results={}
try:
  arg_0 = 'xxx'
  tf.keras.backend.set_epsilon(arg_0,)
except Exception as e:
  print(str(e))
```

**Comment by sushreebarsa** [comment] 2022-09-03 04:31
@cheyennee I tried to replicate the issue reported, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/d2fbb19e7af28f4c1de8d65faa31d801/untitled113.ipynb) and confirm the same?
Thank you!

**Comment by cheyennee** [comment] 2022-09-03 06:45
@sushreebarsa  Yeah, I met the same problem with you.

**Comment by tilakrayal** [comment] 2023-02-14 08:02
@cheyennee,
When I tried to provide the input other than float to tf.keras.backend.set_epsilon, it was giving the output as None which was working as expected and when provide the argument as float it is working. 

**value | float. New value of epsilon.**

Code:

```
import tensorflow as tf
print(tf.__version__)
print(tf.keras.backend.epsilon())
a = tf.keras.backend.set_epsilon('xxx')
print(a)
```

Output:

```
2.13.0-dev20230213
abc
None

```
Code 2: 

```
import tensorflow as tf
results={}
arg_0 = 'abc'
r = tf.keras.backend.set_epsilon(arg_0,)
print(r)

```
Output:

`None`


Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/18a8a49f014c455f295704f8db939561/untitled938.ipynb) of it for the reference. Thank you!

**Comment by sachinprasadhs** [comment] 2023-03-02 19:15
@cheyennee , Thanks for reporting the issue. 
We don't explicitly check for all types of runtime validations like dtype checks, as mentioned in the document, it is suggested to use single dtype which is float to get the expected behavior. Thanks!
![image](https://user-images.githubusercontent.com/73069040/222528404-72723a1a-08f2-4f6f-9676-1f0450324914.png)

**Comment by sachinprasadhs** [comment] 2023-03-23 05:36
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by sachinprasadhs** 2023-03-23 05:36 UTC
Labels: type:bug/performance, stat:awaiting response from contributor, stalled
