### ISSUE TITLE
Using flow_from_dataframe with predict_generator produces wrong ordering of filenames

### ISSUE THREAD

**Issue by kamal4493** [keras-team/keras#11841] opened 2018-12-10 18:03 UTC
flow_from_dataframe is a very useful function allowing flexibility that flow_from_directory lacks, for e.g, regression tasks.
But the problem with this function is it processes the dataframe's (filename) column in sorted way.
for example
filename  y
a              3.2
d              2.2
c               5.2

in principle, the generator should process files in this way:
a,d,c
but the current implementation processes file in alphabtic order
a,c,d

this is not so convenient for predict_generator function

**Comment by Dref360** [comment] 2018-12-10 18:18
Have you set `shuffle=False` ?

**Comment by albert-92** [comment] 2018-12-13 13:58
I have the same problem. 

This is where it originates from:

_keras-preprocessing/keras_preprocessing/image.py_
```
def _iter_valid_files(directory, white_list_formats, follow_links):
    """Iterates on files with extension in `white_list_formats` contained in `directory`.

    # Arguments
        directory: Absolute path to the directory
            containing files to be counted
        white_list_formats: Set of strings containing allowed extensions for
            the files to be counted.
        follow_links: Boolean.

    # Yields
        Tuple of (root, filename) with extension in `white_list_formats`.
    """
    def _recursive_list(subpath):
        return sorted(os.walk(subpath, followlinks=follow_links),
                      key=lambda x: x[0])

    for root, _, files in _recursive_list(directory):
        for fname in sorted(files):
            for extension in white_list_formats:
                if fname.lower().endswith('.tiff'):
                    warnings.warn('Using \'.tiff\' files with multiple bands '
                                  'will cause distortion. '
                                  'Please verify your output.')
                if fname.lower().endswith('.' + extension):
                    yield root, fname
```

The filenames from the dataframe are getting sorted when they are read out.

Either this should be fixed (remove sorted) or it should be documented.

**Comment by gabrieldemarmiesse** [comment] 2018-12-28 18:53
@Dref360 I labeled this as a bug. Can you confirm?

**Comment by Dref360** [comment] 2018-12-30 19:16
Not a bug, but it should be documented.
Without the sorted, we could get two different lists since os.walk is not deterministic.

**Closed** 2019-01-17 00:02 UTC
Labels: Good first issue, stat:contributions welcome, type:docs
