### ISSUE TITLE
Bugs found in Normalization() and load_model()

### ISSUE THREAD

**Issue by rafak360** [keras-team/keras#15348] opened 2021-09-11 03:39 UTC
First and foremost I reported these bugs at the tensorflow github section which some of the staff told me to post it here.

Setup:
OS: Windows 10 x64
tensorflow-gpu: 2.6.0
Python: 3.9.7
CUDA: 11.2.2
cuDNN: 8.1.1

As in the code below, when loading a model that was normalized by not passing arguments to `Normalization()` it throws an exception when that model is loaded by `load_model()`, however before loading the model I can use it without any apparent issues which makes you think it's all good since `Normalization()` did NOT complain and took care of the input shape. When loading a model that was normalized by `Normalization(input_dim=5)` it does NOT thrown any exception since a known shape is specified. That is weird I mean **it should warn you that when normalizing it without passing arguments to `Normalization()` you should expect an exception when loading it.** This bug also happens in `tensorflow-gpu 2.5.0`.

bug_1.py:
```
import numpy as np
import tensorflow as tf


def main():
    train_data = np.array([[1, 2, 3, 4, 5]])

    train_label = np.array([123])

    normalizer = tf.keras.layers.experimental.preprocessing.Normalization()

    normalizer.adapt(train_data)

    model = tf.keras.Sequential([normalizer, tf.keras.layers.Dense(units=1)])

    model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1), loss='mean_absolute_error')

    model.fit(train_data, train_label, epochs=3000)

    model.save('test.h5')

    model = tf.keras.models.load_model('test.h5')  # Exception is thrown.

    unseen_data = np.array([[1, 2, 3, 4, 6]])

    prediction = model.predict(unseen_data)

    print(prediction)


if __name__ == "__main__":
    main()
```

Exception:
```
Traceback (most recent call last):
  File "E:\Backup\Desktop\bug_1.py", line 28, in <module>
    main()
  File "E:\Backup\Desktop\bug_1.py", line 19, in main
    model = tf.keras.models.load_model('test.h5')
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\save.py", line 200, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\model_config.py", line 52, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\serialization.py", line 208, in deserialize
    return generic_utils.deserialize_keras_object(
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\generic_utils.py", line 674, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\sequential.py", line 434, in from_config
    model.add(layer)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\training\tracking\base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\sequential.py", line 217, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 976, in __call__
    return self._functional_construction_call(inputs, args, kwargs,
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 1114, in _functional_construction_call
    outputs = self._keras_tensor_symbolic_call(
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 886, in _infer_output_signature
    self._maybe_build(inputs)
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\engine\base_layer.py", line 2659, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\censored\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\layers\preprocessing\normalization.py", line 145, in build
    raise ValueError(
ValueError: All `axis` values to be kept must have known shape. Got axis: (-1,), input shape: [None, None], with unknown axis at index: 1

Process finished with exit code 1
```

In addition to that, there is another bug when you load a model, that model gets a significant loss of accuracy, however that does NOT happen in `tensorflow-gpu 2.5.0` which means `tensorflow-gpu 2.6.0` has more bugs than expected.

bug_2.py:
```
import numpy as np
import tensorflow as tf


def main():
    train_data = np.array([[1, 2, 3, 4, 5]])

    train_label = np.array([123])

    normalizer = tf.keras.layers.experimental.preprocessing.Normalization(input_dim=5, axis=None)

    normalizer.adapt(train_data)

    model = tf.keras.Sequential([normalizer, tf.keras.layers.Dense(units=1)])

    model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.1), loss='mean_absolute_error')

    model.fit(train_data, train_label, epochs=3000)

    model.save('test.h5')

    model_loaded = tf.keras.models.load_model('test.h5')

    seen_data = np.array([[1, 2, 3, 4, 5]])

    model_prediction = model.predict(seen_data)

    model_loaded_prediction = model_loaded.predict(seen_data)

    print(f'model prediction:{model_prediction}')  # Expected value close to 123.

    print(f'model loaded prediction: {model_loaded_prediction}')   # Wrong, not even close to 123.


if __name__ == "__main__":
    main()
```

**Comment by sushreebarsa** [comment] 2021-09-13 12:58
@rafak360 I tried to run your code of **bug_1.py** on Colab using **TF v2.6-GPU** and didn't face the **`Traceback error`**  please find the [gist](https://colab.research.google.com/gist/sushreebarsa/4141e0dbf98e48b49e4c2615a5049110/untitled195.ipynb) for reference. I was able to reproduce   **bug_2.py** on Colab using **TF v2.6-GPU** , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a2ff51702af464ca86812337ded3c1d5/untitled194.ipynb) and confirm the same. Could you please refer to the [link](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization) and let us know if it helps?Thank you!

**Comment by FancyXun** [comment] 2021-09-14 05:07
This issue mainly occurs When `Sequential` add `Normalization` layer. After `normalizer.adapt(train_data)`, Normalization's `built` would be set to `True`, which will not lead to [self.build(input_shapes)](https://github.com/keras-team/keras/blob/6859a01cf1df31b8f31e2e8b13aa5db793ec2b4e/keras/engine/base_layer.py#L2724) occurs, but if the model is reloaded, Normalization's built defaults to False, then it will call `self.build(input_shapes)`, the error happens. A workaround is to remove the suffix 'h5', Do not save model as h5 format.

**Comment by SupaHam** [comment] 2021-10-07 23:16
I'm following https://www.tensorflow.org/io/tutorials/elasticsearch with Tensorflow 2.6.0 and Tensorflow-io 0.21.0 and the issue is immediately present. Any advice for a workaround would be appreciated.

**Comment by IAINATTWATER** [comment] 2021-11-12 00:49
Any update to this? Using 2.6 model that was running fine under 2.5 and now presents the above traceback. Additional info, using the Apple Metal plugin.

**Comment by mattdangerw** [comment] 2021-11-12 02:53
Saving with `save_format='tf'` is probably the correct workaround right now. We should really be today erroring out when trying to save the stateful preprocessing layers (TextVectorization, StringLookup, IntegerLookup, Normalization, Discretization) with h5 format.

It probably is quite possible to support h5 for this layer and Discretization though, I can take a look at that.

Is there a reason the workaround of using save format 'tf' is not working?

**Comment by pantelis** [comment] 2021-11-14 18:18
> I'm following https://www.tensorflow.org/io/tutorials/elasticsearch with Tensorflow 2.6.0 and Tensorflow-io 0.21.0 and the issue is immediately present. Any advice for a workaround would be appreciated.

We are also seeing the same issue in Colab with tensorflow-io version: 0.22.0
tensorflow version: 2.7.0 and ES 7.15.2.

**Comment by jvishnuvardhan** [comment] 2021-11-20 03:01
`h5` format limitations listed in the Keras page mentioned that **Does not support preprocessing layers.**. Please check the page https://github.com/keras-team/keras-io/blob/master/guides/ipynb/serialization_and_saving.ipynb

> H5 limitations:
> - External losses & metrics added via `model.add_loss()`
> & `model.add_metric()` are not saved (unlike SavedModel).
> If you have such losses & metrics on your model and you want to resume training,
> you need to add these losses back yourself after loading the model.
> Note that this does not apply to losses/metrics created *inside* layers via
> `self.add_loss()` & `self.add_metric()`. As long as the layer gets loaded,
> these losses & metrics are kept, since they are part of the `call` method of the layer.
> - The *computation graph of custom objects* such as custom layers
> is not included in the saved file. At loading time, Keras will need access
> to the Python classes/functions of these objects in order to reconstruct the model.
> See [Custom objects](#custom-objects).
> - Does not support preprocessing layers.

**Comment by rafak360** [comment] 2021-11-21 03:07
> `h5` format limitations listed in the Keras page mentioned that **Does not support preprocessing layers.**. Please check the page https://github.com/keras-team/keras-io/blob/master/guides/ipynb/serialization_and_saving.ipynb
> 
> > H5 limitations:
> > 
> > * External losses & metrics added via `model.add_loss()`
> >   & `model.add_metric()` are not saved (unlike SavedModel).
> >   If you have such losses & metrics on your model and you want to resume training,
> >   you need to add these losses back yourself after loading the model.
> >   Note that this does not apply to losses/metrics created _inside_ layers via
> >   `self.add_loss()` & `self.add_metric()`. As long as the layer gets loaded,
> >   these losses & metrics are kept, since they are part of the `call` method of the layer.
> > * The _computation graph of custom objects_ such as custom layers
> >   is not included in the saved file. At loading time, Keras will need access
> >   to the Python classes/functions of these objects in order to reconstruct the model.
> >   See [Custom objects](#custom-objects).
> > * Does not support preprocessing layers.

Well that documentation does not make sense for `tensorflow-gpu 2.5.0`, when specifying the preprocessing `Normalization` layer like: `normalizer = tf.keras.layers.experimental.preprocessing.Normalization(input_dim=5, axis=None)` it does seem to work fine with .h5 save formats. That's why I switch back to version 2.5, unfortunately it's been my workaround.

**Comment by mattdangerw** [comment] 2021-11-30 23:14
Bug 2 should now be fixed on tf-nightly. Discretization and normalization should now load back with proper state with h5. Note that the lookup preprocessing layers (StringLookup, IntegerLookup and TextVectorization) will still not function properly with h5. Fix should go out in 2.8, workaround until it releases will be to use the tf save format or use nightly.

For bug 1, the fix most people will want is probably to pass `axis=None` to the Normalization layer. That will have the layer compute a single mean and variance over all the input. The default to the layer is `axis=-1` which computes a separate mean and variance for each position along the last axis. In that case, I think bug 1 is still valid, for some reason we are building the restored model with different input shape that when originally building it, triggering the error in the colab.

**Comment by MuhammadAlBarham** [comment] 2021-12-12 18:04
I am facing the same error, any solution for it?

Here is my code: https://colab.research.google.com/drive/1RHgQ6KsOF7FDmbRAHPyQtXGCtsrAzD0h?usp=sharing

**Comment by IAINATTWATER** [comment] 2021-12-12 18:07
My particular issue was not related to loading models, rather it was creating Normalization layers in Keras. My solution was to drop back to 2.5 and all was good. I have not tried it in 2.7 as yet.  

Best,

Iain

**Comment by rafak360** [comment] 2021-12-12 18:23
> I am facing the same error, any solution for it?
> 
> Here is my code: https://colab.research.google.com/drive/1RHgQ6KsOF7FDmbRAHPyQtXGCtsrAzD0h?usp=sharing

You should specify the `input_dim` according to your input dimensions and set the `axis` to None (see @mattdangerw's answer for more details) in its `preprocessing.Normalization()` parameters.

**Comment by MuhammadAlBarham** [comment] 2021-12-13 20:41
> > I am facing the same error, any solution for it?
> > Here is my code: https://colab.research.google.com/drive/1RHgQ6KsOF7FDmbRAHPyQtXGCtsrAzD0h?usp=sharing
> 
> You should specify the `input_dim` according to your input dimensions and set the `axis` to None (see @mattdangerw's answer for more details) in its `preprocessing.Normalization()` parameters.

I did what you said and my problem has been solved. 

But they mention in the tutorial that the layer can inspect the input shape ( assum that I assign axis to None).

https://www.tensorflow.org/tutorials/keras/regression#linear_regression

**Comment by rafak360** [comment] 2021-12-13 21:07
> > > I am facing the same error, any solution for it?
> > > Here is my code: https://colab.research.google.com/drive/1RHgQ6KsOF7FDmbRAHPyQtXGCtsrAzD0h?usp=sharing
> > 
> > 
> > You should specify the `input_dim` according to your input dimensions and set the `axis` to None (see @mattdangerw's answer for more details) in its `preprocessing.Normalization()` parameters.
> 
> I did what you said and my problem has been solved.
> 
> But they mention in the tutorial that the layer can inspect the input shape ( assum that I assign axis to None).
> 
> https://www.tensorflow.org/tutorials/keras/regression#linear_regression

I'm glad I helped you. Unfortunately the tutorial is out of date as many other tensorflow and keras documentations.

**Comment by alegaros** [comment] 2022-01-04 16:03
This is very relevant. We have an ImageNet-pretrained model (an [EfficientNet](https://www.tensorflow.org/api_docs/python/tf/keras/applications/efficientnet), concretely) that was trained with tensorflow==2.5.0 and saved as an `hdf5` file. 

As you know, TensorFlow's EfficientNet uses a [Normalization](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization) layer, so this bug affects us. We cannot load this model with tensorflow==2.7.0 because the inferences are totally different. The `mean` and `variance` attributes of the `Normalization` layer that are loaded do not correspond to the ones of the ImageNet database, being this the source of the problem.

Will this be fixed on tensorflow==2.8.0?

**Comment by mattdangerw** [comment] 2022-01-04 19:14
@alegaros would it be possible to try test on nightly? We do have a fix for Normalization with h5 coming in 2.8, but it would be good to check with your use case.

**Comment by alegaros** [comment] 2022-01-05 08:57
Thanks for your answer @mattdangerw. I have tried on TensorFlow nightly and everything seems fixed now. Minimal code for reproducibility:

```python
>>> import numpy as np
>>> import tensorflow

>>> print(tensorflow.__version__)
'2.9.0-dev20220104' 
>>> model = tensorflow.keras.applications.EfficientNetB0(weights="imagenet")
>>> model.save('wop.hdf5')
>>> model = tensorflow.keras.models.load_model('wop.hdf5')
>>> model.layers[2].mean
<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0.485, 0.456, 0.406]]]], dtype=float32)>
```

As you can see, the ImageNet's mean is preserved as a layer attribute. I have tried on `2.8.0-rc0` and it is fixed too. I have also tried my use case (model trained on tf 2.5.1), and could confirm the fix on `2.8.0-rc0` and `2.9.0-dev20220104`.

**Comment by jvishnuvardhan** [comment] 2022-01-27 20:15
@rafak360 Is this issue got resolved for you? I see Bug 1  and Bug2 are not throwing any error when `tf-nightly` was used. Please check the gist for [bug 1](https://colab.research.google.com/gist/jvishnuvardhan/370814a7973523bdccb89e398801ef08/untitled1075.ipynb) and [bug2](https://colab.research.google.com/gist/jvishnuvardhan/c41ffe26350d7bf27073428fcac8b7fc/untitled1076.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2022-02-10 20:28 UTC
Labels: type:bug/performance, stat:awaiting response, stalled

**Comment by abderrahmen13** [comment] 2022-03-15 11:01
add "input_shape=[1,], axis=None" in the Normalization function
Ex:
single_feature_normalizer = layers.Normalization(input_shape=[1,], axis=None)

**Comment by ValienX1** [comment] 2023-11-03 13:28
> @rafak360 I tried to run your code of **bug_1.py** on Colab using **TF v2.6-GPU** and didn't face the **`Traceback error`** please find the [gist](https://colab.research.google.com/gist/sushreebarsa/4141e0dbf98e48b49e4c2615a5049110/untitled195.ipynb) for reference. I was able to reproduce **bug_2.py** on Colab using **TF v2.6-GPU** , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a2ff51702af464ca86812337ded3c1d5/untitled194.ipynb) and confirm the same. Could you please refer to the [link](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization) and let us know if it helps?Thank you!

I have same problem. And on your bug_1.py notebook [this one](https://colab.research.google.com/gist/sushreebarsa/4141e0dbf98e48b49e4c2615a5049110/untitled195.ipynb#scrollTo=Z6D87Ta6TWlq) I get same error 
![image](https://github.com/keras-team/keras/assets/57298777/e90940e3-1170-4315-81a6-cf9db7c67f04)

**Comment by rafak360** [comment] 2023-11-03 15:17
> > @rafak360 I tried to run your code of **bug_1.py** on Colab using **TF v2.6-GPU** and didn't face the **`Traceback error`** please find the [gist](https://colab.research.google.com/gist/sushreebarsa/4141e0dbf98e48b49e4c2615a5049110/untitled195.ipynb) for reference. I was able to reproduce **bug_2.py** on Colab using **TF v2.6-GPU** , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a2ff51702af464ca86812337ded3c1d5/untitled194.ipynb) and confirm the same. Could you please refer to the [link](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization) and let us know if it helps?Thank you!
> 
> I have same problem. And on your bug_1.py notebook [this one](https://colab.research.google.com/gist/sushreebarsa/4141e0dbf98e48b49e4c2615a5049110/untitled195.ipynb#scrollTo=Z6D87Ta6TWlq) I get same error 
> ![image](https://github.com/keras-team/keras/assets/57298777/e90940e3-1170-4315-81a6-cf9db7c67f04)
> 
> 

You should specify the input_dim according to your input dimensions and set the axis to None (see @mattdangerw's answer for more details) in its preprocessing.Normalization() parameters.

By the way it's been a long time I don't touch tensorflow but from the time of the original post the tensorflow 2.5 was better than 2.6 since I found out many bugs on 2.6 version, not sure if it's fixed these days. So I recommend you try 2.5 and compare.

**Comment by Cyril9227** [comment] 2025-03-20 08:30
Bug still here in `tf 2.16.1`, saving a trained `tf.keras.applications.EfficientNet` as a `.h5` will result in wrongly initialized `Normalization` layer after loading and wrong inference, saving a `.keras` seems to work
