### ISSUE TITLE
categorical_entropy yields no shape? 

### ISSUE THREAD

**Issue by cottrell** [keras-team/keras#12663] opened 2019-04-12 18:56 UTC
I'm not sure what is going on the with this layer but it does not take an axis dim. Possibly just a feature missing. 

```
In [43]: x = keras.Input(shape=(10,))

In [44]: keras.losses.categorical_crossentropy(x, x, from_logits=True)
Out[44]: <tf.Tensor 'softmax_cross_entropy_with_logits_11/Reshape_2:0' shape=<unknown> dtype=float32>


TypeError: object of type 'NoneType' has no len()

```

**Comment by jvishnuvardhan** [comment] 2019-05-03 16:04
Please fill the issue [template](https://github.com/keras-team/keras/issues/new?template=a--tensorflow-backend-users.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. . Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-03 16:05
The following should work
!pip install keras==2.2.4
from keras.layers import Input
from keras import losses
x = Input(shape=(10,))
losses.categorical_crossentropy(x,x)

**Comment by jvishnuvardhan** [comment] 2019-05-07 22:32
I think it was resolved. I am closing the issue. But, please let me know if I'm mistaken. Thanks!

**Closed by jvishnuvardhan** 2019-05-07 22:32 UTC
Labels: backend:tensorflow, stat:awaiting response, type:support
