### ISSUE TITLE
tried to convert the weights.h5 to onnx format. The github page containing https://github.com/AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow contains the weights.h5.

### ISSUE THREAD

**Issue by Abrahamma97** [keras-team/keras#14164] opened 2020-07-15 14:23 UTC
Hi I had tried to convert the weights.h5 to onnx format. The github page containing https://github.com/AdrianNunez/Fall-Detection-with-CNNs-and-Optical-Flow contains the weights.h5.
Weightsh5toonnxconv.py.txt
Kindly tell me what I am doing wrong and also give me tips on how to make this conversion as perfect as possible.
This is the error on executing Weightsh5toonnxconv.py(I created this script )
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/ubuntu/.local/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
np_resource = np.dtype([("resource", np.ubyte, 1)])
WARNING:tensorflow:From /home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.init (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Model: "sequential"
Layer (type) Output Shape Param #

zero_padding2d (ZeroPadding2 (None, 226, 226, 20) 0

conv1_1 (Conv2D) (None, 224, 224, 64) 11584

zero_padding2d_1 (ZeroPaddin (None, 226, 226, 64) 0

conv1_2 (Conv2D) (None, 224, 224, 64) 36928

max_pooling2d (MaxPooling2D) (None, 112, 112, 64) 0

zero_padding2d_2 (ZeroPaddin (None, 114, 114, 64) 0

conv2_1 (Conv2D) (None, 112, 112, 128) 73856

zero_padding2d_3 (ZeroPaddin (None, 114, 114, 128) 0

conv2_2 (Conv2D) (None, 112, 112, 128) 147584

max_pooling2d_1 (MaxPooling2 (None, 56, 56, 128) 0

zero_padding2d_4 (ZeroPaddin (None, 58, 58, 128) 0

conv3_1 (Conv2D) (None, 56, 56, 256) 295168

zero_padding2d_5 (ZeroPaddin (None, 58, 58, 256) 0

conv3_2 (Conv2D) (None, 56, 56, 256) 590080

zero_padding2d_6 (ZeroPaddin (None, 58, 58, 256) 0

conv3_3 (Conv2D) (None, 56, 56, 256) 590080

max_pooling2d_2 (MaxPooling2 (None, 28, 28, 256) 0

zero_padding2d_7 (ZeroPaddin (None, 30, 30, 256) 0

conv4_1 (Conv2D) (None, 28, 28, 512) 1180160

zero_padding2d_8 (ZeroPaddin (None, 30, 30, 512) 0

conv4_2 (Conv2D) (None, 28, 28, 512) 2359808

zero_padding2d_9 (ZeroPaddin (None, 30, 30, 512) 0

conv4_3 (Conv2D) (None, 28, 28, 512) 2359808

max_pooling2d_3 (MaxPooling2 (None, 14, 14, 512) 0

zero_padding2d_10 (ZeroPaddi (None, 16, 16, 512) 0

conv5_1 (Conv2D) (None, 14, 14, 512) 2359808

zero_padding2d_11 (ZeroPaddi (None, 16, 16, 512) 0

conv5_2 (Conv2D) (None, 14, 14, 512) 2359808

zero_padding2d_12 (ZeroPaddi (None, 16, 16, 512) 0

conv5_3 (Conv2D) (None, 14, 14, 512) 2359808

max_pooling2d_4 (MaxPooling2 (None, 7, 7, 512) 0

flatten (Flatten) (None, 25088) 0
fc6 (Dense) (None, 4096) 102764544

Total params: 117,489,024
Trainable params: 117,489,024
Non-trainable params: 0

Traceback (most recent call last):
File "archtojson.py", line 54, in
model.load_weights('/home/ubuntu/Desktop/onnxkeras/weights.h5')
File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
return super(Model, self).load_weights(filepath, by_name)
File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1424, in load_weights
saving.load_weights_from_hdf5_group(f, self.layers)
File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 737, in load_weights_from_hdf5_group
' layers.')
ValueError: You are trying to load a weight file containing 0 layers into a model with 14 layers.

**Comment by Marwen-Bhj** [comment] 2020-12-10 22:59
I know this is late but you are trying to convert the weights without the definition of the architecture of the model. you need to convert a "model.h5", not the weights (as weights.h5)

**Comment by jvishnuvardhan** [comment] 2021-09-03 01:09
@Abrahamma97 Please let us know whether the above suggestion worked for you or not? 

If you still have an issue with recent `tf` versions, then Please share a simple standalone code to reproduce the issue.  Thanks!

**Comment by jvishnuvardhan** [comment] 2021-09-21 00:48
Closing due to lack of recent activity. Please feel free to reopen when you have more information. Thanks!

**Closed by jvishnuvardhan** 2021-09-21 00:48 UTC
Labels: type:support, stat:awaiting response, stalled
