### ISSUE TITLE
How to substitute a keras layer?

### ISSUE THREAD

**Issue by gcunhase** [keras-team/keras#15049] opened 2021-08-02 06:23 UTC
Hello Keras Team,

I'm attempting to substitute some layers in my custom model with: 
```
model.layers[i] = layers[i]
```
But I'm getting the following error:
```
AttributeError: Can't set the attribute "layers", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.
```

Note that my model is a custom tf model (not a `tf.keras.model`), so unfortunately I cannot use `clone_model()`. Is there an alternative to clone it?

Thank you in advance!

**Comment by rmothukuru** [comment] 2021-08-02 11:14
@gcunhase,
Do you want to replace one of the **`Layers`** of the **`Custom Saved Model`** with another **`Layer`**? Also, can you elaborate on what you mean by **`Custom TF Model`** vs **`tf.keras.Model`**? I didn't understand the difference.

**Comment by gcunhase** [comment] 2021-08-02 11:47
Hi @rmothukuru,

Thank you for your reply.

My goal is to modify some of the layers in my custom model and replace them in the original model.

Ideally, I would do that in a copy of the model, so I tried to `clone_model()` TF's EfficientDet model obtained from their official model zoo [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). However, that gave me an error saying that the model was not of `tf.keras.Model` type.

So I tried directly assigning the modified layer to its relevant index `model.layers[i] = layers[i]`, which did not work as mentioned above.

Please let me know if this explanation clarifies my issue.

**Comment by jvishnuvardhan** [comment] 2021-08-04 16:56
@gcunhase Is it possible for you to create simple standalone code to reproduce the issue. Couple of questions. Are you saving and loading the model and then trying to replace one layer? Do you have access to the code of the original model? Thanks!

**Comment by jvishnuvardhan** [comment] 2021-08-23 23:53
Closing due to lack of recent activity. Please feel free to reopen when you have more information. Thanks!

**Closed by jvishnuvardhan** 2021-08-23 23:53 UTC
Labels: type:support, stat:awaiting response
