### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by GOURAVSUMAN** [keras-team/keras#14180] opened 2020-08-01 15:29 UTC
*TypeError: cannot pickle '_thread.RLock' object
TypeError                                 Traceback (most recent call last)
<ipython-input-27-65e1acad3748> in <module>
----> 1 pickle.dump(learner, open('model.pkl','wb'))
      2 
      3 model = pickle.load(open('model.pkl','rb'))
      4 print(model.predict([['GST TDS RETURN', 'Tax teturn filled', 'Good bless u']]))

TypeError: cannot pickle '_thread.RLock' object

![image](https://user-images.githubusercontent.com/52237592/89104816-d2052b80-d439-11ea-9ff5-491b2323c2c7.png)

**Comment by stacy-ojwang** [comment] 2020-10-09 04:17
i am having the same issue. Can someone please assist.

**Comment by itsrawlinz-jeff** [comment] 2020-11-06 10:08
Same issue..Who's got a solution

**Comment by rohitnishad613** [comment] 2020-12-02 15:11
I have the same issue too.

**Comment by HeinrichWizardKreuser** [comment] 2020-12-13 18:12
has anyone found a fix for this yet? I'm not even using multiprocessing

**Comment by Gourav-infobiz** [comment] 2020-12-14 07:02
> has anyone found a fix for this yet? I'm not even using multiprocessing

Can you please share full error details and the code where you got this error.

**Comment by tkmamidi** [comment] 2020-12-15 07:03
> Maybe follow this -
> https://medium.com/fintechexplained/how-to-save-trained-machine-learning-models-649c3ad1c018

As mentioned in this link, you can save and load keras models without using pickle. 

Save the model: 
```
# serialize to JSON
json_file = model.to_json()
with open(json_file_path, "w") as file:
   file.write(json_file)
# serialize weights to HDF5
model.save_weights(h5_file)
```

Load the model:
```from keras.models import model_from_json
# load json and create model
file = open(json_file, 'r')
model_json = file.read()
file.close()
loaded_model = model_from_json(model_json)
# load weights
loaded_model.load_weights(h5_file)```

Hope this helps!

**Comment by tkmamidi** [comment] 2020-12-17 03:03
This is as other way to do it - 
```
model.save("my_model")
model.save_weights("weights.h5")

from tensorflow import keras
my_model = keras.models.load_model('my_model')
my_model.load_weights("weights.h5")
```

**Comment by sushreebarsa** [comment] 2021-07-26 12:21
@GOURAVSUMAN could you please try as per the above comment and let us know if this issue still persists ? Thanks !

**Comment by sushreebarsa** [comment] 2021-08-03 06:50
Closing this issue due to lack of recent activity .Please feel free to reopen if you still have concern.Thanks!

**Closed by sushreebarsa** 2021-08-03 06:50 UTC
Labels: stat:awaiting response, type:support

**Comment by Lord-O-Binary** [comment] 2022-03-18 15:20
I can confirm saving as json with weights file fixes the threading issue during deepcopy

**Comment by Lord-O-Binary** [comment] 2022-03-18 15:21
> This is as other way to do it -
> 
> ```
> model.save("my_model")
> model.save_weights("weights.h5")
> 
> from tensorflow import keras
> my_model = keras.models.load_model('my_model')
> my_model.load_weights("weights.h5")
> ```
I can confirm saving as json with weights file fixes the threading issue during deepcopy
