### ISSUE TITLE
get_config method for callbacks

### ISSUE THREAD

**Issue by ivanlen** [keras-team/keras#12802] opened 2019-05-08 14:35 UTC
Hi all, this is a feature request.

Since keras objects are not pickeable and I want to save different callbacks configurations, I would like to use a method like the `get_config` method that optimizers have for example.

In this sens I could do
```python
callback_params = somecallback.get_config()
```
and then save these parameters.

I don't know why this method isn't a default method.

I would be more than happy to contribute to this issue if you find it useful.

**Comment by jvishnuvardhan** [comment] 2019-05-11 14:19
@ivanlen Could you provide more details on this feature? Some use cases and contexts where this feature can be helpful. Thanks!

**Comment by ivanlen** [comment] 2019-05-13 13:52
@jvishnuvardhan currently I am tuning hyperparameters of some models, and this includes tuning some hyperparameters of the callbacks and optimizers for example.

The problem with callbacks is that when you are exploring different parameters, it is hard to compare different instances of the same class with different parameters because callbacks do not have the method get_config() and I have to compare one by one the paremeters. These parameters also differ across the different callbacks instances.

**Comment by jvishnuvardhan** [comment] 2019-05-21 05:18
@ivanlen what is the backend you are using? Thanks!

**Comment by ivanlen** [comment] 2019-05-21 12:17
@ivanlen I am using tf backend. Thank you ;)

**Comment by jvishnuvardhan** [comment] 2019-06-03 22:20
@ivanlen Do you have any reproducible code that you can share? Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-17 23:56
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-17 23:56 UTC
Labels: backend:tensorflow, stat:awaiting response, type:feature
