### ISSUE TITLE
error reporting model(x) vs model.predict(x)

### ISSUE THREAD

**Issue by rschumi0** [keras-team/keras#14902] opened 2021-07-11 19:05 UTC
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras: no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the problem**.

The error and warning messages seem to be different when `model(x)` is used instead of `model.predict(x)`  to make a prediction.
Is this intentional and documented somewhere? 
For example, in the following simple model there is a warning when `model.predict(x)` is used, but none for `model(x)`. 
Moreover, it would be generally good to know which warnings (or errors) might not occur when a specific prediction method is used and also which warnings will be the same.

**Standalone code to reproduce the issue**.
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
model = keras.Sequential([
keras.layers.ReLU(threshold=3,  input_shape=(2,))])
x = tf.constant([[[[1,2,3,4,5]]]])
print (np.array2string(model(x).numpy(), separator=', '))
#print (np.array2string(model.predict(x), separator=', '))
```

**Comment by rmothukuru** [comment] 2021-07-13 13:06
Could observe the **`warning`** while using **`model.predict`**. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/2c79a14753fefed07aa3bad1a6c354cb/keras_14902.ipynb) to reproduce the issue.

**Comment by jvishnuvardhan** [comment] 2021-07-28 17:58
@rschumi0 This is a Duplicate of #https://github.com/keras-team/keras/issues/14979

I have opened it on behalf of you. Keras team looked into this issue already. Thanks for creating the issue. 

I will close this issue here. Let us follow the progress here https://github.com/keras-team/keras/issues/14979

**Closed by jvishnuvardhan** 2021-07-28 17:58 UTC
Labels: keras-team-review-pending, type:docs
