### ISSUE TITLE
How to pass callbacks to scikit_learn wrappers (e.g. KerasClassifier)

### ISSUE THREAD

**Issue by kaspermarstal** [keras-team/keras#4278] opened 2016-11-03 11:44 UTC
I want to use `EarlyStopping` and `TensorBoard` callbacks with the `KerasClassifier` scikit_learn wrapper. Normally, when not using scikit_learn wrappers, I pass the callbacks to the fit function [as outlined in the documentation](https://keras.io/callbacks/#usage-of-callbacks). However, when using scikit_learn wrappers, this function is a method of `KerasClassifier`. The documentation mentions that [`sk_params` can contain arguments to the the fit method](https://keras.io/scikit-learn-api/#wrappers-for-the-scikit-learn-api) (among others) but I am unable to figure out how to use `sk_params` to pass callbacks to the fit function inside the `KerasClassifier` class.

My code looks like this (excluding code for loading data into `x` and `encoded_y` for brevity):

```
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasClassifier
from keras.layers import BatchNormalization
from keras.callbacks import EarlyStopping, TensorBoard

from sklearn.model_selection import cross_val_score, StratifiedKFold

# model architecture
def DNN():
    model = Sequential()
    model.add(Dense(512, input_dim=x.shape[1], init='normal', activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))
    model.add(Dense(32, init='normal', activation='relu'))
    model.add(BatchNormalization())
    model.add(Dropout(0.5))
    model.add(Dense(1, init='normal', activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adagrad', metrics=['accuracy'])
    return model

# fix random seed for reproducibility
seed = 8

classifier = KerasClassifier(build_fn=DNN, nb_epoch=32, batch_size=8, verbose=1)
kfold = StratifiedKFold(n_splits=2, shuffle=True, random_state=seed)
results = cross_val_score(classifier, x, encoded_y, cv=kfold, verbose=1)
print("Result: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))
```

Does anyone know how I should use `EarlyStopping` and `TensorBoard` with this setup?

**Comment by Hudler** [comment] 2016-11-04 20:19
I believe it's like this

`classifier = KerasClassifier(build_fn=DNN, nb_epoch=32, batch_size=8, callbacks=[your_callback], verbose=1)`

according to [documentation](https://keras.io/scikit-learn-api/)

**Comment by jfr311** [comment] 2016-11-06 12:53
When I attempted adding the kwarg to the KerasClassifier during a grid search as @Hudler instructs, it resulted in the error documented here #4081 . I have no idea how to solve this from within Keras, but I was able pass the callback to the fit_params kwarg of GridSearchCV.  It looks like cross_val_score also accepts the fit_params kwarg. 

@kaspermarstal Can you try changing this: 
`results = cross_val_score(classifier, x, encoded_y, cv=kfold, verbose=1)` 
into this: 
`results = cross_val_score(classifier, x, encoded_y, cv=kfold, verbose=1, fit_params={'callbacks': [EarlyStopping(), TensorBoard()]})`

n.b. Don't forget to add your own parameters for both EarlyStopping and TensorBoard unless you are using the defaults.

**Comment by Hudler** [comment] 2016-11-07 00:02
@jfr311 Sadly there is another problem. This creates one instance of the Callback which is passed to all fit() calls. I tried using ModelCheckpoint in GridSearchCV and I can see that in first epoch model is not saved because it compares its error against error reached in previous split.

**Comment by jfr311** [comment] 2016-11-07 12:49
Hmm, it seems the best solution overall would be to edit the KerasClassifier such that its constructor sets the parameter 'callbacks' so that each fit call receives it's own instance of Callback, but this may introduce other problems or may not produce the expected results due to its interaction with scikit-learn's clone method.

In the mean time, I suppose you could look into the ModelCheckpoint code and override the method 'on_train_begin' or 'on_train_end' to ensure a new file is created or that the previous results are remove from the instance after being saved to file. There would have to be some logic for creating new file names as to not overwrite the previous results.

**Comment by kaspermarstal** [comment] 2016-11-07 15:09
Thank you for your inputs! @jr311 passing callbacks for fit_params of GridSearchCV indeed does the trick! However the method @Hudler suggested seems more appropriate to me and this is also perhaps the intended interface since it is in the documentation. Is the project interested in a patch @fchollet?

**Comment by Hudler** [comment] 2016-11-07 15:42
Well both options suffer from the same problem. You won't be able to make use of callback in cv in most cases, unless you tweak your keras.

**Comment by jfr311** [comment] 2016-11-07 18:38
I'm simply using the first listed method in the documentation: 

> Values passed to the dictionary arguments of fit, predict, predict_proba, and score methods

GridSearchCV's fit_params argument is used to pass a dictionary to the fit method of the base estimator, the KerasClassifier in this case.

Upon further investigation it looks like when the callback is passed to sk_params and then the estimator is cloned by GridSearchCV, two different instances of the callback are created. Thus the sanity check in clone fails when comparing that the original callback instance and the cloned callback instance (line 117 in sklearn\base.py).

In an attempt to allow callbacks to be passed to sk_params. I added callbacks to the constructor of the BaseWrapper as so:

`def __init__(self, build_fn=None, callbacks=[], **sk_params):`
  `  self.build_fn = build_fn`
  `  self.callbacks = callbacks`
  `  self.sk_params = sk_params`
  ` self.sk_params['callbacks'] = callbacks
 `   self.check_params(sk_params)`

Then I added self.callbacks to the get_params method of the same class:

`def get_params(self, deep=True):`
  `    res = copy.deepcopy(self.sk_params)`
  `    res.update({'build_fn': self.build_fn, 'callbacks': self.callbacks})`
  `    return res`

After testing with my model using callbacks and not using callbacks, no more errors arise and my callbacks function as intended. I don't think this deserves a PR simply because it is already possible to pass in callbacks and the unexpected behavior of ModelCheckpoint is due to that callback's implementation.

@Hudler, I believe this change allows different instances of ModelCheckpoint to be passed to each fit call, but since each instance would have the same file name for saving the checkpoints, it may end up overwriting the file at the begin of the following fit call.

**Comment by gorgitko** [comment] 2016-12-03 21:11
Does someone solve this in order to `EarlyStopping` (and possibly other callbacks) work with `GridSearchCV` with cross-validation? I think that the solution would be to somehow compute the `val_loss` on test data from cv.   So `GridSearchCV` must pass test data from cv to `model.fit(validation_data=(X_test, y_test))`. I am just looking at `GridSearchCV` source and it's horrible (functional style there is very chaotic for me) :smile:

**Comment by ghego** [comment] 2017-04-21 01:12
Also, some methods in scikit-learn do not implement the `fit_params` attribute, for example `learning_curve`

**Comment by Ahmid** [comment] 2017-05-17 09:19
Hello,
I used the following:

```
earlyTB= keras.callbacks.EarlyStopping(monitor='val_loss', patience=2, verbose=0)
TensorB= keras.callbacks.TensorBoard(log_dir='./Graph', histogram_freq=0, write_graph=True, write_images=True)
results = cross_val_score(pipeline, X, Y, cv=kfold, verbose=1, fit_params={'callbacks': [earlyTB, TensorB]})
```

But this error appears:
```
Traceback (most recent call last):
  File "C:/Users/Ahmad/PycharmProjects/keras_network/network_Final.py", line 40, in <module>
    results = cross_val_score(pipeline, X, Y, cv=kfold, verbose=1, fit_params={'callbacks': [tbCallBack1, tbCallBack]})
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\model_selection\_validation.py", line 140, in cross_val_score
    for train, test in cv_iter)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\externals\joblib\parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\model_selection\_validation.py", line 238, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\pipeline.py", line 268, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "C:\Users\Ahmad\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\pipeline.py", line 227, in _fit
    step, param = pname.split('__', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

Does any one know how to solve it?

**Comment by anselal** [comment] 2017-06-17 17:11
I tried passing the callback to scikit functions and it doesn't work for.
What works for me is this. I think you don't have to pass the callback to a function at all. For example I run:

`filepath = "weights-improvement-{epoch:02d}-{acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='acc', verbose=1, save_best_only=True, mode='max')`

and it saves the weights from the checkpoint without any problem.
Can anyone else verify it ???

**Comment by paolof89** [comment] 2017-06-29 09:57
Hi @anselal, 
your solution works for me but I had to use as monitor the 'loss' value instead of the 'val_loss' one.

**Comment by anselal** [comment] 2017-06-29 10:05
@paolof89 Great. The monitor parameter depends on your problem. For me it was a classification problem so I was monitoring the accuracy.

**Comment by edumucelli** [comment] 2017-07-26 22:39
HI @anselal, I have tried your solution and it gave me `ValueError: fit_params is not a legal parameter`.

**Comment by anselal** [comment] 2017-07-27 05:18
@edumucelli It seems that you are using scikit version 0.19 which is still in development. The `fit_params` parameter will be indeed deprecated. I was using version 0.18. You can either downgrade your scikit version to 0.18 or you can pass the `callback_list` directly to the `fit` method as indicated in the documentation

> fit_params : dict, optional
        Parameters to pass to the fit method.
        .. deprecated:: 0.19
           ``fit_params`` as a constructor argument was deprecated in version
           0.19 and will be removed in version 0.21. Pass fit parameters to
           the ``fit`` method instead.

**Comment by anselal** [comment] 2017-10-25 06:40
Anyone ??

**Comment by Josh-Ring-jisc** [comment] 2017-10-25 15:58
Works nicely with Scikit-learn 0.19 and Keras 2.0.5 with TF backend.
Thanks for the report anselal

**Comment by anselal** [comment] 2017-10-25 16:25
I am glad I could help you out guys !!!

**Comment by FrugoFruit90** [comment] 2017-10-30 10:57
Hmmm what about FeatureUnions, though?
I've had this discussion here, about not using fit_params to send anything "downstream":
https://github.com/scikit-learn/scikit-learn/issues/2034 (it's pretty lengthy, scroll down to see the relevant part).

From what I can tell, the situation is as follows: As described in this thread, I can't send callbacks through the constructor, as then the object can't be cloned. However, I can't send callbacks through fir_params either (in case of pipelines with feature_unions) due to what was written in the link above.

Can someone confirm my observation? :D

**Comment by kishoreiitd** [comment] 2018-06-22 12:05
@jfr311 Thanks for providing such a detailed explanation, However even after modifying base wrapper class, still I am getting an error. The error which I have received is as follows:-
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
Can anybody confirm if they have received it?

Thanks in advance!

**Comment by littlewine** [comment] 2018-07-05 15:18
I have sort of the same issue (caused by the same reasons). 
I have been trying to plot the learning_curves of a CNN (which never accepted the fit_params argument in the first place), with a varying number of epochs - depending on the # of training examples (which is important, as training the same # epochs with 1/5 of the data will greatly overfit).

I am trying to use EarlyStopping as a callback, but I get the following error:
```
model = KerasClassifier(build_fn=create_model , batch_size=batch_size, epochs=epochs, verbose=1, callbacks = [EarlyStopping(patience=0)] )
learning_curve(model, ...)
>>> Cannot clone object <keras.wrappers.scikit_learn.KerasClassifier object at 0x7f129fae8390>, as the constructor does not seem to set parameter callbacks
```

What confuses me is that from the documentation of the [wrapper](https://keras.io/scikit-learn-api/), I can see that the params should be passed into the .fit method, so I can't see why it's not working.

@anselal I am not sure if I understood your solution correctly, but how can you pass directly arguments in the fit method without using 'fit_params' or passing them in the `KerasClassifier`?

Thanks!

**Comment by anselal** [comment] 2018-07-06 05:21
@littlewine it is been a year since I suggested this solution and the APIs have changed since then.

As I quoted  `fit_params` is deprecated since scikit v0.19 and will be removed in version 0.21. Pass fit parameters to the ``fit`` method instead.

I was using Gridsearch and version 0.18 of scikit so I passed it to `fit_params`.

the KerasClassifier wrapper suggests that you pass it to `**sk_params`

From the wrapper documentation:

> Values passed to the **dictionary** arguments of fit, predict, predict_proba, and score methods

So fit=dict(callbacks=callbacks_list)
So I guess you can try something like this:

`model = KerasClassifier(build_fn=create_model , batch_size=batch_size, epochs=epochs, verbose=1, fit = dict(callbacks=[EarlyStopping(patience=0)]) )`

**Comment by kakoli** [comment] 2019-09-02 03:43
If we pass checkpoint as callback to gridSearchCV.fit function, then we can save the accuracy/loss only on the training set and not for the validation sets as is possible in keras Sequential model.fit.
Typically we are more concerned with the monitoring of validation set, hence this is not very useful. Any alternatives?

**Comment by ronammar** [comment] 2019-12-18 16:55
Struggling with this as well. The following syntax works for me:

```python
early_stopper= EarlyStopping(monitor='loss')
estimator= KerasClassifier(build_fn=build_model, epochs=500, batch_size=10, verbose=0)
results= cross_val_score(estimator, x, y, cv=foldsList, n_jobs=-1,
                         fit_params={'callbacks': [early_stopper]})
```

**Comment by ZhiliangWu** [comment] 2019-12-31 11:21
@kakoli With some sacrifices on the training set, you can set the `validation_split` when fitting the model. In that case, you will make it internally split the training set into train and validation and get the validation loss back into your callbacks.

**Closed** 2021-06-24 21:21 UTC
