### ISSUE TITLE
Creating a fixed embedding layer (with "trainable=False") still shows up as having trainable params in the model's summary

### ISSUE THREAD

**Issue by untilted** [keras-team/keras#19398] opened 2024-03-28 18:55 UTC
I'm following the example on https://keras.io/examples/nlp/pretrained_word_embeddings/ and noticed that when the summary is printed, the embedding layer's parameters are still counted in the "Trainable params" part of the summary, even though the layer is initialized with `trainable=False`. This result from `summary` can also be seen in the link.

When trying `model.summary(show_trainable=True)`, the embedding layer does appear with `trainable=N` as expected. Not sure if this is an issue with the summary method or if the parameters of the layer are actually being trained.

Keras version 3.0.5

**Comment by SuryanarayanaY** [comment] 2024-04-01 06:34
Hi @untilted ,

I have replicated the reported issue and attached gist. It needs to check why Embedding parameters showing as trainable params even after setting it to `trainable=False`. 

Also `model.summary(show_trainable=True)` output also seems incorrect to me as it is not showing non_trainable params count. It seems the issue is with `model.summary()`  which needs to be checked. Will go through it and keep you update. 
Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/235a2fb1ef7ce17fdfe04b72b251499d/19398_pretrained_word_embeddings.ipynb) for reported behaviour.

Thanks!

**Comment by SuryanarayanaY** [comment] 2024-04-05 04:06
Hi @untilted ,

This has been fixed in this [commit](https://github.com/keras-team/keras/commit/471edf24d9aa769797efdcdc112de9a3e260032d).

**Comment by jc-louis** [comment] 2024-04-05 07:13
Fixed for me with `keras-nightly==3.2.0.dev2024040503`

**Comment by SuryanarayanaY** [comment] 2024-04-08 06:04
> but I still get OOM which seems to indicate that the embeddings are not freezed.

Hi @jc-louis ,

I have tested the above code in colab env and got OOM error during vectorization of training data. This seems the dataset needs more memory than in colab environment. 
 
Could you please provide more details like Memory size and at whether OOM occured during training stage etc?

**Comment by SuryanarayanaY** [comment] 2024-04-08 06:06
Screenshot of OOM attached for reference.

<img width="1496" alt="Screenshot 2024-04-08 at 11 27 59 AM" src="https://github.com/keras-team/keras/assets/116063290/4cdeca24-cff7-4f34-894f-f5535cf69719">

**Comment by fchollet** [comment] 2024-04-11 21:10
This issue has been fixed previously.

**Closed by fchollet** 2024-04-11 21:10 UTC
Labels: stat:awaiting response from contributor, type:Bug
