### ISSUE TITLE
UnicodeEncodeError when running keras.model.predict

### ISSUE THREAD

**Issue by geniusonanotherlevel** [keras-team/keras#19386] opened 2024-03-27 01:37 UTC
The following problem occurs in keras version 3.1.1 (tensorflow version 2.16.1)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>

prediction = trained_nn_model.predict(last_sequence)
A bit more details:
  File "...\lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "...\.pyenv\pyenv-win\versions\3.10.5\lib\encodings\cp1252.py", line 20, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 19-38: character maps to <undefined>

(The positions varies when tried with different test data).
The code works ok with keras version 2.15.0 (tensorflow 2.15.0)

**Comment by SuryanarayanaY** [comment] 2024-03-27 08:05
Hi @geniusonanotherlevel ,

The issue seems to be with preprocessing steps. With the given info I am not sure to say whether this is Keras issue or not. 
It seems the error is related to encoding and may be adding `encoding="utf-8" ` might helps. If it not resolved with this 
 please provide more details along with a repro code snippet.

Thanks!

**Comment by ryand626** [comment] 2024-03-27 19:09
I’m seeing this in Windows 11, but not in Windows 10, or Mac.

**Comment by ryand626** [comment] 2024-03-27 19:41
It was working with Keras <3.0, but after updating to 3.1.1 it breaks for Windows 11 runs executed by Snakemake in a git bash conda environment.

If I copy/paste the same command Snakemake ran into the git bash conda environment and run it: it succeeds.

I have set the `KERAS_BACKEND` environment variable to `tensorflow`, but I suspect there are other environment shenanigans at play I am unaware of.

I get the same `19-38: character maps to <undefined>` error when running `model.fit` as the OP (exact position match).

**Comment by geniusonanotherlevel** [comment] 2024-03-27 21:47
Hi @SuryanarayanaY , thanks for the response. It can be noted that I did try to to add encoding of utf-8 with the numpy array, but that wasn't an acceptable option as it only accepted ascii, latin & something else which I can't remember. But the fact that it works with an earlier version of tensorflow/keras while all the pre-processing steps and versions of other packages are exactly the same, is why I suspected keras. I've also noted your request for repro code, I will try and get that next week.

@ryand626 , I'm running on Windows 10.

**Comment by SuryanarayanaY** [comment] 2024-03-28 05:49
Hi @geniusonanotherlevel ,

I will be waiting for your repro code. Thanks!

**Comment by SuryanarayanaY** [comment] 2024-04-01 06:56
Hi @geniusonanotherlevel ,

Could you please provide repro for same. Thanks!

**Comment by geniusonanotherlevel** [comment] 2024-04-03 06:10
> Hi @geniusonanotherlevel ,
> 
> Could you please provide repro for same. Thanks!

Hi, thanks for the reminder. I don't have the code with me atm, so I will do when I go back to the office (I'm just not sure which day I'll be there yet... but soon) Thanks for your patience.

**Comment by eliadom** [comment] 2024-04-21 16:32
Same issue here on FastAPI. However, my `model.fit` will work as expected when running locally, just throw the `character maps to <undefined>` when on the FastAPI function called by client.

**Comment by paulheisterkamp97** [comment] 2024-04-23 12:56
Got the same Problem with version keras 3.3.1 and tf  2.16.1 on windows 10. Unfortunately the stack trace of this error does not show the origin but with keras.config.disable_traceback_filtering() you can print out the whole stacktrace:

```python
 File "C:\Users\heisterkamp\Desktop\Git\tfx-pipeline\.venv\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 316, in fit
    callbacks.on_train_batch_end(step, logs)
  File "C:\Users\heisterkamp\Desktop\Git\tfx-pipeline\.venv\Lib\site-packages\keras\src\callbacks\callback_list.py", line 106, in on_train_batch_end
    callback.on_train_batch_end(batch, logs=logs)
  File "C:\Users\heisterkamp\Desktop\Git\tfx-pipeline\.venv\Lib\site-packages\keras\src\callbacks\progbar_logger.py", line 58, in on_train_batch_end
    self._update_progbar(batch, logs)
  File "C:\Users\heisterkamp\Desktop\Git\tfx-pipeline\.venv\Lib\site-packages\keras\src\callbacks\progbar_logger.py", line 95, in _update_progbar
    self.progbar.update(self.seen, list(logs.items()), finalize=False)
  File "C:\Users\heisterkamp\Desktop\Git\tfx-pipeline\.venv\Lib\site-packages\keras\src\utils\progbar.py", line 182, in update
    io_utils.print_msg(message, line_break=False)
  File "C:\Users\heisterkamp\Desktop\Git\tfx-pipeline\.venv\Lib\site-packages\keras\src\utils\io_utils.py", line 98, in print_msg
    sys.stdout.write(message)
  File "C:\Users\heisterkamp\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
```

The progress bar seems to be the problem here, maybe using the wrong character? but the problem itself seems to be on Keras side. I hope this will be fixed in the future, since the status printouts are helpful for quick testing. 

But for now verbose=0 has to do.

**Comment by slievens** [comment] 2024-05-27 13:56
I had/have the same issue when using "shiny for Python".
Adding `verbose=0` to `model.predict` fixes the error.

**Comment by eliadom** [comment] 2024-05-30 19:36
> I had/have the same issue when using "shiny for Python". Adding `verbose=0` to `model.predict` fixes the error.

Thank you very much. My problem was fixed by adding `verbose=2` to both `model.fit` and `model.predict` functions.

**Comment by krosh-id** [comment] 2024-08-01 16:19
Thanks. I had the same problem and it was solved in a similar way, after several hours of searching for the cause of the error

**Closed** 2024-11-03 17:59 UTC
Labels: type:support
