### ISSUE TITLE
Math Bug in tf.keras.regularizers.OrthogonalRegularizer

### ISSUE THREAD

**Issue by hramadas** [keras-team/keras#16682] opened 2022-06-15 05:00 UTC
The current implementation of `tf.keras.regularizers.OrthogonalRegularizer` penalizes the dot product between rows (or columns) of the input matrix.

Using this as a regularizer would result in the rows (or columns) being antiparallel (dot product = -1) instead of orthogonal (dot product = 0).

This could be fixed either by squaring or taking the absolute value of the dot product.

https://github.com/keras-team/keras/blob/v2.9.0/keras/regularizers.py#L323

**Comment by tilakrayal** [comment] 2022-06-15 11:55
@hramadas,
Could you share a reproducible code that supports your statement so that the issue can be easily understood? Thank you!

**Comment by hramadas** [comment] 2022-06-15 20:38
Consider the vectors `[1, 2]` and `[-1, -2]`. Since these are antiparallel (i.e. point in opposite directions) and not orthogonal,  `OrthogonalRegularizer` should penalize a matrix composed of these vectors. In other words the `__call__` method applied to such a matrix should return a positive scalar.

However, running the code below:
```
import tensorflow as tf

assert(tf.__version__ == "2.9.0")

reg = tf.keras.regularizers.OrthogonalRegularizer(
    factor=1., mode='rows'
)

x = tf.Variable([
    [1., 2.],
    [-1., -2.]
])

print(reg(x))
```
returns a negative scalar: `<tf.Tensor: shape=(), dtype=float32, numpy=-0.99999994>`.

**Comment by tilakrayal** [comment] 2022-06-16 16:34
@hramadas,
This issue has been resolved in the tf-nightly version. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/efbd438cfeee49b28d4a7a7b3ffef242/16682.ipynb). Thank you!

**Comment by hramadas** [comment] 2022-06-16 17:25
Thank you!

**Comment by tilakrayal** [comment] 2022-06-17 02:33
@hramadas,
 Glad the issue is resolved for you, please feel free to move this to closed status.

**Closed** 2022-06-17 02:36 UTC
Labels: stat:awaiting response, type:Bug

**Comment by tilakrayal** [comment] 2022-06-17 02:37
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
