### ISSUE TITLE
TypeError: TimeseriesGenerator object is not an iterator in Colab

### ISSUE THREAD

**Issue by cmp1** [keras-team/keras#13067] opened 2019-07-05 12:43 UTC
**I am trying to fit an LSTM-RNN using a time series generator based on on a pandas dataframe. When I attempt to train the model, I get the following error:**

_"
Epoch 1/20
Exception in thread Thread-12:
Traceback (most recent call last):
  File "<embedded stdlib>/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "<embedded stdlib>/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/export/hda3/borglet/remote_hdd_fs_dirs/0.colab_kernel_tensorflow_gpu_chrisprice.kernel.chrisprice.157145873468.14b334fb3717c109/mount/server/colab_notebook.par/google3/third_party/py/keras/utils/data_utils.py", line 633, in data_generator_task
    generator_output = next(self._generator)
TypeError: TimeseriesGenerator object is not an iterator
"_

**Please see my code below**

from keras.models import Sequential
from keras.layers import Dense, LSTM

n_input = 1

train_data_gen = sq.TimeseriesGenerator(x_train_scaled, y_train_scaled,
	length=n_input, sampling_rate=1, batch_size=8)

model = Sequential()
model.add(LSTM(8, input_shape=(no_samples, 3)))
model.add(Dense(8))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit_generator(train_data_gen, epochs=20, steps_per_epoch=25)

**Comment by dabasajay** [comment] 2019-07-05 13:08
Which Keras version are you using? Check using `print(keras.__version__)`

**Comment by cmp1** [comment] 2019-07-05 13:11
Hi Ajay,

Currently running in 2.2.4

**Comment by dabasajay** [comment] 2019-07-05 14:02
Did you import `TimeseriesGenerator` using `from keras.preprocessing.sequence import TimeseriesGenerator` **or** `from keras_preprocessing.sequence import TimeseriesGenerator` ?

**Comment by cmp1** [comment] 2019-07-05 14:08
imported from 'keras_preprocessing.sequence''

**Comment by cmp1** [comment] 2019-07-05 14:11
However please note I have imported from both
keras.preprocessing.sequence.TimeseriesGenerator
and keras_preprocessing.sequence

**Comment by dabasajay** [comment] 2019-07-05 14:34
Well, if you import using `from keras_preprocessing.sequence import TimeseriesGenerator`, then `TimeseriesGenerator` is not an iterator and it'll throw an error however if you import using `keras.preprocessing.sequence import TimeseriesGenerator`, then `TimeseriesGenerator` is an iterator and it should work. Please try this and let me know how it goes.

**Comment by cmp1** [comment] 2019-07-05 15:07
Hi Ajay,

Sadly I am getting the same error with keras.preprocessing.sequence


[image: Screenshot 2019-07-05 at 16.06.55.png]

**Comment by dabasajay** [comment] 2019-07-05 15:46
I can't find the source code for `data_generator_task()` function in `keras.utils.data_utils.py` file. I suggest you update your Keras version using command:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

**Comment by cmp1** [comment] 2019-07-07 18:01
Hi Ajay does this mean this is a bug? sadly I am importing this from a
company library so unable to update>

**Comment by dabasajay** [comment] 2019-07-08 15:44
Well, I reproduced the error with this:
![1](https://user-images.githubusercontent.com/38384266/60823380-08379380-a1c5-11e9-84f9-78dc804446d0.png)

Now, if I remove(comment) the line `from keras_preprocessing.sequence import TimeseriesGenerator` and use `from keras.preprocessing.sequence import TimeseriesGenerator` instead then I am able to train the model.
![2](https://user-images.githubusercontent.com/38384266/60823461-34ebab00-a1c5-11e9-982a-a0b2e3b581a5.png)

Note that I'm using the latest version of Keras. So I guess these images support both of arguments that you should update your Keras version using `pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps` and use `from keras.preprocessing.sequence import TimeseriesGenerator` instead of other one.

**Comment by cmp1** [comment] 2019-07-09 13:43
Good point - I will see what can be done internally! Very much appreciate
your help Ajay. Thank you!

**Comment by jvishnuvardhan** [comment] 2019-07-09 17:06
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken.Thanks!

**Closed by jvishnuvardhan** 2019-07-09 17:06 UTC
Labels: backend:tensorflow, type:support
