### ISSUE TITLE
k-fold save model error

### ISSUE THREAD

**Issue by mechsihao** [keras-team/keras#15855] opened 2022-01-04 17:45 UTC
# Background:
I want to train a two-dense-layer classification model, I use the k-fold strategy to train it and use tf.keras.callback.checkpoint utils to save the best model weights:

`RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')`

I tried to change the version of h5py to fix this bug, but it did not work.(2.10.0 ~ 3.6.0).
This bug will be occured `randomly`, it seems like bugs more frequently when training cost time shorter，It seems like when training a k-fold model, the model will be saveing parallel, then this bug will be occurred.

# when I track to source code of keras, the save_weights function is just like that:
```python
def save_weights(self, filepath, overwrite=True):
    ...
    with h5py.File(filepath, 'w') as f:
        saving.save_weights_to_hdf5_group(f, self.layers)
        f.flush()
saving.save_weights_to_hdf5_group means save weights into the HDF5 group
```
# This bug can be repeated by those codes:
```python
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import KFold
import numpy as np

input_dim = 256
input_x = Input(input_dim,)
x = Dense(128, activation='relu')(input_x)
p = Dense(2, activation='sigmoid')(x)
model = Model(inputs=input_x, outputs=p)

model.compile(loss='mse', optimizer=Adam(1e-5), metrics = ['acc'])

sample_num = 2000
train, label = np.random.random((sample_num, input_dim)), np.random.random((sample_num, 2))
kfold = KFold(n_splits=5)
for i, (train_ind, valid_ind) in enumerate(kfold.split(list(range(sample_num)))):
    model_path = f'model-{i}.h5'
    ckpt = ModelCheckpoint(model_path, monitor='val_loss')
    model.fit([train[train_ind], label[train_ind]], label[train_ind], validation_data=[train[valid_ind], label[valid_ind]], epochs=10, batch_size=64, callbacks=[ckpt])
```
# More detailed bug information is:
```python
Traceback (most recent call last):
  File "/home/notebook/code/personal/test_sihao/gitcode/oCTS_lsh/train_tf2.py", line 36, in <module>
    current_train_pickle_path, n_fold=5, monitor='val_categorical_crossentropy')
  File "/home/notebook/data/group/sihao_work/gitcode/oCTS_lsh/classifier/b4k_classifier_tf2.py", line 186, in model_train_kfold
    self.train(model, train_D, valid_D, tmp_model_save_path, monitor=monitor)
  File "/home/notebook/data/group/sihao_work/gitcode/oCTS_lsh/classifier/b4k_classifier_tf2.py", line 159, in train
    callbacks=[early_stopping, plateau, checkpoint])
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 331, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 311, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 969, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 998, in _save_model
    self.model.save_weights(filepath, overwrite=True)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 1315, in save_weights
    self._ckpt_saved_epoch).encode('utf8')
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 544, in __exit__
    self.close()
  File "/opt/conda/lib/python3.7/site-packages/h5py/_hl/files.py", line 526, in close
    self.id._close_open_objects(h5f.OBJ_LOCAL | h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 358, in h5py.h5f.FileID._close_open_objects
RuntimeError: Can't decrement id ref count (unable to close file, errno = 5, error message = 'Input/output error')
Segmentation fault
```

**Comment by qlzh727** [comment] 2022-01-05 17:58
Triage notes: Assign to Rick since this is related to model checkpoint callbacks. There might be a race condition somewhere.

**Comment by jvishnuvardhan** [comment] 2022-01-27 20:59
@mechsihao This is not a bug. There is a small change required from user's side as shown below.

```
 # model.fit([train[train_ind], label[train_ind]], label[train_ind], validation_data=[train[valid_ind], label[valid_ind]], epochs=10, batch_size=64) #, callbacks=[ckpt]
  model.fit(x=train[train_ind], y=label[train_ind], validation_data=(train[valid_ind], label[valid_ind]), epochs=10, batch_size=64, callbacks=[ckpt]) 
```

With the above change, everything worked as expected. [Here](https://colab.research.google.com/gist/jvishnuvardhan/fc4382436aa37c0b4b2a12c89098614f/untitled1147.ipynb) is a gist for reference.

Please verify once and close the issue if this was resolved for you. Thanks!

**Closed** 2022-01-28 17:37 UTC
Labels: type:support, stat:awaiting response

**Comment by jvishnuvardhan** [comment] 2022-02-01 00:35
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
