### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded while calling a Python object" after adding layer to model

### ISSUE THREAD

**Issue by Joerg99** [keras-team/keras#12081] opened 2019-01-20 11:23 UTC
Using Keras 2.2.4:
I added the second line (logits_temp...) to my code which causes problems saving the model. If I remove the second line and use 'output' directly as an input instead of 'logits_temperature' everything is fine.
Training the model would still  work. So I assume that it's just something with saving.
Why is that? Whats the solution? See code for saving below. The error pops up at 'self.models[modelName].save(savePath, True)'. The full error trace is also attached.

```
output = shared_layer
logits_temperature = Lambda(lambda x : x / self.params['temperature'])(output)
TimeDistributed(Dense(n_class_labels, activation='softmax'), name=modelName+'_softmax')(logits_temperature) 

```

```
def saveModel(self, modelName, epoch, dev_score, test_score):
        import json
        import h5py

        if self.modelSavePath == None:
            raise ValueError('modelSavePath not specified.')

        savePath = self.modelSavePath.replace("[DevScore]", "%.4f" % dev_score).replace("[TestScore]", "%.4f" % test_score).replace("[Epoch]", str(epoch+1)).replace("[ModelName]", modelName)

        directory = os.path.dirname(savePath)
        if not os.path.exists(directory):
            os.makedirs(directory)

        if os.path.isfile(savePath):
            logging.info("Model "+savePath+" already exists. Model will be overwritten")

        self.models[modelName].save(savePath, True)

        with h5py.File(savePath, 'a') as h5file:
            h5file.attrs['mappings'] = json.dumps(self.mappings)
            h5file.attrs['params'] = json.dumps(self.params)
            h5file.attrs['modelName'] = modelName
            h5file.attrs['labelKey'] = self.datasets[modelName]['label']
```

  ```
File "/home/joerg/applications/envs/tud_lm/lib/python3.5/site-packages/keras/engine/network.py", line 1263, in __getstate__
    return saving.pickle_model(self)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/site-packages/keras/engine/saving.py", line 429, in pickle_model
    _serialize_model(model, f)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/site-packages/keras/engine/saving.py", line 83, in _serialize_model
    model_config['config'] = model.get_config()
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/site-packages/keras/engine/network.py", line 931, in get_config
    return copy.deepcopy(config)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 218, in _deepcopy_list
    y.append(deepcopy(a, memo))
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 223, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 223, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 297, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 243, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/joerg/applications/envs/tud_lm/lib/python3.5/copy.py", line 151, in deepcopy
    cls = type(x)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by tRosenflanz** [comment] 2019-01-23 23:47
Had something similar happen a while back. I think it is the problem with how lambda layers are saved. It attempts to save the full `self` whatever it is, to be able to access its `params` later on. 
Try this: 
```
output = shared_layer
temp= self.params['temperature']
logits_temperature = Lambda(lambda x : x / temp)(output)
TimeDistributed(Dense(n_class_labels, activation='softmax'), name=modelName+'_softmax')(logits_temperature) 
```
which should prevent the lambda function (and layer) from referencing the `self` object and instead point it to a simple `temp` variable

**Comment by Joerg99** [comment] 2019-01-24 09:41
> Had something similar happen a while back. I think it is the problem with how lambda layers are saved. It attempts to save the full `self` whatever it is, to be able to access its `params` later on.
> Try this:
> 
> ```
> output = shared_layer
> temp= self.params['temperature']
> logits_temperature = Lambda(lambda x : x / temp)(output)
> TimeDistributed(Dense(n_class_labels, activation='softmax'), name=modelName+'_softmax')(logits_temperature) 
> ```
> which should prevent the lambda function (and layer) from referencing the `self` object and instead point it to a simple `temp` variable

Yes, this helped! Thank you!

**Comment by monicadsong** [comment] 2020-12-22 01:37
Thanks @tRosenflanz for providing the solution! It seems like in general the lambda function should be for "simple stateless computation" [1], so you may running into issue referencing variables inside the lambda function.

Adding the additional following two workarounds for posterity, if folks would like more ways to reference class attributes (in this case, `self.temperature`) in their lambda layers.

1) Subclass a tf.keras.Model and define a `get_config` method:
```
class SubclassedModel(tf.keras.Model):
  def __init__(self):
    super(SubclassedModel, self).__init__()
    self.temperature = 10
    self.l = tf.keras.layers.Lambda(lambda x: x / self.temperature)

  def call(self, a):
    return self.l(a)

  def get_config(self):
    return {'temperature': self.temperature}
  
  @classmethod
  def from_config(cls, config):
    return cls(**config)

m = SubclassedModel()
m.predict([1, 10])
m.save('/tmp/m')
f = tf.keras.models.load_model("/tmp/m")
f([[tf.constant(5)]])
```

2) use the Sequential model building API : 
```
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, input_shape=(1,)))
model.temperature = 10
model.add(tf.keras.layers.Lambda(lambda x: x / model.temperature))
model(tf.constant([[2.]]))
model.save('/tmp/m')
f = tf.keras.models.load_model("/tmp/m")
f(tf.constant([[2.]]))
```

I believe that there have been sufficient solutions provided, the root cause identified, and in general, keras Lambda Layers should be used for stateless computation-- would it be possible to close this now? Thanks!

[1] https://keras.io/api/layers/core_layers/lambda/

**Closed** 2021-06-24 22:35 UTC
Labels: To investigate
