### ISSUE TITLE
Concatenate layer error unhashable type: 'Dimension'

### ISSUE THREAD

**Issue by gilgarad** [keras-team/keras#12742] opened 2019-04-26 02:30 UTC
I was trying to do a simple test; Concatenating two layers.

Below is the code

```
inputs = Input(shape=(seq_length, latent_dim)) # seq_length = 3, latend_dim=2
reshaped_d_inputs = Reshape((inputs.get_shape()[1] * inputs.get_shape()[2], ))(inputs)
print(reshaped_d_inputs.get_shape()) # (?, 3, 2)
repeat_d_repeat = RepeatVector(seq_length)(reshaped_d_inputs)
repeat_d = Reshape((seq_length, inputs.get_shape()[1], inputs.get_shape()[2]))(repeat_d_repeat)
print(repeat_d.get_shape()) # (?, 3, 3, 2)


permuted_e = Permute((2, 1))(inputs)
reshaped_e_inputs = Reshape((inputs.get_shape()[1] * inputs.get_shape()[2], ))(permuted_e)
permuted_e_repeat = RepeatVector(seq_length)(reshaped_e_inputs)
repeat_e = Reshape((seq_length, inputs.get_shape()[2], inputs.get_shape()[1]))(permuted_e_repeat)
repeat_e = Permute((1, 3, 2))(repeat_e)
print(repeat_e.get_shape()) # (?, 3, 3, 2)

outputs = Concatenate(-1)([repeat_d, repeat_e])
model = Model(inputs=inputs, outputs=outputs)
model.compile(optimizer='rmsprop', loss='mse')
output_array = model.predict(input_array)
```

But it emits an error like below

> TypeError                                 Traceback (most recent call last)
> <ipython-input-95-11688d9ddbec> in <module>
>      14 print(repeat_e.get_shape())
>      15 
> ---> 16 outputs = Concatenate(-1)([repeat_d, repeat_e])
>      17 model = Model(inputs=inputs, outputs=outputs)
>      18 model.compile(optimizer='rmsprop', loss='mse')
> 
> d:\igs_projects\nlp_nlu\venv\lib\site-packages\keras\engine\base_layer.py in __call__(self, inputs, **kwargs)
>     429                                          'You can build it manually via: '
>     430                                          '`layer.build(batch_input_shape)`')
> --> 431                 self.build(unpack_singleton(input_shapes))
>     432                 self.built = True
>     433 
> 
> d:\igs_projects\nlp_nlu\venv\lib\site-packages\keras\layers\merge.py in build(self, input_shape)
>     355         for i in range(len(reduced_inputs_shapes)):
>     356             del reduced_inputs_shapes[i][self.axis]
> --> 357             shape_set.add(tuple(reduced_inputs_shapes[i]))
>     358         if len(shape_set) > 1:
>     359             raise ValueError('A `Concatenate` layer requires '
> 
> **TypeError: unhashable type: 'Dimension'**

I do not know if it is me doing something wrong or Keras bug...

After digging a while I realize that the tensor of right after the RepeatVector could be Concatenate but won't be concatenated once the posterior code is added.

**Comment by jvishnuvardhan** [comment] 2019-05-08 20:43
Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by metador** [comment] 2019-05-21 01:27
I am facing the same issue. The resolution provided [https://github.com/keras-team/keras/issues/5972](#5972)  does not work.

**Comment by jvishnuvardhan** [comment] 2019-05-21 04:42
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Closed by jvishnuvardhan** 2019-05-21 04:42 UTC
Labels: stat:awaiting response, type:support

**Comment by QuantumLiu** [comment] 2019-06-20 06:22
@gilgarad I sloved it in #12963

**Comment by Mekholika** [comment] 2023-12-14 16:52
@gilgarad Are you able to solve this problem? I am also facing the same problem.
