### ISSUE TITLE
Bug with combination of initial state on recurrent layers and multi_gpu_model

### ISSUE THREAD

**Issue by bezigon** [keras-team/keras#10830] opened 2018-08-02 09:55 UTC
### Reproducing code #1

```python
import numpy as np

import keras
from keras import layers as L

from keras.models import Sequential, Model

from keras.utils.multi_gpu_utils import multi_gpu_model

x = L.Input((4,3))
y = L.SimpleRNN(3,return_sequences=True)(x)

_x = np.random.randn(2,4,3)
_y = np.random.randn(2,4,3)

m = Model(x,y)
m.compile(loss='mean_squared_error',optimizer='adam')
m.train_on_batch(_x,_y)

print("Success!")

m2 = multi_gpu_model(m,2)
m2.compile(loss='mean_squared_error',optimizer='adam')
m2.train_on_batch(_x,_y)

print("Success 2!")

x = L.Input((4,3))
init_state = L.Input((3,))
y = L.SimpleRNN(3,return_sequences=True)(x,initial_state=init_state)

_x = [np.random.randn(2,4,3),np.random.randn(2,3)]
_y = np.random.randn(2,4,3)

m = Model([x,init_state],y)
m.compile(loss='mean_squared_error',optimizer='adam')
m.train_on_batch(_x,_y)

print("Success 3!")

m2 = multi_gpu_model(m,2)
m2.compile(loss='mean_squared_error',optimizer='adam')
m2.train_on_batch(_x,_y)

print("Success 4!")
```

### Result #1
```
/home/bezigon/py35_tf_latest/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.
/home/bezigon/py35_tf_latest/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/bezigon/py35_tf_latest/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
2018-08-02 09:42:47.769393: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-02 09:42:47.858065: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:42:47.858693: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 10.48GiB
2018-08-02 09:42:48.023616: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:42:48.024334: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:05.0
totalMemory: 11.17GiB freeMemory: 10.97GiB
2018-08-02 09:42:48.103817: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:42:48.104508: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 2 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:06.0
totalMemory: 11.17GiB freeMemory: 10.97GiB
2018-08-02 09:42:48.184163: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:42:48.184776: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 3 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:07.0
totalMemory: 11.17GiB freeMemory: 10.97GiB
2018-08-02 09:42:48.185304: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
2018-08-02 09:42:49.265646: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-02 09:42:49.265697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 2 3 
2018-08-02 09:42:49.265707: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y Y Y 
2018-08-02 09:42:49.265711: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N Y Y 
2018-08-02 09:42:49.265716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   Y Y N Y 
2018-08-02 09:42:49.265720: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3:   Y Y Y N 
2018-08-02 09:42:49.266798: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10153 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-08-02 09:42:49.445735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10628 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: 0000:00:05.0, compute capability: 3.7)
2018-08-02 09:42:49.634548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10628 MB memory) -> physical GPU (device: 2, name: Tesla K80, pci bus id: 0000:00:06.0, compute capability: 3.7)
2018-08-02 09:42:49.821634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10635 MB memory) -> physical GPU (device: 3, name: Tesla K80, pci bus id: 0000:00:07.0, compute capability: 3.7)
Success!
Success 2!
Success 3!
Traceback (most recent call last):
  File "case1.py", line 43, in <module>
    m2.train_on_batch(_x,_y)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/engine/training.py", line 1215, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4,4,3] vs. [2,4,3]
	 [[Node: training_3/Adam/gradients/loss_3/simple_rnn_2_loss/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _class=["loc:@training_3/Adam/gradients/loss_3/simple_rnn_2_loss/sub_grad/Reshape"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training_3/Adam/gradients/loss_3/simple_rnn_2_loss/sub_grad/Shape/_317, training_3/Adam/gradients/loss_3/simple_rnn_2_loss/sub_grad/Shape_1)]]
	 [[Node: training_3/Adam/gradients/loss_3/simple_rnn_2_loss/sub_grad/Reshape/_343 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_697_training_3/Adam/gradients/loss_3/simple_rnn_2_loss/sub_grad/Reshape", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
### Reproducing code #2

Adapted code from https://github.com/keras-team/keras/blob/master/examples/lstm_seq2seq.py to use with `multi_gpu_model`.

### Result #2 
```
/home/bezigon/py35_tf_latest/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/bezigon/py35_tf_latest/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/bezigon/py35_tf_latest/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.
2018-08-02 09:53:04.114522: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-08-02 09:53:04.199896: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:53:04.200605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 10.48GiB
2018-08-02 09:53:04.276430: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:53:04.277099: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 1 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:05.0
totalMemory: 11.17GiB freeMemory: 10.97GiB
2018-08-02 09:53:04.356528: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:53:04.357302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 2 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:06.0
totalMemory: 11.17GiB freeMemory: 10.97GiB
2018-08-02 09:53:04.438287: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:897] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-02 09:53:04.439074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1392] Found device 3 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:07.0
totalMemory: 11.17GiB freeMemory: 10.97GiB
2018-08-02 09:53:04.439749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1471] Adding visible gpu devices: 0, 1, 2, 3
2018-08-02 09:53:05.586851: I tensorflow/core/common_runtime/gpu/gpu_device.cc:952] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-02 09:53:05.586911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:958]      0 1 2 3 
2018-08-02 09:53:05.586940: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   N Y Y Y 
2018-08-02 09:53:05.586958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y N Y Y 
2018-08-02 09:53:05.587003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 2:   Y Y N Y 
2018-08-02 09:53:05.587015: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 3:   Y Y Y N 
2018-08-02 09:53:05.588068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10153 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
2018-08-02 09:53:05.589282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10628 MB memory) -> physical GPU (device: 1, name: Tesla K80, pci bus id: 0000:00:05.0, compute capability: 3.7)
2018-08-02 09:53:05.590266: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 10628 MB memory) -> physical GPU (device: 2, name: Tesla K80, pci bus id: 0000:00:06.0, compute capability: 3.7)
2018-08-02 09:53:05.591197: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1084] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 10635 MB memory) -> physical GPU (device: 3, name: Tesla K80, pci bus id: 0000:00:07.0, compute capability: 3.7)
Number of samples: 10000
Number of unique input tokens: 71
Number of unique output tokens: 94
Max sequence length for inputs: 16
Max sequence length for outputs: 59
Train on 8000 samples, validate on 2000 samples
Epoch 1/100
Traceback (most recent call last):
  File "case2.py", line 163, in <module>
    validation_split=0.2)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/engine/training.py", line 1037, in fit
    validation_steps=validation_steps)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/engine/training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2666, in __call__
    return self._call(inputs)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2636, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1454, in __call__
    self._session._session, self._handle, args, status, None)
  File "/home/bezigon/py35_tf_latest/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [16,256] vs. [64,256]
	 [[Node: replica_2/model_1/lstm_2/while/add_6 = Add[T=DT_FLOAT, _class=["loc:@train.../Reshape_1"], _device="/job:localhost/replica:0/task:0/device:GPU:2"](replica_2/model_1/lstm_2/while/BiasAdd_3, replica_2/model_1/lstm_2/while/MatMul_7)]]
```

Solution?

**Comment by yanboliang** [comment] 2018-08-06 20:43
This has been fixed by #10845 .

**Comment by bezigon** [comment] 2018-08-07 11:30
Apparently, the problem is solved, thanks!

**Comment by bezigon** [comment] 2018-08-09 12:32
### Num of samples should be divisible by num_gpus * batch_size without the remainder

```
Train on 883 samples, validate on 56 samples
Epoch 1/100
768/883 [=========================>....] - ETA: 0s - loss: 3.2286 - acc: 0.3419

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-23-e3c29beb7d7c> in <module>()
     20 
     21 # Train the neural network
---> 22 parallel_model.fit([train_images, train_decoder_input], train_decoder_output, batch_size=32*num_gpus, epochs=100, validation_data=([valid_images, valid_decoder_input], valid_decoder_output))
     23 # parallel_model.fit([train_data, train_X], train_y, batch_size=32*num_gpus, epochs=10, validation_data=([valid_data, valid_X], valid_y))
     24 # parallel_model.fit_generator(data_generator(train_sequences, train_images, batch_size=batch_size), steps_per_epoch=steps_per_epoch, epochs=1)

~/py35_tf_latest/lib/python3.5/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
   1035                                         initial_epoch=initial_epoch,
   1036                                         steps_per_epoch=steps_per_epoch,
-> 1037                                         validation_steps=validation_steps)
   1038 
   1039     def evaluate(self, x=None, y=None,

~/py35_tf_latest/lib/python3.5/site-packages/keras/engine/training_arrays.py in fit_loop(model, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
    197                     ins_batch[i] = ins_batch[i].toarray()
    198 
--> 199                 outs = f(ins_batch)
    200                 outs = to_list(outs)
    201                 for l, o in zip(out_labels, outs):

~/py35_tf_latest/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
   2661                 return self._legacy_call(inputs)
   2662 
-> 2663             return self._call(inputs)
   2664         else:
   2665             if py_any(is_tensor(x) for x in inputs):

~/py35_tf_latest/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in _call(self, inputs)
   2631                                 symbol_vals,
   2632                                 session)
-> 2633         fetched = self._callable_fn(*array_vals)
   2634         return fetched[:len(self.outputs)]
   2635 

~/py35_tf_latest/lib/python3.5/site-packages/tensorflow/python/client/session.py in __call__(self, *args)
   1452         else:
   1453           return tf_session.TF_DeprecatedSessionRunCallable(
-> 1454               self._session._session, self._handle, args, status, None)
   1455 
   1456     def __del__(self):

~/py35_tf_latest/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    517             None, None,
    518             compat.as_text(c_api.TF_Message(self.status.status)),
--> 519             c_api.TF_GetCode(self.status.status))
    520     # Delete the underlying status object from memory otherwise it stays alive
    521     # as there is a reference to status from this from the traceback due to

InvalidArgumentError: Inputs to operation replica_3/model_1/lstm_2/Select_2 of type Select must have the same size and shape.  Input 0: [28,128] != input 1: [31,128]
	 [[Node: replica_3/model_1/lstm_2/Select_2 = Select[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/AddN_1267"], _device="/job:localhost/replica:0/task:0/device:GPU:3"](replica_3/model_1/lstm_2/Tile_2, replica_3/model_1/lstm_2/add_5, replica_3/model_1/lstm_1/add_397)]]
	 [[Node: replica_2/model_1/concatenate_1/All/_1549 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:2", send_device_incarnation=1, tensor_name="edge_62053_replica_2/model_1/concatenate_1/All", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```

**Comment by yanboliang** [comment] 2018-08-09 21:14
@bezigon I can't reproduce your reported issue on my machine with 2 GPUs. Can you share a minimum code snippet which can reproduce it? Then I can help to take a look. Thanks.

**Closed** 2021-06-24 22:31 UTC
