### ISSUE TITLE
Typo in keras/keras/ops/numpy.py file

### ISSUE THREAD

**Issue by timotheeMM** [keras-team/keras#19168] opened 2024-02-10 19:58 UTC
There is a typo in the keras/keras/ops/numpy.py file:
https://github.com/keras-team/keras/blob/f33c02c6e47e9291d127792b13412b9ac94ae7f6/keras/ops/numpy.py#L668
`lenght` sould be `length`

**Comment by timotheeMM** [comment] 2024-02-10 20:04
PR #19169

**Comment by sachinprasadhs** [comment] 2024-02-13 18:18
Could you please close the issue since the issue is fixed with the commit here https://github.com/keras-team/keras/pull/19169/commits/c8b2f03d49358bf9a84a0dee9fc4e5b2cf25f541

**Closed** 2024-02-14 12:27 UTC
Labels: stat:awaiting response from contributor
