### ISSUE TITLE
possible bug? tf.math.tanh to replace tf.tanh 

### ISSUE THREAD

**Issue by Vadori** [keras-team/keras#19218] opened 2024-02-23 01:47 UTC
Hi,

I am getting the following error with TensorFlow 2.11 and 2.12.

Traceback (most recent call last):
  File "/users/vadoriv/ncis/main.py", line 49, in <module>
    hist = ncismodel.train(epochs = 2, n_batches_epoch = 10)
  File "/users/vadoriv/ncis/cisc.py", line 186, in train
    history = self.keras_model.fit(
  File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 52, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnimplementedError: Graph execution error:

Detected at node 'model_2/activation_66/Tanh' defined at (most recent call last):
    File "/users/vadoriv/ncis/main.py", line 49, in <module>
      hist = ncismodel.train(epochs = 2, n_batches_epoch = 10)
    File "/users/vadoriv/ncis/cisc.py", line 186, in train
      history = self.keras_model.fit(
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 1694, in fit
      val_logs = self.evaluate(
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 2040, in evaluate
      tmp_logs = self.test_function(iterator)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 1820, in test_function
      return step_function(self, iterator)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 1804, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 1792, in run_step
      outputs = model.test_step(data)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 1756, in test_step
      y_pred = self(x, training=False)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/training.py", line 561, in __call__
      return super().__call__(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1132, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/functional.py", line 511, in call
      return self._run_internal_graph(inputs, training=training, mask=mask)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/functional.py", line 668, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 65, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/engine/base_layer.py", line 1132, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 96, in error_handler
      return fn(*args, **kwargs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/layers/core/activation.py", line 59, in call
      return self.activation(inputs)
    File "/users/vadoriv/.conda/envs/ncis_env/lib/python3.9/site-packages/keras/activations.py", line 381, in tanh
      return tf.tanh(x)
Node: 'model_2/activation_66/Tanh'
Fusion is not implemented: [FusedBatchNorm,Tanh]
	 [[{{node model_2/activation_66/Tanh}}]] [Op:__inference_test_function_128272]
2024-02-23 01:14:51.986105: W tensorflow/core/kernels/data/generator_dataset_op.cc:108] Error occurred when finalizing GeneratorDataset iterator: FAILED_PRECONDITION: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]

Is it possible that the cause is 

return tf.tanh(x) 

which should be 

return tf.math.tanh(x)

in keras/activations.py

**Comment by SuryanarayanaY** [comment] 2024-02-23 04:32
Hi @Vadori ,

Since you are using TF2.11 which is quite older and currently Keras3 supports multi backend.Could you please try with latest version of TF and install keras3 using `pip install keras -U` which will install latest keras package.Please refer [README](https://github.com/keras-team/keras/blob/master/README.md) for more details.

With these can you try again and let us know if same problem persists along with reproducible code snippet.

BTW, `tf.math.tanh` is alias of `tf.tanh` and both will call same API only. 

Thanks!

**Comment by Vadori** [comment] 2024-02-23 19:20
Hi, @SuryanarayanaY,

Thanks for your prompt response. I am trying to run a network training on a server with NVIDIA-SMI 515.105.01 Driver Version: 515.105.01 CUDA Version: 11.7, and unfortunately, I am quite limited on the version of tensorflow I can install in my conda env. I read that the only compatible versions are 2.8 and 2.9.1. I am actually trying to downgrade from 2.11, rather than updagrading. Do you have any other suggestions, given my constraints? I am using tensorflow keras.

**Comment by SuryanarayanaY** [comment] 2024-02-27 04:32
Hi @Vadori ,
Could you please submit reproducble code snippet with Tf2.8 or Tf2.9 version to check the issue?

**Comment by Vadori** [comment] 2024-02-27 12:10
Hi @SuryanarayanaY,

I managed to solve the issue I had, thanks! :) I managed to make the model run on single node equipped with GPU. Now the next step would be to run the keras model across multiple nodes with tf.distribute.MultiWorkerMirroredStrategy. I checked the documentation but the only tutorial provided by tensorflow/keras is kind of a toy example. No tutorial is provided to run the model on an actual HPC cluster where jobs are submitted via slurm scripts. I have so far made lots of unsuccessful attempts and I think I can’t solve by myself. Do you know where I can find such instructions/tutorial. It would really help!! Thanks! Please let me know if this is not the right place to ask.

**Comment by SuryanarayanaY** [comment] 2024-02-28 16:17
Hi @Vadori ,

Since you are not using Keras3 and the issue is with distribution strategy you can ask the question in Tensorflow repo.I hope you have already checked the resources form TF docs here [1](https://www.tensorflow.org/guide/distributed_training#multiworkermirroredstrategy) ,[2](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) & [3](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_ctl).

Please feel free to close the issue here and raise a request in TF repo, if you couldn't find the attached resources useful.

**Comment by Vadori** [comment] 2024-02-28 16:23
Thanks to @SuryanarayanaY for the prompt answers. The issues I had has been solved.

**Closed** 2024-02-28 16:22 UTC
Labels: type:support
