### ISSUE TITLE
Generating End of Sequence Token for ConvLSTM

### ISSUE THREAD

**Issue by wangwalton** [keras-team/keras#10782] opened 2018-07-26 13:15 UTC
I'm working on a polygon prediction project. The output of the ConvLSTM is a 2D one-hot encoding of where the pixel of interest is. I'm interested in adding one extra dimension into this output to mark an end-of-sequence response, any idea how?

**Comment by chriskoups** [comment] 2018-07-27 08:31
Here is not a place for help and this is not a bug or feature.
Please do not post here this type of questions but use stackoverflow.
Please close the issue by pressing the button under the reply/comment box

**Closed** 2018-07-27 18:00 UTC
