### ISSUE TITLE
Tensorboard callback embeddings sample with MNIST fails

### ISSUE THREAD

**Issue by phisad** [keras-team/keras#12808] opened 2019-05-09 16:28 UTC
**System information**  
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  1.13.1
- Keras version:  2.2.4-tf
- Python version:  3.6
- CUDA/cuDNN version:  9.0
- GPU model and memory:  GeForce 1060 

**Describe the current behavior**  

There is an MNIST sample how to use embeddings with the Tensorboad callback at https://keras.io/examples/tensorboard_embeddings_mnist

But when I run the code an error message is thrown:

```
Caused by op 'strided_slice/_assign', defined at:
  File "C:\Users\Philipp\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\runfiles.py", line 273, in <module>
    main()
  File "C:\Users\Philipp\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\runfiles.py", line 97, in main
    return pydev_runfiles.main(configuration)  # Note: still doesn't return a proper value.
  File "C:\Users\Philipp\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_runfiles\pydev_runfiles.py", line 874, in main
    PydevTestRunner(configuration).run_tests()
  File "C:\Users\Philipp\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_runfiles\pydev_runfiles.py", line 803, in run_tests
    run_tests()
  File "C:\Users\Philipp\.p2\pool\plugins\org.python.pydev.core_7.1.0.201902031515\pysrc\_pydev_runfiles\pydev_runfiles.py", line 798, in run_tests
    runner.run(test_suite)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\runner.py", line 176, in run
    test(result)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\suite.py", line 122, in run
    test(result)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\case.py", line 653, in __call__
    return self.run(*args, **kwds)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\unittest\case.py", line 605, in run
    testMethod()
  File "F:\Development\git\thesis-captioning\tests\test_embedding_callback.py", line 179, in mnist
    validation_data=(x_test, y_test))
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 215, in model_iteration
    mode=mode)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\callbacks.py", line 106, in configure_callbacks
    callback_list.set_model(callback_model)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\callbacks.py", line 178, in set_model
    callback.set_model(model)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1051, in set_model
    embedding_input)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\ops\state_ops.py", line 224, in assign
    return ref.assign(value, name=name)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\ops\array_ops.py", line 844, in assign
    shrink_axis_mask=shrink_axis_mask)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1163, in _strided_slice_assign
    shrink_axis_mask=shrink_axis_mask))
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7288, in resource_strided_slice_assign
    name=name)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\framework\ops.py", line 1801, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Resource localhost/features/embeddings/class tensorflow::Var does not exist.
	 [[node strided_slice/_assign (defined at F:\Development\git\thesis-captioning\tests\test_embedding_callback.py:179) ]]
	 [[node ReadVariableOp_1 (defined at F:\Development\git\thesis-captioning\tests\test_embedding_callback.py:179) ]]
```

The error message looks for me, as when the node is not correctly added to the graph.

**Describe the expected behavior**  

I expect that the sample runs without a problem and then shows me the correct projection in Tensorboad.

**Code to reproduce the issue**  
See sample at https://keras.io/examples/tensorboard_embeddings_mnist

**Other info / logs**  
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment] 2019-05-09 18:53
@phisad I don't see any issue when I ran your code in Google colab with the same env as you mentioned. Please take a look at the [GitHub gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/e00b7b9f6eeb785a147e25b636f33900/untitled145.ipynb) and try to run it on your system and check whether there is any error. Thanks!

**Comment by phisad** [comment] 2019-05-10 06:54
> @phisad I don't see any issue when I ran your code in Google colab with the same env as you mentioned. Please take a look at the [GitHub gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/164248b567552f47a8836dac6008b4c0/untitled145.ipynb) and try to run it on your system and check whether there is any error. Thanks!

Thanks for the reply. From the gist I run locally in the error already mentioned in [1666](https://github.com/tensorflow/tensorboard/issues/1666) Do you have used a different tensorflow backend version?

```
  File "test_mnist.py", line 82, in <module>
    validation_data=(x_test, y_test))
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\engine\training.py", line 880, in fit
    validation_steps=validation_steps)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 370, in model_iteration
    callbacks.on_epoch_end(epoch, epoch_logs, mode=mode)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\callbacks.py", line 251, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Development\apps\Anaconda3\envs\tf113\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1203, in on_epoch_end
    self.sess.run(self.assign_embeddings, feed_dict=feed_dict)
AttributeError: 'TensorBoard' object has no attribute 'sess'
```

When I apply the fix from https://github.com/tensorflow/tensorflow/commit/d994300bde00c7dee8bacccdbc5d67c3f3f2b322 I still get the error: 

```
NotFoundError (see above for traceback): Resource localhost/features_embeddings/class tensorflow::Var does not exist.
	 [[node strided_slice/_assign (defined at test_mnist.py:82) ]]
	 [[node ReadVariableOp_1 (defined at test_mnist.py:82) ]]
```

**Comment by jvishnuvardhan** [comment] 2019-05-10 12:56
@phisad Did you ran my gist in Google Colab? or ran it in your local Anaconda (Spyder?). Similar to you, I had used TF1.13.1. Could you create a gist and send it to me here. thanks!

**Comment by phisad** [comment] 2019-05-13 18:13
OK, the important thing seems to be to replace the imports to
```
import tensorflow
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
import tensorflow.keras.backend as K
```
Then I can also reproduce the missing session problem here: https://colab.research.google.com/gist/phisad/cfcf613d8bdf9408863376a2d298315d/keras-issue-12808.ipynb

When I replace `TensorBoard` with `TensorBoardWithSession` then I get the error.

```
NotFoundError: Resource localhost/features_embedding_2/N10tensorflow3VarE does not exist.
	 [[{{node strided_slice_2/_assign}}]]
```

as here https://colab.research.google.com/gist/phisad/f9299171beba72f4e50d903548d37721/keras-issue-12808-2.ipynb

**Comment by jvishnuvardhan** [comment] 2019-05-13 23:17
@phisad My question was "Did you ran my gist in Google Colab?" was there any issue when you ran my gist? I will take a look at your gists but it will take some time. Thanks!

**Comment by phisad** [comment] 2019-05-15 07:08
> @phisad My question was "Did you ran my gist in Google Colab?" was there any issue when you ran my gist? I will take a look at your gists but it will take some time. Thanks!

Yes, I cannot run it, because I cannot import keras as I only have installed tensorflow-gpu using conda.

**Comment by jvishnuvardhan** [comment] 2019-05-15 12:06
@phisad The purpose of asking you to run my gist was to know whether the issue was due to local installation or your code. When you run my gist, it will not use your local installation. GitHub gist imports modules in the browser and runs TF code. 

Just open gist, on top there will be "run" or "run all" drop down, select one of that. Then, a window pops up, on that window just click on "Run Anyway".  Please let me know how it progresses. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-21 05:15
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-21 05:15 UTC
Labels: backend:tensorflow, stat:awaiting response, type:support

**Comment by Nithanaroy** [comment] 2019-09-19 06:01
@phisad did you resolve the issue?

I see the same error with `tf.keras` with tensorflow-gpu version of 1.14. However I am running my own code and the above dataset.

**Comment by KristianHolsheimer** [comment] 2019-10-11 04:33
@jvishnuvardhan I can confirm that this bug is still there. I'm on tensorflow version **1.14.0**.

I ran your gist in colab twice:
1. pure keras (works fine)
2. tf.keras (breaks)

So, to reproduce this bug, just replace `keras` by `tf.keras` in your [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/164248b567552f47a8836dac6008b4c0/untitled145.ipynb), i.e. replace:
```python
import keras
from keras.callbacks import TensorBoard
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
```
by:
```python
from tensorflow import keras
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras import backend as K
```

Would you be able to have a look at this?
