### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by slavenandjelic** [keras-team/keras#13146] opened 2019-07-24 14:45 UTC
`AttributeError: module 'tensorflow' has no attribute 'get_default_graph'`

I am working through an example of building a simple CNN with tensorflow/keras to classify dogs/cat pictures. I keep getting the above traceback message when executing following line of code (the first layer of my network):
`Conv2D(32, (3, 3), activation='relu', input_shape=(224,224,3))`

Writing `tensorflow.keras` instead of `keras` doesn't make a difference, neither does importing any of the other modules etc as suggested in previous threads for similar issues. 

I'm running this all on my macbook on IDLE (for various reasons) - could this problem have something to do with the version of tensorflow I have installed? i.e not `tensorflow-GPU==2.0.0-beta1`

**System information**   
- Mac OSX  
- TensorFlow backend
- TensorFlow version:  2.0.0
- Keras version:  2.2.4
- Python version:  3.6.8
- CUDA/cuDNN version:  n/a

<img width="941" alt="Screen Shot 2019-07-24 at 15 43 43" src="https://user-images.githubusercontent.com/44614292/61803434-04914700-ae2a-11e9-85a9-ee6ad8254be6.png">
<img width="666" alt="Screen Shot 2019-07-24 at 15 44 11" src="https://user-images.githubusercontent.com/44614292/61803435-04914700-ae2a-11e9-826d-dce6d3eb3270.png">

**Comment by gowtham-kp** [comment] 2019-07-24 15:24
Duplicate of the issue #12379 .Please go through the issue and let me know if it helps. Thanks!

**Comment by slavenandjelic** [comment] 2019-07-24 16:01
> Duplicate of the issue #12379 .Please go through the issue and let me know if it helps. Thanks!

nope, unfortunately not.

**Comment by gowtham-kp** [comment] 2019-07-24 18:55
@slavenandjelic 
**Please replace**
`from keras import backend`
with:
`from tensorflow.keras import backend`
in your script and let me know if this solves the issue. Thanks!

**Comment by slavenandjelic** [comment] 2019-07-24 19:01
As mentioned in the original post, writing tensorflow.keras instead of keras (wherever in the code) doesnt help

**Comment by gowtham-kp** [comment] 2019-07-24 20:48
@slavenandjelic Please share a gist of your code or colab link so that I can work solving this issue. Thanks!

**Comment by slavenandjelic** [comment] 2019-07-25 08:31
https://gist.github.com/slavenandjelic/f880d36ad2c00a55b094f8688119df7b#file-gistfile1-txt

**Comment by leochan2009** [comment] 2019-10-28 21:17
i have the same issue on my mac os

**Comment by shahdev** [comment] 2019-11-01 19:11
Were you able to solve it @slavenandjelic ? I am getting the same error

**Comment by slavenandjelic** [comment] 2019-11-01 19:28
solved this by downgrading tensorflow. Tensorflow 2 is still in beta(?) so didn't sit too well with keras. Try using tensorflow as opposed to tensorflow 2

**Closed** 2019-11-01 19:28 UTC
Labels: backend:tensorflow, type:support

**Comment by jhughs** [comment] 2019-11-07 15:23
Keras integrated into TensorFlow 2.0
The article below cleared this up for me.  Key points are:
1.	Keras is included in the TensorFlow 2.0 package
2.	So no need to install the stand-alone Keras package in your environment
3.	And now the fore-mentioned solutions of using "from tensorflow.keras…" make sense.

After recognizing that and making the change, my code samples work with some minor changes here and there.
https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/
