### ISSUE TITLE
`tf.keras.layers.Convolution3DTranspose` crashes with zero-size input

### ISSUE THREAD

**Issue by VictoriaGriffith** [keras-team/keras#16953] opened 2022-08-28 19:46 UTC
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): TF2.9.1
- Python version: 3.9
- Bazel version (if compiling from source):
- GPU model and memory:

**Describe the problem**.
`tf.keras.layers.Convolution3DTranspose` crashes with zero-size input

**Describe the current behavior**.
The session crashes.

**Describe the expected behavior**.
If such input is not support, should do proper input checking to avoid direct session crash.

**Standalone code to reproduce the issue**.
```
import tensorflow as tf
filters = 3
kernel_size = [3, 3, 3]
strides = [1, 1, 1]
padding = "valid"
output_padding = None
data_format = "channels_last"
dilation_rate = [1, 1, 1,]
activation = "linear"

x = tf.random.uniform([3, 2, 2, 2, 0], minval=1.1, maxval=10, dtype=tf.float32)

Convolution3DTranspose_class = tf.keras.layers.Convolution3DTranspose(filters, kernel_size, data_format=data_format, activation=activation,)
r = Convolution3DTranspose_class(x)
```

**Output**.
crashes.

**Comment by tilakrayal** [comment] 2022-08-30 10:10
@gadagashwini,
I was able to reproduce the issue in tensorflow-gpu v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/843d58d72c5af9d11d7bdbd0f9efc6eb/untitled547.ipynb).

**Comment by hertschuh** [comment] 2022-09-01 18:09
@VictoriaGriffith ,

This is a duplicate of #16933 please follow this issue instead.

Thanks!

**Closed by hertschuh** 2022-09-01 18:09 UTC
Labels: type:bug/performance, keras-team-review-pending
