### ISSUE TITLE
model.load_weights() exception: The Session graph is empty. Add operations to the graph before calling run().

### ISSUE THREAD

**Issue by tjliupeng** [keras-team/keras#12906] opened 2019-06-01 05:54 UTC
My code works fine with Keras 2.0.6 and Tensorflow-gpu 1.3.0. When I reinstall my computer and my code throw exceptions from the model.load_weights() call with Keras 2.2.4 and Tensorflow-gpu 1.12.2.  The error message is: 
**RuntimeError: The Session graph is empty. Add operations to the graph before calling run().**
I google this error and find that there was some similar questions before. It seems relate to the Keras and Tensorflow version. 

What is the better solution?

Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-06 17:45
Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-21 23:06
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-21 23:06 UTC
Labels: backend:tensorflow, stat:awaiting response, type:support
