### ISSUE TITLE
Prediction always the same, no matter which input

### ISSUE THREAD

**Issue by Tropaion** [keras-team/keras#16178] opened 2022-03-05 13:16 UTC
Hello,

I'm new to Keras and are currently learning it because I need it for a university project.
Currently I'm trying this example: https://keras.io/examples/vision/image_classification_from_scratch/

At first a had a problem with filtering corrupted images: https://discuss.tensorflow.org/t/first-steps-in-keras-error/8049
But after changing the code, training the model worked.

Now I tried predicting a few images, the it always shows the same percentage:
[CreatingModel.pdf](https://github.com/keras-team/keras/files/8190713/CreatingModel.pdf)
[RunningModel.pdf](https://github.com/keras-team/keras/files/8190714/RunningModel.pdf)

Thanks for your help.

**Comment by chunduriv** [comment] 2022-03-08 08:13
@Tropaion,

Please can you refresh your kernel and try with other images. It will resolve your issue.

I tried to run your code on Colab using `TF v2.8` and everything is working as expected. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/022b9d4264c5383bcec555947230ab10/16178.ipynb) for reference.Thanks!

**Comment by Tropaion** [comment] 2022-03-08 08:21
@Tropaion Maybe there is a problem with my setup? https://wiki.flowerhouse.at/index.php/Jupyter
I use Jupyter with Keras. But sadly I don't have much hardware ressources and it takes ~42h.

**Comment by chunduriv** [comment] 2022-03-08 09:41
@Tropaion,
>  I don't have much hardware resources and it takes ~42h.

You can use `Google Colab` for your learning, where you can access to `GPU` for free of charge. For more details please refer [here](https://colab.research.google.com/#scrollTo=5fCEDCU_qrC0).

I am successfully able to delete corrupted files using the same code mentioned in tutorial. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/022b9d4264c5383bcec555947230ab10/16178.ipynb#scrollTo=yDOomNdF57hF) for reference. Thanks!

**Comment by Tropaion** [comment] 2022-03-08 11:07
@chunduriv I need to use my system because of a university project... which python version did you use?
I use Debian11 with Python 3.9.2 and this version:
```
(Keras) root@Jupyter:/home/venv# python3 -m pip show tensorflow
Name: tensorflow
Version: 2.8.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/venv/Keras/lib/python3.9/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, keras-preprocessing, libclang, numpy, opt-einsum, protobuf, setuptools, six, tensorboard, tensorflow-io-gcs-filesystem, termcolor, tf-estimator-nightly, typing-extensions, wrapt
```

**Comment by chunduriv** [comment] 2022-03-08 12:26
@Tropaion,
> which python version did you use?

Python Version: `3.7.12.`  

If you are still facing same error, a workaround here is first uninstall Tensorflow and create new virtual environment for fresh Tensorflow installation. Thanks!

**Comment by Tropaion** [comment] 2022-03-08 12:29
@chunduriv I tried it with an completely new setup two hours ago, sadly it didn't change anything:
```
#Install venv
apt install python3-venv

#Get to folder where environment should be
mkdir /home/venv
cd /home/venv

#Create Keras-Environment
python3 -m venv Keras

#Activate environment
source Keras/bin/activate

#Deactivate with:
deactivate

#Add Environment to Jupyter Notebook
#Activate environment
source Keras/bin/activate

#Install iPython Kernel
pip install ipykernel

#Add virtual environment to jupyter
python -m ipykernel install --name=Keras

#Install Keras in Environment
#Activate environment
source Keras/bin/activate

#Install tensorflow
pip install tensorflow

#Verify tensorflow installation
python3 -m pip show tensorflow

#Update tensorflow with
pip install --upgrade tensorflow
pip install --upgrade keras
```

**Comment by chunduriv** [comment] 2022-03-11 15:43
@Tropaion,

Can you please share outcome of this code snippet ?

```
image_size = (180, 180)
batch_size = 32

train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    validation_split=0.2,
    subset="training",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    "PetImages",
    validation_split=0.2,
    subset="validation",
    seed=1337,
    image_size=image_size,
    batch_size=batch_size,
)
```

**Comment by Tropaion** [comment] 2022-03-11 18:26
@chunduriv Thanks for your help.
This is the output:
```
Found 23440 files belonging to 2 classes.
Using 18752 files for training.
2022-03-11 18:25:42.835276: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-03-11 18:25:42.835688: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-03-11 18:25:42.835744: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (Jupyter): /proc/driver/nvidia/version does not exist
Found 23440 files belonging to 2 classes.
Using 4688 files for validation.
```

**Comment by Tropaion** [comment] 2022-03-11 18:57
@chunduriv I also installed Keras on my Windows11 computer now and it is the same result, so I don't think there is a problem with my setup:
```
Python 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=========== RESTART: C:\Users\Fabian\Desktop\CatsVSDogs\CatsVSDogs.py ==========
Deleted 1578 images
Found 23422 files belonging to 2 classes.
Using 18738 files for training.
Found 23422 files belonging to 2 classes.
Using 4684 files for validation.
>>> 
```

**Comment by gowthamkpr** [comment] 2022-04-20 21:11
@Tropaion Looked at your code. Your model is running fine. The issue is that you are predicting on cat image in the first instance and printing horse, and in the second instance again you are predicting on cat image and printing dog image. I have highlighted it in two colors. Make sure you feed in the same image that you are visualizing.
[RunningModel.pdf](https://github.com/keras-team/keras/files/8525450/RunningModel.pdf)

This should fix your issue.

**Comment by Tropaion** [comment] 2022-04-20 21:43
@gowthamkpr Thanks for looking into it. True, this is also an mistake, but it wasn't this what made the problem.

> At first a had a problem with filtering corrupted images: https://discuss.tensorflow.org/t/first-steps-in-keras-error/8049
> But after changing the code, training the model worked.

The problem was this. It is weird, I tried it in Google Colab and there it works, but in my Jupyter installation it doesn't.
I even tried installing the exactly same Python, TF and Keras versions in my system but still didn't work.

A few days ago I found a workaround.
I downloaded this program https://github.com/coderslagoon/BadPeggy on my Windows PC, did the filtering with it and copied the files to my Jupyter server.
Surprisingly with this filtering program, training the model didn't even throw one error and the prediction worked perfectly.

But I still haven't found out why it didn't work with the code in the tutorial.

**Comment by gowthamkpr** [comment] 2022-04-21 01:51
Can you share a copy of your code with outputs. Thanks!!!

**Comment by Tropaion** [comment] 2022-04-21 11:15
> CreatingModel.pdf

It's this one, I never changed it.

And this is the working one:
[CreatingModel.pdf](https://github.com/keras-team/keras/files/8530466/CreatingModel.pdf)

**Comment by gowthamkpr** [comment] 2022-04-21 16:25
SInce your model is working, can you go ahead and close the issue. Thanks!

**Closed** 2022-04-21 19:15 UTC
Labels: type:support, stat:awaiting response
