### ISSUE TITLE
Link to release announcement broken

### ISSUE THREAD

**Issue by timoklein** [keras-team/keras#18841] opened 2023-11-28 07:51 UTC
When trying to access the site https://keras.io/keras_3/ from https://github.com/keras-team/keras/releases/tag/v3.0.0, it doesn't exist.  
Should this instead link to https://keras.io/keras_core/announcement/?

**Comment by aliencaocao** [comment] 2023-11-28 08:35
https://keras.io/guides/migrating_to_keras_3/
this one also broken

**Comment by aliencaocao** [comment] 2023-11-28 23:53
Works for me, thanks

**Comment by timoklein** [comment] 2023-11-29 06:17
Looks good to me

**Comment by sachinprasadhs** [comment] 2023-11-29 18:22
Closing the issue since the issue is resolved. Thanks for confirming.

**Closed by sachinprasadhs** 2023-11-29 18:22 UTC
Labels: type:Bug
