### ISSUE TITLE
EinsumDense layer ignores global_dtype_policy when imported in a certain way

### ISSUE THREAD

**Issue by gcuder** [keras-team/keras#15806] opened 2021-12-17 08:50 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 11.5.1
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): `2.6.2`
- Python version: `3.8`

**Describe the current behavior**

I tried using the `EinsumDense` layer in a `mixed_float16` training and it seems like that the way you import this layer is very crucial, as it tends to ignore the `dtype_policy` when I import it with `from tensorflow.python.keras.layers.einsum_dense import EinsumDense`.

**Describe the expected behavior**
All layers should use the `global_dtype_policy`, regardless of the way they are imported.

**Standalone code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.keras import mixed_precision
from tensorflow.keras.layers.experimental import EinsumDense as EinsumDense1
from tensorflow.python.keras.layers.einsum_dense import EinsumDense as EinsumDense2
from keras.layers.einsum_dense import EinsumDense as EinsumDense3

policy = mixed_precision.Policy("mixed_float16")
mixed_precision.set_global_policy(policy)

layer1 = EinsumDense1("abc,cd->abd",
                      output_shape=(None, 64),
                      bias_axes="d")

layer2 = EinsumDense2("abc,cd->abd",
                      output_shape=(None, 64),
                      bias_axes="d")

layer3 = EinsumDense3("abc,cd->abd",
                      output_shape=(None, 64),
                      bias_axes="d")

layer4 = tf.keras.layers.experimental.EinsumDense("abc,cd->abd",
                      output_shape=(None, 64),
                      bias_axes="d")

input_tensor = tf.keras.Input(shape=[32, 128])

print('from tensorflow.keras.layers.experimental import EinsumDense')
print(layer1(input_tensor))
print(layer1.dtype_policy) # float16
print('------------------------------------------------------------')

print('from tensorflow.python.keras.layers.einsum_dense import EinsumDense')
print(layer2(input_tensor))
print(layer2.dtype_policy) # float32

print('------------------------------------------------------------')

print('from keras.layers.einsum_dense import EinsumDense')
print(layer3(input_tensor))
print(layer3.dtype_policy) # float16
print('------------------------------------------------------------')

print('from keras.layers.einsum_dense import EinsumDense')
print(layer4(input_tensor))
print(layer4.dtype_policy) # float16
```

**Comment by sushreebarsa** [comment] 2021-12-22 11:40
@gcuder I tried to replicate the issue on colab using TF v2.7.0,could you please have a look on the [gist](https://colab.research.google.com/gist/sushreebarsa/1367b5d9710bf242074ee649fe8a5fc1/15806.ipynb#scrollTo=pH3K0btc7OB6) and confirm the same?Thanks!

**Comment by gcuder** [comment] 2021-12-22 12:05
@sushreebarsa Thank you. Yes, the issue persists using tensorflow `2.7.0`

**Comment by rchao** [comment] 2021-12-23 18:10
`tensorflow.python.keras` is now deprecated and will be removed at any point, so please avoid using this. Also, please avoid directly importing python modules: always use `tf.keras.*`.

**Comment by rchao** [comment] 2021-12-23 18:11
It appears to be working as intended so closing.

**Closed by rchao** 2021-12-23 18:11 UTC
Labels: type:bug/performance
