### ISSUE TITLE
ValueError: Error when checking target: expected dense_2 to have shape (5,) but got array with shape (1,)

### ISSUE THREAD

**Issue by CajetanRodrigues** [keras-team/keras#13107] opened 2019-07-14 12:27 UTC
**I am training a keras model for multi label image classification , 5 classes namely flood, wildfire, storm, tornado, earthquake**

_But I am getting this error =>_

> ValueError: Error when checking target: expected dense_2 to have shape (5,) but got array with shape_ (1,)

`# # Importing the Keras libraries and packages
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense
import numpy as np
from keras.preprocessing import image
from keras.preprocessing.image import ImageDataGenerator
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
def create_model() :
    # Initialising the CNN
    classifier = Sequential()
    # Step 1 - Convolution
    classifier.add(Conv2D(32, (3, 3), input_shape = (64, 64, 3), activation = 'relu'))
    # Step 2 - Pooling
    classifier.add(MaxPooling2D(pool_size = (2, 2)))
    # Adding a second convolutional layer
    classifier.add(Conv2D(32, (3, 3), activation = 'relu'))
    classifier.add(MaxPooling2D(pool_size = (2, 2)))
    # Step 3 - Flattening
    classifier.add(Flatten())
    # Step 4 - Full connection
    classifier.add(Dense(units = 128, activation = 'relu'))
    classifier.add(Dense(units = 5, activation = 'softmax'))
    return classifier

def train_save_model():
    classifier = create_model()
    classifier.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    train_datagen = ImageDataGenerator(rescale = 1./255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True)
    test_datagen = ImageDataGenerator(rescale = 1./255)
    training_set = train_datagen.flow_from_directory('training_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary')
    test_set = test_datagen.flow_from_directory('validation_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary')
    classifier.fit_generator(training_set,
    steps_per_epoch = 2021,
    epochs = 5,
    validation_data = test_set,
    validation_steps = 2021)
    classifier.save_weights("model.h5")

def test_model():
    classifier = create_model()
    classifier.load_weights("model.h5")
    test_image = image.load_img('validation_set/tornado/110.jpg', target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    # print(test_image)
    result = classifier.predict(test_image)
    train_datagen = ImageDataGenerator(rescale = 1./255,
    shear_range = 0.2,
    zoom_range = 0.2,
    horizontal_flip = True,
    )
    training_set = train_datagen.flow_from_directory('training_set',
    target_size = (64, 64),
    batch_size = 32,
    class_mode = 'binary')
    training_set.class_indices
    # print(training_set.class_indices)
    print(result)

train_save_model()
test_model()
`

**Comment by jvishnuvardhan** [comment] 2019-07-16 00:33
Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-23 04:53
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-07-23 04:53 UTC
Labels: stat:awaiting response, type:support
