### ISSUE TITLE
Validation_generator not validating all samples inside its validation list

### ISSUE THREAD

**Issue by rvallari1** [keras-team/keras#13079] opened 2019-07-07 20:12 UTC
**System information**  
- Have I written custom code (as opposed to using example directory):  
- OS Platform and Distribution:  Linux Ubuntu    
- TensorFlow backend (yes / no):  yep
- TensorFlow version:  1.13.1
- Keras version:  2.2.4
- Python version:  
- CUDA/cuDNN version:  no
- GPU model and memory:   

**Describe the current behavior**  
If we run model.fit_generator, evaluate_generator is called after every epoch..
So, If we are running a model on n cpus', where training and validation data is divided as per https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly . What is happening, since the validation data is 80 in size, evaluate_generator is running 80/n steps but each cpu is validating only its [80/n] samples [I am taking one sample per step]. 

So, if the validation list is 80; and I have 4 cpus' running ; each cpu is validating only 20 samples in its list in this order[1 2 3... 20]. Unlike training_generator, where this problem doesnot exist. Random index is thrown to __getitem__(index): to retreive the sample. 
  

 

**Other info / logs**  
<img width="767" alt="djsnjnxj" src="https://user-images.githubusercontent.com/32358727/60773366-fcdf5c00-a121-11e9-96c1-184fc395a431.PNG">

where 1 is the index thrown to __getitem__ and [ __ ] is the sample number.

**Comment by jvishnuvardhan** [comment] 2019-07-08 23:00
@rvallari1 Can you provide a standalone code to reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-07-15 22:17
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-07-15 22:17 UTC
Labels: backend:tensorflow, stat:awaiting response
