### ISSUE TITLE
import error with keras 2.1.1. While i,porting, somehow trying to use theano as backend and throwing the following error

### ISSUE THREAD

**Issue by shravankumar147** [keras-team/keras#8580] opened 2017-11-24 18:41 UTC
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>()
     74         if version != getattr(lazylinker_ext, '_version', None):
---> 75             raise ImportError()
     76 except ImportError:

ImportError: 

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>()
     91             if version != getattr(lazylinker_ext, '_version', None):
---> 92                 raise ImportError()
     93         except ImportError:

ImportError: 

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\vm.py in <module>()
    672         raise theano.gof.cmodule.MissingGXX('lazylinker will not be imported if theano.config.cxx is not set.')
--> 673     from . import lazylinker_c
    674 

C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\lazylinker_c.py in <module>()
    126             cmodule.GCC_compiler.compile_str(dirname, code, location=loc,
--> 127                                              preargs=args)
    128             # Save version into the __init__.py file.

C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\cmodule.py in compile_str(module_name, src_code, location, include_dirs, lib_dirs, libs, preargs, py_module, hide_symbols)
   2355             raise Exception('Compilation failed (return status=%s): %s' %
-> 2356                             (status, compile_stderr.replace('\n', '. ')))
   2357         elif config.cmodule.compilation_warning and compile_stderr:

. collect2.exe: error: ld returned 1 exit statuscompiledir_Windows-10-10.0.15063-SP0-Intel64_Family_6_Model_58_Stepping_9_GenuineIntel-3.6.3-64/lazylinker_ext/mod.cpp:976: undefined reference to `__imp__Py_TrueStruct'Error'e undefined references to `__imp__Py_NoneStruct' followow

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-4-c74e2bd4ca71> in <module>()
----> 1 import keras

C:\ProgramData\Anaconda3\lib\site-packages\keras\__init__.py in <module>()
      1 from __future__ import absolute_import
      2 
----> 3 from . import utils
      4 from . import activations
      5 from . import applications

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\__init__.py in <module>()
      4 from . import data_utils
      5 from . import io_utils
----> 6 from . import conv_utils
      7 
      8 # Globally-importable utils.

C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\conv_utils.py in <module>()
      1 from six.moves import range
      2 import numpy as np
----> 3 from .. import backend as K
      4 
      5 

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\__init__.py in <module>()
     78 elif _BACKEND == 'theano':
     79     sys.stderr.write('Using Theano backend.\n')
---> 80     from .theano_backend import *
     81 elif _BACKEND == 'tensorflow':
     82     sys.stderr.write('Using TensorFlow backend.\n')

C:\ProgramData\Anaconda3\lib\site-packages\keras\backend\theano_backend.py in <module>()
      1 from collections import defaultdict
      2 from contextlib import contextmanager
----> 3 import theano
      4 from theano import tensor as T
      5 from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams

C:\ProgramData\Anaconda3\lib\site-packages\theano\__init__.py in <module>()
    108     object2, utils)
    109 
--> 110 from theano.compile import (
    111     SymbolicInput, In,
    112     SymbolicOutput, Out,

C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\__init__.py in <module>()
     10 from theano.compile.function_module import *
     11 
---> 12 from theano.compile.mode import *
     13 
     14 from theano.compile.io import *

C:\ProgramData\Anaconda3\lib\site-packages\theano\compile\mode.py in <module>()
      9 import theano
     10 from theano import gof
---> 11 import theano.gof.vm
     12 from theano import config
     13 from six import string_types

C:\ProgramData\Anaconda3\lib\site-packages\theano\gof\vm.py in <module>()
    680 except ImportError:
    681     pass
--> 682 except (OSError, theano.gof.cmodule.MissingGXX) as e:
    683     # OSError happens when g++ is not installed.  In that case, we
    684     # already changed the default linker to something else then CVM.

AttributeError: module 'theano' has no attribute 'gof'

```

**Comment by bdwyer2** [comment] 2017-11-27 20:41
What is the contents of your `keras.json` file?
`%USERPROFILE%/.keras/keras.json`

**Comment by ranjita-naik** [comment] 2017-12-07 06:40
I was able to resolve this error by switching to keras 1.2.2 + theano 0.9.0

**Comment by nouiz** [comment] 2017-12-11 15:43
For the original error, most of the time the problem is that there is multiple Theano installed in the environment. Remove Theano multiple time to be sure there isn't one anymore and reinstall it.

This is probably why it was fixed by installing another version.

Otherwise, just import theano in python and it could give a better error message depending of how keras handle errors in different part.

**Closed** 2018-03-04 14:39 UTC
