### ISSUE TITLE
bortedError: Operation received an exception:Status: 3, message: could not create a dilated convolution forward descriptor

### ISSUE THREAD

**Issue by FirasMegrahi** [keras-team/keras#12588] opened 2019-04-01 09:14 UTC
Hello,

i'm trying to implement a model of image classification, 
i'm using **Mobilene**t, i'm getting an error while running "mobile.predict(image)"
the error is : "**AbortedError: Operation received an exception:Status: 3, message: could not create a dilated convolution forward descriptor, in file tensorflow/core/kernels/mkl_conv_ops.cc:1111
	 [[{{node conv1/convolution}}]**]"
here is my script. 

import keras
from keras import backend as K
from keras.layers.core import Dense, Activation
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing import image
from keras.models import Model
from keras.applications import imagenet_utils
from keras.layers import Dense,GlobalAveragePooling2D
from keras.applications import MobileNet
from keras.applications.mobilenet import preprocess_input
import numpy as np
from IPython.display import Image
from keras.optimizers import Adam

#import de la fonction mobilenet
mobile = keras.applications.mobilenet.MobileNet()
#preprocessiong image

def prepare_image(file):

    img_path = ''

    img = image.load_img(img_path + file, target_size=(224, 224))

    img_array = image.img_to_array(img)

    img_array_expanded_dims = np.expand_dims(img_array, axis=0)

    return keras.applications.mobilenet.preprocess_input(img_array_expanded_dims)

preprocessed_image = prepare_image('lion.jpg')

**predictions = mobile.predict(preprocessed_image)**

results = imagenet_utils.decode_predictions(predictions)

results

**Comment by samsterckval** [comment] 2019-04-10 09:09
I have the same problem, using MobileNetV2

**Comment by prag79** [comment] 2019-04-28 10:55
I am getting this same issue, Keras v2.2.4 and Tensorflow is v1.13.1. Any resolution?

**Comment by JanderHungrige** [comment] 2019-05-03 09:29
[Here ](https://github.com/tensorflow/tensorflow/issues/24650) they say that it is resolved in the master branch, but I receive the same error with mobileNetV2 and mobileNet.
For me it worked before with Keras v2.2.2 and Tensorflow v1.10.0

**Comment by agilebean** [comment] 2019-07-09 02:36
@JanderHungrige thanks so much for your hint which made me realize this error is caused by the mobilenet models.
I tested and can confirm this error is not thrown by the following models:
    'VGG16',
    'VGG19',
    'InceptionV3',
    'Xception',
    'ResNet50',
    'DenseNet201',
    'InceptionResNetV2’

**Comment by HKjoe** [comment] 2019-08-08 03:28
I try to fine-tuning the MobileNet in my code. I can use model.fit to train my model, but i received the same error when i apply model.evaluate in the trained model. My Keras is also 2.2.4, and TensorFlow is 1.13.1.

**Comment by blakeedwards823** [comment] 2019-08-20 17:36
> I am getting this same issue, Keras v2.2.4 and Tensorflow is v1.13.1. Any resolution?

Did you ever find a solution? I am running the same versions and am having the same problem.

**Comment by JanderHungrige** [comment] 2019-09-10 12:45
> 
> 
> > I am getting this same issue, Keras v2.2.4 and Tensorflow is v1.13.1. Any resolution?
> 
> Did you ever find a solution? I am running the same versions and am having the same problem.

As mentioned in my earlier comment, they fixed it in the tensorflow2 version. It was working in the Alpha version and my guess is, it is working in the beta as well. I hope your project allows you to upgrade to TF2

good luck with your code

**Closed** 2021-06-24 22:36 UTC
Labels: type:support
