### ISSUE TITLE
I want LSTM to learn with newer data. It needs to update itself depending on the trend in the new data and I wish to save this say in a file. Then I wish to call this pre-fed training  file into any other X,Y,Z fresh files where testing is done. So I wish to 're-fit' [update NOT re-train] the model with new data such that model parameters are just updated and not re-initialized. I understand this is online learning but how to implement it through Keras? Can someone please advise?

### ISSUE THREAD

**Issue by phdrsch** [keras-team/keras#14380] opened 2021-01-20 02:32 UTC

**Comment by sushreebarsa** [comment] 2021-07-29 12:27
@phdrsch In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by sushreebarsa** [comment] 2021-08-03 06:50
Closing this issue due to lack of recent activity  .Please feel free to reopen if you still have concern.Thanks!

**Closed by sushreebarsa** 2021-08-03 06:50 UTC
Labels: stat:awaiting response, type:support
