### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.src

### ISSUE THREAD

**Issue by elbeetheone** [keras-team/keras#18878] opened 2023-12-04 09:43 UTC
I get the following error when trying to instantiate a saved model. Can I get clarity on what module this is. I have the latest versions of tensorflow and keras installed.

Context: I am uploading the model using joblib. 

The model saves just fine but I am unable to load it within my application.

`ModuleNotFoundError: No module named 'keras.src'`

**Comment by fchollet** [comment] 2023-12-04 17:08
Sounds like to could be a Keras version issue. What are your versions?

**Comment by SuryanarayanaY** [comment] 2023-12-08 04:59
Hi @elbeetheone ,

Can you confirm the keras version you are using and also the reproducible code snippet.

It seems like the issue with `keras<=2.12` versions. If we try something like `from keras.src import layers` it will raise 

`ModuleNotFoundError: No module named 'keras.src'` since keras.src exists from TF2.13v onwards.



If we use keras>=2.13v or Keras3 the above import works.

Attaching a simple [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5e2649676ddd7b0765027e2afd95fef7/18878.ipynb) that reproduces the reported error with `keras<=2.12` and which doesn't exists in  keras>=2.13v or Keras3.

**Comment by elbeetheone** [comment] 2023-12-08 10:02
Hi there,

The issue is most likely the version. 

`[keras - 2.6.0](https://pypi.python.org/pypi/keras/2.6.0)`

I'll have to initiate a work around. It's a third party application that won't let me install the newest version. 

Thanks for the assistance.

**Comment by SuryanarayanaY** [comment] 2023-12-12 04:10
Hi @elbeetheone ,

Thanks for confirmation.Could you please close the issue as the root cause is clear now. Thanks!

**Closed** 2023-12-12 10:56 UTC
Labels: type:support, stat:awaiting response from contributor

**Comment by Mohsi76** [comment] 2024-03-20 17:56
@elbeetheone i am facing this issue No module named 'keras.src.engine', will you help me to solve the problem?

**Comment by Magnificent-01** [comment] 2024-03-27 07:20
ModuleNotFoundError: No module named 'keras.src.engine'

**Comment by elbeetheone** [comment] 2024-03-27 12:29
> @elbeetheone i am facing this issue No module named 'keras.src.engine', will you help me to solve the problem?

Please confirm the keras version you are using.

**Comment by Blessing988** [comment] 2024-03-29 14:45
Hello I'm facing the same error 
I'm using `keras 2.6.0`

**Comment by Mohsi76** [comment] 2024-04-02 16:26
Hi, if you are using new version of tensorflow then uninstall because its
due to mismatch with addons version and reinstall old version of tensorflow.
