### ISSUE TITLE
tf.keras.preprocessing.timeseries_dataset_from_array changes data types

### ISSUE THREAD

**Issue by MattWolf74** [keras-team/keras#14569] opened 2021-03-31 18:15 UTC
I am constructing a tf dataset from a pandas dataframe and use the function `tf.keras.preprocessing.timeseries_dataset_from_array`.

The relevant column datatype is float32 in the dataframe, however, the dtype of the resulting dataset is float64? Why is that the case and how can I retain the original datatype(s)?

`ds = tf.keras.preprocessing.timeseries_dataset_from_array(
        data=data,
        targets=None,
        sequence_length=total_window_size,
        sequence_stride=1,
        batch_size=batch_size)`

**Comment by ymodak** [comment] 2021-07-01 21:06
I was not able to reproduce the reported behavior. 
Please take a look at a toy example I tried;
```python
import tensorflow as tf
print(tf.__version__)
import numpy as np 
X = np.arange(100, dtype='float32')
sample_length = 20
input_dataset = tf.keras.preprocessing.timeseries_dataset_from_array(
    X, None, sequence_length=sample_length, sequence_stride=sample_length)
print(input_dataset)
```
Output:
```python
2.5.0
<BatchDataset shapes: (None, None), types: tf.float32>
```

**Comment by ymodak** [comment] 2021-07-14 19:12
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2021-07-14 19:12 UTC
Labels: stat:awaiting response, type:support
