### ISSUE TITLE
 InvalidArgumentError (see above for traceback): **indices[6,4]** = 23624 is not in [0, 23624)

### ISSUE THREAD

**Issue by marc88** [keras-team/keras#11819] opened 2018-12-07 12:00 UTC
I get the following error after running an embedding layer as;

`Embedding(23624, 50, input_length=5, trainable=False)`

> InvalidArgumentError (see above for traceback): **indices[6,4]** = 23624 is not in [0, 23624)
> 	 [[Node: embedding_1/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_1/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_1/embeddings/read, embedding_1/Cast)]]

Each datapoint here is a number(index). Upon checking indices[6,4] I found the following

```
print(ar_train_data[6,4])
5088
```
ar_train_data is an array of shape (162896, 5) where each value is  between [0, 23624).
The training stops towards the end of the first epoch with the error above.

Am amazed! 5088 is no where out of range for [0, 23624).  Can anyone suggest what could be the issue here?
Please suggest if additional code snippets are required for clarity.
The model roughly goes below as:

```
inputs =  Input(shape=(None,),dtype='float32')
               <Embedding layer>
               <Convolution layer>
linear_output = Dense(10,input_shape=(72,),activation='relu')(linear_input)

model = Model(inputs=[inputs],outputs=[linear_output])
model.compile(loss='categorical_crossentropy', optimizer='nadam')
```

Full error trace:

> ---------------------------------------------------------------------------
> InvalidArgumentError                      Traceback (most recent call last)
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1349     try:
> -> 1350       return fn(*args)
>    1351     except errors.OpError as e:
> 
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
>    1328                                    feed_dict, fetch_list, target_list,
> -> 1329                                    status, run_metadata)
>    1330 
> 
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
>     472             compat.as_text(c_api.TF_Message(self.status.status)),
> --> 473             c_api.TF_GetCode(self.status.status))
>     474     # Delete the underlying status object from memory otherwise it stays alive
> 
> InvalidArgumentError: indices[6,4] = 23624 is not in [0, 23624)
> 	 [[Node: embedding_8/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_8/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_8/embeddings/read, embedding_8/Cast)]]
> 
> During handling of the above exception, another exception occurred:
> 
> InvalidArgumentError                      Traceback (most recent call last)
> <ipython-input-41-3591dc7735b9> in <module>()
> ----> 1 model.fit(ar_train_data,train_label,validation_data=(ar_valid_data,valid_label),epochs=10,batch_size=batch_size)
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, **kwargs)
>    1037                                         initial_epoch=initial_epoch,
>    1038                                         steps_per_epoch=steps_per_epoch,
> -> 1039                                         validation_steps=validation_steps)
>    1040 
>    1041     def evaluate(self, x=None, y=None,
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py in fit_loop(model, f, ins, out_labels, batch_size, epochs, verbose, callbacks, val_f, val_ins, shuffle, callback_metrics, initial_epoch, steps_per_epoch, validation_steps)
>     210                         val_outs = test_loop(model, val_f, val_ins,
>     211                                              batch_size=batch_size,
> --> 212                                              verbose=0)
>     213                         val_outs = to_list(val_outs)
>     214                         # Same labels assumed.
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py in test_loop(model, f, ins, batch_size, verbose, steps)
>     390                 ins_batch[i] = ins_batch[i].toarray()
>     391 
> --> 392             batch_outs = f(ins_batch)
>     393             if isinstance(batch_outs, list):
>     394                 if batch_index == 0:
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in __call__(self, inputs)
>    2719                     'In order to feed symbolic tensors to a Keras model '
>    2720                     'in TensorFlow, you need tensorflow 1.8 or higher.')
> -> 2721             return self._legacy_call(inputs)
>    2722 
>    2723 
> 
> /opt/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in _legacy_call(self, inputs)
>    2691         session = get_session()
>    2692         updated = session.run(fetches=fetches, feed_dict=feed_dict,
> -> 2693                               **self.session_kwargs)
>    2694         return updated[:len(self.outputs)]
>    2695 
> 
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
>     893     try:
>     894       result = self._run(None, fetches, feed_dict, options_ptr,
> --> 895                          run_metadata_ptr)
>     896       if run_metadata:
>     897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)
> 
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
>    1126     if final_fetches or final_targets or (handle and feed_dict_tensor):
>    1127       results = self._do_run(handle, final_targets, final_fetches,
> -> 1128                              feed_dict_tensor, options, run_metadata)
>    1129     else:
>    1130       results = []
> 
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
>    1342     if handle is None:
>    1343       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
> -> 1344                            options, run_metadata)
>    1345     else:
>    1346       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)
> 
> /opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
>    1361         except KeyError:
>    1362           pass
> -> 1363       raise type(e)(node_def, op, message)
>    1364 
>    1365   def _extend_graph(self):
> 
> InvalidArgumentError: indices[6,4] = 23624 is not in [0, 23624)
> 	 [[Node: embedding_8/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_8/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_8/embeddings/read, embedding_8/Cast)]]
> 
> Caused by op 'embedding_8/embedding_lookup', defined at:
>   File "/opt/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/opt/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
>     app.launch_new_instance()
>   File "/opt/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
>     app.start()
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 478, in start
>     self.io_loop.start()
>   File "/opt/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
>     super(ZMQIOLoop, self).start()
>   File "/opt/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
>     handler_func(fd_obj, events)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
>     self._handle_recv()
>   File "/opt/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
>     self._run_callback(callback, msg)
>   File "/opt/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
>     callback(*args, **kwargs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
>     return fn(*args, **kwargs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
>     return self.dispatch_shell(stream, msg)
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
>     handler(stream, idents, msg)
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
>     user_expressions, allow_stdin)
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>   File "/opt/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
>     interactivity=interactivity, compiler=compiler, result=result)
>   File "/opt/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2850, in run_ast_nodes
>     if self.run_code(code, result):
>   File "/opt/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-39-c3ad63e8ca6c>", line 25, in <module>
>     sent_embed = Embedding(input_dim=vocab_size+1,output_dim=embedding_size,input_length=2*WINDOW_SIZE+1,trainable=False)(sent_grams)
>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py", line 457, in __call__
>     output = self.call(inputs, **kwargs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/layers/embeddings.py", line 141, in call
>     out = K.gather(self.embeddings, inputs)
>   File "/opt/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 1228, in gather
>     return tf.nn.embedding_lookup(reference, indices)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 325, in embedding_lookup
>     transform_fn=None)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
>     result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
>     return array_ops.gather(params, ids, name=name)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2585, in gather
>     params, indices, validate_indices=validate_indices, name=name)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1864, in gather
>     validate_indices=validate_indices, name=name)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
>     op_def=op_def)
>   File "/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
>     self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
> 
> InvalidArgumentError (see above for traceback): indices[6,4] = 23624 is not in [0, 23624)
> 	 [[Node: embedding_8/embedding_lookup = Gather[Tindices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@embedding_8/embeddings"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_8/embeddings/read, embedding_8/Cast)]]

Keras version - 2.2.4
tensorflow version: 1.5.0

Regards

**Comment by Surojit88** [comment] 2018-12-09 07:08
@SriRangaTarun  It's a common practice to have the embeddings as vocab_size+1 and I've just done that by having my embeddings at 23624 with a vocab size of 23623. So, the problem doesn't lie there.

@gabrieldemarmiesse : Is there anyway you can help? Apologies but, I couldn't understand the meaning of the tag added.

**Comment by gabrieldemarmiesse** [comment] 2018-12-09 09:46
There is a description for each tag that you can see if you put your mouse on it.

This means that this may be a bug, but I'm not sure. It could be a user error. Someone needs to investigate to go to the bottom of it. (not necessarily me since I don't have the time to investigate in depth each issue in keras).

**Comment by mkaze** [comment] 2018-12-12 07:32
@Surojit88 It seems there is (are) an element(s) with index `23624` in the training data: `23624 is not in [0, 23624)`. Use [`np.where`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html) to find out where they are: `np.where(ar_train_data == 23624)`.

**Comment by marc88** [comment] 2018-12-12 13:22
@mkaze  As suggested above, that's not the case

**Comment by jvishnuvardhan** [comment] 2019-03-13 21:09
@marc88 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by kak-to-tak** [comment] 2019-03-14 11:45
I'm having the same issue:
```
nvalidArgumentError: indices[20,19] = 16492 is not in [0, 16492) 	 [[{{node embedding_1/embedding_lookup}}]]
```
increasing the vocabulary length doesn't help
```
word_embedding = Embedding(input_dim=**len(vocabulary)+1,** output_dim=128, mask_zero=True)(word_input)
```
What could be the issue in this case?

**Comment by jvishnuvardhan** [comment] 2019-05-07 22:03
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Closed by jvishnuvardhan** 2019-05-07 22:03 UTC
Labels: To investigate, backend:tensorflow, stat:awaiting response
