### ISSUE TITLE
InvalidArgumentError caused by using class_weights and flow_from_dataframe

### ISSUE THREAD

**Issue by dendrondal** [keras-team/keras#13732] opened 2020-01-30 02:17 UTC
**System information**  
- Have I written custom code (as opposed to using example directory):  Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 18.04
- TensorFlow backend (yes / no):  yes
- TensorFlow version:  2.1.0
- Keras version:  2.3.1
- Python version:  3.7.4
- CUDA/cuDNN version: 10.1  
- GPU model and memory:  NVIDIA Tesla K80 w/ 12GB VRAM 

**Describe the current behavior**  
When attempting to use class balancing with ImageGeneration().flow_from_dataframe(), the stacktrace below is thrown. The same result happens both in the case of weight_col being used as an argument for flow_from_dataframe, and class_weight used as an argument for Model().fit(). It should be noted that model training proceeds without error when no class weights are included. 

**Describe the expected behavior**  
Model training should take class imbalance into account with the weights I provide.

**Code to reproduce the issue**  
Assume that df is a Pandas DataFrame consisting of valid filepaths and classes, and model is a pre-compiled CNN with rmsprop as an optimizer.  In particular, my use case had 4 classes. Again, training without class weights worked, implying that the error comes from neither the model or dataframe objects.

_ Method 1_
```
class_weights = {
0: 5.508955223880597, 
1: 1.4212552945706585, 
2: 8.705188679245284, 
3: 1.0
}
model.fit(ImageDataGenerator().flow_from_dataframe(df), class_weight= class_weights)
```
_Method 2_
After using df.apply with a custom function, the dataframe looked like this:

|filename|class  |weight|
|file 1      |class1|    1.42|
|file2|       class3|      1.0|
|file3|       class0|      5.5|
...etc. 

`model.fit(ImageDataGenerator().flow_from_dataframe(df, weight_col='weight))`
 

**Other info / logs**  
```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/ubuntu/.pyenv/versions/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/CIf3R/cif3r/models/train_model.py", line 175, in <module>
    tensorboard(),
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 819, in fit
    use_multiprocessing=use_multiprocessing)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 342, in fit
    total_epochs=epochs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 128, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 98, in execution_function
    distributed_function(input_fn))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 632, in _call
    return self._stateless_fn(*args, **kwds)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 2363, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1611, in _filtered_call
    self.captured_inputs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1692, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 545, in call
    ctx=ctx)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/cif3r-EJ8-K5-v-py3.7/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 32
	 [[node loss/output_loss/weighted_loss/Squeeze (defined at /CIf3R/cif3r/models/train_model.py:175) ]]
  (1) Invalid argument:  Can not squeeze dim[0], expected a dimension of 1, got 32
	 [[node loss/output_loss/weighted_loss/Squeeze (defined at /CIf3R/cif3r/models/train_model.py:175) ]]
	 [[metrics/auc/assert_greater_equal/Assert/AssertGuard/pivot_f/_45/_35]]
0 successful operations.
0 derived errors ignored. [Op:__inference_distributed_function_11180]

Function call stack:
distributed_function -> distributed_function
```
Please let me know if any additional information is required.

**Comment by SaiSandeepKantareddy** [comment] 2020-07-15 18:58
Hey, this is working, once check your classes encoding, that might be the possile error, I solved it in that way.

**Comment by Saduf2019** [comment] 2021-07-06 14:22
@dendrondal 
Moving this to closed status as the issue is resolved.

**Closed by Saduf2019** 2021-07-06 14:22 UTC
Labels: type:bug/performance
