### ISSUE TITLE
TypeError: ('Keyword argument not understood:', 'inputs')

### ISSUE THREAD

**Issue by amarsharma441** [keras-team/keras#13743] opened 2020-02-04 18:38 UTC
keras version : 2.2.4-tf
Using TensorFlow backend.

![73775035-1e352300-47ab-11ea-8088-c63fd6579606](https://user-images.githubusercontent.com/42449336/73775195-72400780-47ab-11ea-8835-4858f0c11524.png)

**Comment by pablo53** [comment] 2020-02-15 20:10
I faced the same issue in TensorFlow 2.0, however this does not seem to be an issue in TensorFlow 2.1. In TF 2.0, I just passed both inputs and outputs as positional parameters and it worked.

**Comment by amarsharma441** [comment] 2020-02-15 20:14
> I faced the same issue in TensorFlow 2.0, however this does not seem to be an issue in TensorFlow 2.1. In TF 2.0, I just passed both inputs and outputs as positional parameters and it worked.

It worked, Thank You.

**Comment by maxboels** [comment] 2020-03-30 10:14
Hey, How do you pass them as positional parameters?

Thank you

**Comment by ramahasan** [comment] 2020-04-01 18:57
I faced the same problem with tf.2.1. But please what do you mean by 'assed both inputs and outputs as positional parameters'? could you please give an example?

**Comment by freedom9393** [comment] 2020-04-06 09:14
Changing this:
`model_final = Model(input = model.input, output = predictions)`
to
`model_final = Model(model.input, predictions)`
worked for me

**Comment by nitinmnsn** [comment] 2020-05-29 10:08
This is a consfusing error message by tensorflow. actually the solution is to pass the correct keywords which are : `inputs` and `outputs`. If you are passing `output` as the keyword to `tf.keras.Model` tensorflow should throw the error saying it cannot understand `output` keyword not `inputs` keyword which, it corrently does
The following codepieces should say the same:
```
in1 = k.Input(shape=(10),dtype=tf.float32)
vec = tf.Variable(initial_value=np.arange(start=1000,stop=1010,dtype=np.float32).reshape(-1,10))
ou1 = l.Add()([in1,vec])
model=k.Model(inputs=[in1],output=[ou1])
```
vs 
```
in1 = k.Input(shape=(10),dtype=tf.float32)
vec = tf.Variable(initial_value=np.arange(start=1000,stop=1010,dtype=np.float32).reshape(-1,10))
ou1 = l.Add()([in1,vec])
model=k.Model(inputs=[in1],outputs=[ou1])
```

**Comment by cihan063** [comment] 2020-07-10 03:01
> Changing this:
> `model_final = Model(input = model.input, output = predictions)`
> to
> `model_final = Model(model.input, predictions)`
> worked for me. Or just perform same operation for your case

model=tf.keras.Model(inputs=img_inputs, output=output) to 
model=tf.keras.Model(img_inputs, output)

It worked for me thank you

**Comment by phoenix-meadowlark** [comment] 2020-07-17 18:22
This issue should be fixed in future visions of TensorFlow with [this commit](https://github.com/tensorflow/tensorflow/commit/34f2782a79d339d2f59114210a0250ed6cdf8b7e).

**Comment by BaiqSiska** [comment] 2020-08-05 12:07
> > Changing this:
> > `model_final = Model(input = model.input, output = predictions)`
> > to
> > `model_final = Model(model.input, predictions)`
> > worked for me. Or just perform same operation for your case
> 
> model=tf.keras.Model(inputs=img_inputs, output=output) to
> model=tf.keras.Model(img_inputs, output)
> 
> It worked for me thank you

its worked for me, thanks

**Comment by lz-chen** [comment] 2020-09-03 08:39
> This is a consfusing error message by tensorflow. actually the solution is to pass the correct keywords which are : `inputs` and `outputs`. If you are passing `output` as the keyword to `tf.keras.Model` tensorflow should throw the error saying it cannot understand `output` keyword not `inputs` keyword which, it corrently does
> The following codepieces should say the same:
> 
> ```
> in1 = k.Input(shape=(10),dtype=tf.float32)
> vec = tf.Variable(initial_value=np.arange(start=1000,stop=1010,dtype=np.float32).reshape(-1,10))
> ou1 = l.Add()([in1,vec])
> model=k.Model(inputs=[in1],output=[ou1])
> ```
> 
> vs
> 
> ```
> in1 = k.Input(shape=(10),dtype=tf.float32)
> vec = tf.Variable(initial_value=np.arange(start=1000,stop=1010,dtype=np.float32).reshape(-1,10))
> ou1 = l.Add()([in1,vec])
> model=k.Model(inputs=[in1],outputs=[ou1])
> ```

This seems to be the cause, as least in my case.

**Comment by ketan9808** [comment] 2020-11-29 10:55
I think this error is due to misspelling of inputs and outputs. Please check that you've written inputs instead of input and outputs instead of output.

**Comment by amay428** [comment] 2020-12-16 14:26
> This is a consfusing error message by tensorflow. actually the solution is to pass the correct keywords which are : `inputs` and `outputs`. If you are passing `output` as the keyword to `tf.keras.Model` tensorflow should throw the error saying it cannot understand `output` keyword not `inputs` keyword which, it corrently does
> The following codepieces should say the same:
> 
> ```
> in1 = k.Input(shape=(10),dtype=tf.float32)
> vec = tf.Variable(initial_value=np.arange(start=1000,stop=1010,dtype=np.float32).reshape(-1,10))
> ou1 = l.Add()([in1,vec])
> model=k.Model(inputs=[in1],output=[ou1])
> ```
> 
> vs
> 
> ```
> in1 = k.Input(shape=(10),dtype=tf.float32)
> vec = tf.Variable(initial_value=np.arange(start=1000,stop=1010,dtype=np.float32).reshape(-1,10))
> ou1 = l.Add()([in1,vec])
> model=k.Model(inputs=[in1],outputs=[ou1])
> ```

This worked for me. Thanks!

**Comment by sushreebarsa** [comment] 2021-07-08 09:44
@amarsharma441 Moving this issue to closed status as there has been no recent activity.In case you still face the error please create a new issue,we will get you the right help.Thanks!

**Closed by sushreebarsa** 2021-07-08 09:44 UTC
Labels: type:support
