### ISSUE TITLE
Unimplemented `tf.keras.Model.call()` - even though it's implemented!

### ISSUE THREAD

**Issue by innat** [keras-team/keras#16662] opened 2022-06-07 11:27 UTC
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): 2.9
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GPU model and memory:
- Exact command to reproduce:

**Describe the problem**.

This issue emerged from another issue, here https://github.com/keras-team/keras/issues/16654. 

Train the model and save it. After reloading the model from the saved location, it can't perform inference tasks (`.evaluate` or `.predict`). It shows 

```
NotImplementedError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1845, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1834, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1823, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1791, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 517, in call
        raise NotImplementedError('Unimplemented `tf.keras.Model.call()`: if you '

    NotImplementedError: Exception encountered when calling layer "model_2" (type Model).
    
    Unimplemented `tf.keras.Model.call()`: if you intend to create a `Model` with the Functional API, please provide `inputs` and `outputs` arguments. Otherwise, subclass `Model` with an overridden `call()` method.
    
    Call arguments received by layer "model_2" (type Model):
      • inputs=tf.Tensor(shape=(None, 28, 28, 1), dtype=float32)
      • training=False
      • mask=None
```

Even though the `call` method is implemented in Model class.

**Standalone code to reproduce the issue**.

[Reproducible Code](https://colab.research.google.com/drive/1F3ZbRvT8-KONRTVIj2cKsp0zomystF54?usp=sharing).

**Comment by tilakrayal** [comment] 2022-06-08 09:44
Hi @innat,
Looks like this is a duplicate of issue #16654. Could you close this issue, since it is already being tracked there? Thank you!

**Comment by innat** [comment] 2022-06-08 10:05
If both issues are the same, they would have produced the same error. But they didn't.

**Comment by innat** [comment] 2022-06-10 02:32
@tilakrayal 
Please check the file again. This issue is produced by tensorflow 2.9. It gives different errors at inference time after reloading the model.

Another issue is that is produced by tensorflow 2.8 and with completely different errors. They are NOT the same. The gist file is NOT the same. 

What makes you confuse is the same code structure of both gists which shouldn't be. Please let us know if you can reproduce the issue with tf 2.9. Thanks.

**Comment by tilakrayal** [comment] 2022-06-14 04:54
@gowthamkpr,
I was able to reproduce the error in tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/d1d5cec27b0c49c18a027f6ab981fcc1/16654.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/2bc9e6a8159fc2c02ed5dc3c0e48f01c/16654.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/5b02c888c2d40008a8040346d9810deb/2_10_16662.ipynb). Kindly find the gist here.

**Comment by mattdangerw** [comment] 2022-06-16 17:07
This looks like it may be a regression in 2.9. Assigning @k-w-w to take a look!

**Comment by ghylander** [comment] 2023-02-15 09:02
I assume this has not been addressed and it's still an issue present in tf 2.11?
I am encountering this error too when trying to train a SimCLR pretrained model (https://github.com/google-research/simclr)

I subclass Model with an overriden call() method, then save the model.
Simply attempting to load the model from disk will throw this error.

You can test it with this code:

```
import tensorflow as tf

class Model(tf.keras.Model):
    def __init__(self, path):
        super(Model, self).__init__()
        self.saved_model = tf.saved_model.load(path)

    def call(self, image, training):
        return self.saved_model(image, trainable=False)['final_avg_pool']

base_model = Model("gs://simclr-checkpoints-tf2/simclrv2/finetuned_100pct/r50_1x_sk0/saved_model/")

prediction_layer = tf.keras.layers.Dense(5, activation='sigmoid', kernel_initializer='random_uniform', bias_initializer='zeros')

inputs = tf.keras.Input(shape=(224, 224, 3))

x = base_model(inputs, training=False)
outputs = prediction_layer(x)

model = tf.keras.Model(inputs, outputs)

model.save('SIMCLR.h5')

model = tf.keras.models.load_model('SIMCLR.h5')
```

**Comment by k-w-w** [comment] 2023-02-15 17:53
Sorry for the late reply. Using `Model` as the Model class name is the issue (as it collides with `keras.Model` class). We have an internal bug tracking this. Reassigning to Rick as the new format should also be affected.

**Closed** 2023-08-04 18:42 UTC
Labels: type:bug/performance
