### ISSUE TITLE
Keras crashes with LSTM layer

### ISSUE THREAD

**Issue by ildar-idrisov** [keras-team/keras#12397] opened 2019-03-05 09:29 UTC
Hello, my problem is crash (system reboots) when using LSTM layer.
Simplified code to reproduce problem:

    from keras.models import Model
    from keras.layers import Input, LSTM
    model_input = Input(shape=(5, 224))
    model_output = LSTM(256)(model_input) <--- system reboots
    final_model = Model(model_input, outputs=model_output)

System config:
Ubuntu 18.04
NVidia RTX 2080 Ti
Keras v2.24
TensorFlow v1.13.1
NVidia driver v410.79
CUDA v10.0
cuDNN v7.5.0

Could someone help me please?

**Comment by ymodak** [comment] 2019-03-06 01:26
The script executed successfully on my macOS machine. This does not look like a bug on TF side.

**Comment by ildar-idrisov** [comment] 2019-03-06 03:56
ymodak, thank you.

The other models work well. If the problem was hardware, it would not have worked.
Also I had a problem with running all the pre-trained models from keras.applications when I used TF v1.13.0rc2. The problem was solved by installation of stable TF version 1.13.1.
Probably API has changed in new versions of TF and Keras does not support it. But I can't install the previous version of TF because of 2080 Ti.

What do I need to see to determine the cause of the problem?

**Comment by ymodak** [comment] 2019-03-08 02:54
I ran your script successfully using multiple TF versions was not able to reproduce your behavior. Adding @qlzh727 he may know more.

**Comment by qlzh727** [comment] 2019-03-08 03:50
"system reboots" seems to indicate that something is wrong on the system level, eg some system lib or GPU lib was corrupted. Is there any syslog available right before it reboots?

**Comment by ildar-idrisov** [comment] 2019-03-11 05:17
@ymodak, @qlzh727 thank you guys.
It looks like the problem is not keras/tf. I did an interesting test.
I made a debag when adding the lstm layer, and found that the reboot was in the linalg module. Next I booted up from liveusb and ran scipy.test("full"). On the module scipy linalg/tests/test_decomp.py got a reboot.
That's weird. But it says the problem is probably in my hardware.

**Comment by qlzh727** [comment] 2019-03-11 15:17
Ack, I am closing this bug as it is not related to TF/Keras. Feel free to reopen it if there is any other issue.

**Closed by qlzh727** 2019-03-11 15:17 UTC
Labels: backend:tensorflow, stat:awaiting response, type:support
