### ISSUE TITLE
Batch Normalization with virtual_batch_size not equal to None not implemented correctly for inference time

### ISSUE THREAD

**Issue by ccurro** [keras-team/keras#15790] opened 2021-12-15 00:12 UTC
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- TensorFlow installed from (source or binary): 
- TensorFlow version (use command below): v2.7.0-rc1-69-gc256c071bb2 2.7.0
- Python version: 3.7.12
- Bazel version (if compiling from source):
- GPU model and memory: 
- Exact command to reproduce: 

**Describe the problem**.

The batch normalization implementation respects the `virtual_batch_size` parameter in both train and inference modes. As such you are unable to do inference with batch sizes that are not multiples of the `virtual_batch_size`. Algorithm 1 in the [ghost batch norm paper](https://arxiv.org/pdf/1705.08741.pdf) makes it clear that `virtual_batch_size` should only be respected in train mode. See https://github.com/tensorflow/tensorflow/issues/23050 for a previous discussion, since 2018. Opening here on the direction of @tensorflowbutler 

**Describe the current behavior**.

If the batch dimension is not a multiple of `virtual_batch_size`  tensorflow raises:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Exception encountered when calling layer "batch_normalization" (type BatchNormalization).

Input to reshape is a tensor with 784 values, but the requested shape requires a multiple of 25088 [Op:Reshape]

Call arguments received:
  • inputs=tf.Tensor(shape=(1, 28, 28, 1), dtype=float32)
  • training=False
```

**Describe the expected behavior**.

The layer should normalize using the saved statistics from train time - essentially ignoring the `virtual_batch_size`

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.

```
import tensorflow as tf
import numpy as np

virtual_batch_size = 32

x_train = np.random.random(size=[4*virtual_batch_size, 28, 28, 1])
x_test = np.random.random(size=[virtual_batch_size, 28, 28, 1])
x_inference = np.random.random(size=[1, 28, 28, 1])
                               
bn_layer = tf.keras.layers.BatchNormalization(virtual_batch_size=virtual_batch_size)

assert bn_layer(x_train) is not None
assert bn_layer(x_test, training=False) is not None

# fails on this line:
bn_layer(x_inference, training=False)
```
https://colab.research.google.com/drive/1msCAtSzBAhwmegi41Bs5bgf6PsHLYtg5?usp=sharing

**Comment by sanatmpa1** [comment] 2021-12-17 16:27
@ccurro,

I am able to reproduce the issue reported in colab with `TF 2.7.0`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/36a5739b57dd0aed170a2a158f9f1428/15790.ipynb). Thanks!

**Comment by rchao** [comment] 2021-12-23 18:19
Triage: keeping this open for contribution as the team doesn't currently have the bandwidth.

**Comment by old-school-kid** [comment] 2022-01-15 20:28
@rchao @ccurro 
Correct me if I am wrong. Arent ghost batches like mini batches. That is the ghost batched will be subset of the batch?
So the batch size must be divisble by ghost batch number which is exactly what is recommended by keras-team in this [line of comment](https://github.com/keras-team/keras/blob/2c48a3b38b6b6139be2da501982fd2f61d7d48fe/keras/layers/normalization/batch_normalization.py#L759)
So here the error is raised since 1 cannot be divided by 32.

**Comment by ccurro** [comment] 2022-01-15 20:40
@old-school-kid That is true when `training=True` but when `training=False` you should be able to have any batch size. `virtual_batch_size` should have no effect during inference.

**Comment by tilakrayal** [comment] 2023-05-09 06:04
@ccurro,
The related PR #17065 was merged and also tried to execute the mentioned code on tf-nightly(2.14.0-dev20230508) and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/022032b9db3eaa280dd0729be4e3b115/untitled1118.ipynb).
https://github.com/keras-team/keras/blob/master/keras/layers/normalization/batch_normalization.py
Thank you!

**Comment by ccurro** [comment] 2023-05-09 11:19
Looks good! Thanks @tilakrayal :slightly_smiling_face:

**Closed** 2023-05-09 11:26 UTC
Labels: type:bug/performance, Contributions welcome
