### ISSUE TITLE
Declare tensorflow in package dependencies

### ISSUE THREAD

**Issue by ShadowJonathan** [keras-team/keras#16602] opened 2022-05-26 13:05 UTC
Because each time i do just `pip install keras`, i get met with `No module named 'tensorflow'`, i'd rather just that keras would declare this in dependencies, and have it auto-pull along everything else.

**Comment by sushreebarsa** [comment] 2022-05-26 13:12
@ShadowJonathan To use Keras, please make sure that you need to have the TensorFlow package installed. 
Once TensorFlow is installed, you can import Keras via:
```
from tensorflow import keras

```
Please see the details [here](https://keras.io/getting_started/) and let us know if it helps?
Thank you!

**Comment by ShadowJonathan** [comment] 2022-05-26 13:13
I'm already using keras, but then why is keras [published as an independent package on pypi](https://pypi.org/project/keras/)?

**Comment by gadagashwini** [comment] 2022-06-01 02:32
Hi @ShadowJonathan, As you can see [here](https://pypi.org/project/keras/), it says 

> TensorFlow Keras is an implementation of the Keras API that uses TensorFlow as a backend.

When Tensorflow is installed,It is easy to use Keras library. Thank you!

**Comment by ShadowJonathan** [comment] 2022-06-01 05:27
Yes, so can `tensorflow` be added to `keras`'s package dependencies, so it's automatically installed in when I do `pip install keras`?

**Comment by gadagashwini** [comment] 2022-06-08 06:18
Hi @ShadowJonathan, Keras is added to Tensorflow package. If you want to use Tensorflow and Keras together. We recommend you to install Tensorflow. 
```
!pip install tensorflow
import tensorflow as tf
from tensorflow import keras
```

**Comment by ShadowJonathan** [comment] 2022-06-08 06:59
Then why is `keras` published as an independent package to pypi?

**Comment by gadagashwini** [comment] 2022-06-08 09:09
Hi @ShadowJonathan, We can use Keras alone without any hurdles. But you can’t use Tensorflow, if you installed `pip install keras` library. 

```
pip install keras
import keras
```

**Comment by ShadowJonathan** [comment] 2022-06-08 09:11
@gadagashwini that's what this issue is about; as soon as I do that (without manually installing tensorflow) I get the error that a tensorflow package isn't installed.

My question is; shouldn't `tensorflow` be one of the package dependencies on the `keras` package on pypi, so that it is automatically installed when someone does `pip install keras`?

**Comment by gadagashwini** [comment] 2022-06-08 09:20
Hi @ShadowJonathan, Yes `tensorflow` is one of the Dependencies of the `Keras` package. 
As soon as w install keras `pip install keras`, it doesn’t install Tensorflow. We need to manually install tensorflow. Thank you!

**Comment by ShadowJonathan** [comment] 2022-06-08 09:29
> Yes tensorflow is one of the Dependencies of the Keras package.

> As soon as w install keras pip install keras, it doesn’t install Tensorflow.

...thus, it is not a dependency?

I'm talking about pip dependencies, if `tensorflow` is a dependency of the `keras` package, then why is it not declared in any `setup.py` or the likes, so that it is included in the `METADATA` file on pypi?

---

A quick lesson on pypi packages, it includes some files which contain metadata about the package itself, one of them is the file `METADATA`, which contains dependency information.

An example with the `requests` library is [here](https://www.wheelodex.org/projects/requests/#metadata), where the `METADATA` file contains the following lines;

```
Requires-Dist: | urllib3 (<1.27,>=1.21.1)
Requires-Dist: | certifi (>=2017.4.17)
Requires-Dist: | chardet (<5,>=3.0.2); python_version < "3"
Requires-Dist: | idna (<3,>=2.5); python_version < "3"
Requires-Dist: | charset-normalizer (~=2.0.0); python_version >= "3"
Requires-Dist: | idna (<4,>=2.5); python_version >= "3"
Requires-Dist: | PySocks (!=1.5.7,>=1.5.6); extra == "socks"
Requires-Dist: | win-inet-pton; (sys_platform == "win32" and python_version == "2.7") and extra == "socks"
Requires-Dist: | chardet (<5,>=3.0.2); extra == "use_chardet_on_py3"
Provides-Extra: | security
Provides-Extra: | socks
Provides-Extra: | use_chardet_on_py3
```

These are the lines that pip looks at to find more packages.

In this case, all i'm asking is for the release flow to be altered so that `tensorflow` is listed as one of those dependencies.

If you take a look at the `keras` package [here](https://www.wheelodex.org/projects/keras/#metadata), you can see that there's absolutely no dependency declared, not even `tensorflow`.

---

The whole request of this issue is to get `tensorflow` to get added to the package metadata on pypi, so it is automatically installed, when someone does `pip install keras`.

If this is not possible, please explain to me why this is.

**Comment by gadagashwini** [comment] 2022-06-08 10:01
Hi @ShadowJonathan,

`TensorFlow Keras is an implementation of the Keras API that uses TensorFlow as a backend.`. Thank you!

**Comment by ShadowJonathan** [comment] 2022-06-08 11:56
@gadagashwini then why is `tensorflow` not included as a declared dependency in `pypi`?

**Comment by MTRNord** [comment] 2022-06-08 12:03
> Hi @ShadowJonathan,
> 
> `TensorFlow Keras is an implementation of the Keras API that uses TensorFlow as a backend.`. Thank you!

I think this whole issue is a misunderstanding.

It is clear that this is building on top of tensorflow.

The issue here is that if someone wants to run

```bash
pip install keras
```

on a fresh system. No tensorflow installed whatsoever, then keras will fail running.
This is solvable if you make tensorflow is made a _direct_ dependency in the code you publish instead of just adding a note.

As @ShadowJonathan says you can add it to https://github.com/keras-team/keras/blob/master/requirements.txt just like pandas for example which is a mandatory dependency for keras just like tensorflow is.

That would make pip install usable on a fresh system.

I hope this lifts the confusion?

**Comment by ShadowJonathan** [comment] 2022-06-08 12:08
> As @ShadowJonathan says you can add it to https://github.com/keras-team/keras/blob/master/requirements.txt just like pandas for example which is a mandatory dependency for keras just like tensorflow is.

No, that wont help, as that file seems to be just for development resources, there's no `setup.py` where this can easily be inserted, and the build system is totally alien to me.

**Comment by gadagashwini** [comment] 2022-06-09 07:03
Hi @ShadowJonathan, Request you to take a look at the Keras release notes [here](https://github.com/keras-team/keras/releases/tag/2.3.0). From `Keras v2.3.0`, most of the Keras features are merged into Tensorflow. 

> **This release brings the API in sync with the [tf.keras](https://www.tensorflow.org/beta/guide/keras/) API as of TensorFlow 2.0. However note that it does not support most TensorFlow 2.0 features, in particular eager execution. If you need these features, use [tf.keras](https://www.tensorflow.org/beta/guide/keras/).**

Thank you!

**Comment by MTRNord** [comment] 2022-06-09 07:04
> Hi @ShadowJonathan, Request you to take a look at the Keras release notes [here](https://github.com/keras-team/keras/releases/tag/2.3.0). From `Keras v2.3.0`, most of the Keras features are merged into Tensorflow.
> 
> > **This release brings the API in sync with the [tf.keras](https://www.tensorflow.org/beta/guide/keras/) API as of TensorFlow 2.0. However note that it does not support most TensorFlow 2.0 features, in particular eager execution. If you need these features, use [tf.keras](https://www.tensorflow.org/beta/guide/keras/).**
> 
> Thank you!

You still dont seem to understand the problem here. This is not solving the issue or even talking about the issue. The issue is about something completely other than what you are replying here.

**Comment by ShadowJonathan** [comment] 2022-06-09 07:08
@gadagashwini please take more than 10 seconds to look at this problem.

I'm asking either;
- if `tensorflow` could be added as a declared dependency to the `keras`, package, so it may be downloaded automatically if people install `keras` stand-alone, that `keras` does not assume people have already installed it.
- or, why `keras` exists as an independent package, and/or if the plan is to eventually deprecate it in favour of `tensorflow`

**Comment by qlzh727** [comment] 2022-06-09 17:50
Note that keras can't declare tensorflow in its dependency. Keras is part of the TF API, and TF uses keras as its dependency package to populate tf.keras API name space. It will be a circular dependency if we add TF to keras's dependency list.

PIP install keras is only expected for local dev use case, where user can install other required dependency via the requirements.txt in the keras repo. For normal API usage, user should only access keras via PIP install tensorflow.

For more reason about why keras is a standalone package, please see https://github.com/tensorflow/community/blob/master/rfcs/20200205-standalone-keras-repository.md

**Closed by qlzh727** 2022-06-09 17:50 UTC
Labels: type:support

**Comment by ShadowJonathan** [comment] 2022-06-09 18:11
@qlzh727 thank you for the coherent response.

I'm satisfied with the answer, but i still want to point out that that RFC says "with TensorFlow as a dependency."

And, that none of that is noted in the pypi project readme, or the readme of this repository. Nowhere does it say that the intended usage is for this to be a "local dev usecase", both readmes position it as such that it is "just" a regular API.
