### ISSUE TITLE
InvalidArgumentError "You must feed a value for placeholder tensor" error when composing 2 models

### ISSUE THREAD

**Issue by rfernand2** [keras-team/keras#9385] opened 2018-02-14 01:25 UTC
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [ ] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by rfernand2** [comment] 2018-02-14 01:26
Here is a failing test case:

# model_connect.py - test out ability to connect and reuse 2 keras models
from keras.models import Model
from keras.layers import Input, LSTM, Dense
from keras.layers import Dropout, BatchNormalization, Concatenate
import numpy as np
import os

os.environ['CUDA_VISIBLE_DEVICES'] = '-1'   # force CPU (don't conflict with GPU training)
num_vocab_tokens = 6
latent_dim = 4

# create model1 (encoder)
input1 = Input(shape=( None, num_vocab_tokens,))
output1, h, c = LSTM(latent_dim, return_state=True)(input1)
model1 = Model(input1, [h, c])

# create model2 (decoder)
input2a = Input(shape=( latent_dim,))
input2b = Input(shape=( latent_dim,))
input2c = Input(shape=( None, num_vocab_tokens,))

output2 = LSTM(latent_dim, return_sequences=True)(input2c, initial_state= [input2a, input2b])
output2 = Dense(num_vocab_tokens)(output2)
model2 = Model( [input2a, input2b, input2c], output2)

# create model3 
input3a = Input(shape=( None, num_vocab_tokens))   # input to ENCODER
input3b = Input(shape=( None, num_vocab_tokens))   # teacher input to DECODER

m1_output = model1(input3a)
output3 = model2( [m1_output[0], m1_output[1], input3b] )
model3 = Model( [input3a, input3b], output3)

# predict with model3 (force the error as early as possible)
data = np.random.rand( 2, 2, num_vocab_tokens )
model3.predict( [data, data] )

**Comment by rfernand2** [comment] 2018-02-14 14:30
I should have added, while I think issuing this error for the above test case is a bug, I am really looking for a workaround to the problem.  If anyone has any ideas, I'd love to hear them.  Thanks.

**Comment by visionscaper** [comment] 2018-04-01 21:40
Hi @rfernand2, I reported a very similar issue #9084 . The bug relates to statefulness, the same issue occurs when you set `stateful=True` instantiating an RNN layer. You can work around it, I gave my solution [here](https://github.com/keras-team/keras/issues/9084#issuecomment-363094521). It is not ideal but let me know if that works out for you.

@fchollet It is really a shame that the (awesome) functional API breaks for stateful models. Unfortunately I haven't been able to find the issue, so giving this issue some love will be highly appreciated!

**Comment by nuric** [comment] 2018-04-05 15:03
The Input in the functional API always creates a placeholder at https://github.com/keras-team/keras/blob/416783156c1b07f28131c493a55a93936b5fe163/keras/engine/topology.py#L1363 As far as Keras is concerned everything clicks together; but, now when you chain models together you are expecting TensorFlow to fill one placeholder with another automatically. In reality, you are feeding values to placeholders only on the outer most model and the inner model placeholders are starved giving the error.

**Comment by visionscaper** [comment] 2018-04-05 15:32
@nuric, but how do you explain that the error only occurs for stateful submodels or submodels where you set initial state on its layers?

**Comment by nuric** [comment] 2018-04-05 16:09
Hmm, you are right, it isn't just the placeholder connections. I'm getting the same error on a RepeatVector layer only when the sequence length is unknown. It could be something about the None in the shape that is causing it. We should try the above example with fixed lengths in the model, see if the error still occurs.

**Comment by visionscaper** [comment] 2018-04-05 17:36
@nuric, I have a working gist that shows this issue where the number of samples, sequence length and feature lengths are all fixed:

https://gist.github.com/visionscaper/06a75e9066a368fc2ed01cf0c3f606da

Also see #9084 for more info.

**Comment by nuric** [comment] 2018-04-05 17:42
@visionscaper From my debugging, there is a transpose operation being done on the initial_state tensor passed in. In this case this is a Placeholder that doesn't have a value set hence it blows up. I'm getting the feeling passing Placeholder into initial_states seem to use the value before it is actually set, this is the "model_1/gru/transpose3:0" operation in my case.

**Comment by AlphaXiao** [comment] 2018-08-09 07:30
Anyone find a solution to this? or any workaround? 
I meet this problem when I combined two rnn model(one's output as another's initial state), and I also give the rnn initial state.

**Comment by ophiry** [comment] 2018-08-20 21:22
I also have a similar issue (https://github.com/keras-team/keras/issues/10074) my current workaround (which isn't very convenient) is to build a 'flat' model.
When using the functional API, most models shouldn't be hard to define as a single model.

**Comment by parap1uie-s** [comment] 2018-09-30 03:46
I also find same issue. 
If the sub-model is stateful, then crash when evaluating.

**Comment by sandroci** [comment] 2018-11-26 10:34
My workaround is to use Tensorflow directly for the stateful LSTM. If someone needs some help with the pure Tensorflow implementation of stateful LSTM's, just send me a message :-)

**Comment by codeloverdk** [comment] 2019-02-12 06:56
this problem occurs when the component model inside the combined model does not get the value of the input tensor. I solved this using the peoper index at the get_output_at(index) function. the concept of node_index from the link https://www.rdocumentation.org/packages/keras/versions/2.2.4/topics/get_input_at
solved my issue. I gave wrong index number in my case. Giving the proper index number solved my problem.

**Comment by hosse049** [comment] 2019-06-13 02:09
I was getting the same error. I realized that the issue actually comes when I try to feed a placeholder defined as an Input layer using another input layer. The issue was resolved by literally using the same Input placeholders across models instead of defining multiple of them and then connecting them.

**Comment by KCryptoExpert** [comment] 2019-08-14 00:53
@hosse049 Your suggestion worked. Thank you!

```
input_tensor = pretrained_model.input
output_from_pretrained_model = pretrained_model(input_tensor)

#my model codes follows, using input_tensor and out_from_pretrained_model
```

If you want to flatten the **predefined_model**, use

```
output_from_pretrained_model = pretrained_model.output
```

**Comment by xenore78** [comment] 2019-08-14 05:05
@hosse049 Your suggestion worked. Thank you!

```
input_tensor = pretrained_model.input
output_from_pretrained_model = pretrained_model(input_tensor)

#my model codes follows, using input_tensor and out_from_pretrained_model
```

If you want to flatten the **predefined_model**, use

```
output_from_pretrained_model = pretrained_model.output
```

**Comment by edervishaj** [comment] 2019-08-22 14:55
I am facing the same problem but in a slightly different setting. During `train_on_batch` of a dual-loss discriminator of a GAN I am trying to apply different weights to the losses depending on the input (coming either from generator or real training data). I am following @fchollet's approach in #10358 in order to achieve the dynamic loss weights during training.

The way I construct the models is as follows:
```python
generator = Sequential(...)
discriminator = Model([inputs, loss_weights, target1, target2], [output1, output2])
loss = ...
discriminator.add_loss(loss)
discriminator.compile(...)

# Combined
discriminator.trainable = False
generator_input = Input(...)
gan_loss_weights = Input(shape=(1,))
gan_target1 = Input(shape=(1,))
gan_target2 = Input(shape=(1,))

discriminator_input = generator(generator_input)
out1, out2 = discriminator([discriminator_input, gan_loss_weights, gan_target1, gan_target2])
gan = Model([generator_input, gan_loss_weights, gan_target1, gan_target2], [out1, out2])
loss = ...
gan.add_loss(loss)
gan.compile(...)
```
During training calling `train_on_batch` on discriminator with dynamic loss weights works correctly. But when called on `gan` I get the `InvalidArgumentError "You must feed a value for placeholder tensor"` for `discriminator_input`.

I tried removing the explicit `Input` layers and using `model.input` and `model.output` when calling `generator()` and `discriminator()` as suggested by @hosse049 but it did not work.

The interesting thing is that if I do not apply dynamic loss weighting, this approach for GAN works properly.

**Comment by thomasemmerich** [comment] 2019-10-09 07:11
I have the same problem as mention above. During `train_on_batch` on a GAN i get the error:  `InvalidArgumentError: You must feed a value for placeholder tensor 'ocr_input_img_1' with dtype float and shape [?,128,512,1] [[{{node ocr_input_img_1}}]]`

```
...
img = self.generator([noise, word_embedded])
ctc = self.text_recognition([img, word_sequence, word_length])
valid = self.discriminator(img)
combined = Model([noise, word_sequence, word_length], [ctc, valid]
...
```

When i only use the valid as output the code works.

**Comment by edervishaj** [comment] 2019-10-09 07:37
@thomasemmerich in my case I ended up solving the dynamic loss weighting by creating a custom loss function that takes the weight (a ```K.placeholder()```) as parameter and I update the placeholder dynamically.

**Comment by thomasemmerich** [comment] 2019-10-09 13:05
@edervishaj thank you for your answer. But i need the ctc in the custom loss. The Problem is that when i try to get the ctc the error appears.

**Comment by Huangziyi1994** [comment] 2019-10-19 01:55
I do not have this problem when using tensorflow 1.13.1. when I upgraded it to 1.14.0, this problem occurs. 

I solved this problem by using 'tf.keras.layers.Conv2D' instead of 'slim.conv2d'. So in my case, using functions all from 'tf.keras.layers' can avoid this problem. The keras version I used is: 2.3.1 and the tensorflow version is 1.14.0.

**Comment by Huangziyi1994** [comment] 2019-10-23 21:17
I solved this problem by using tensorflow 1.13.1, keras 2.3.1. I met this problem when using tf 1.14.

**Comment by thomasemmerich** [comment] 2019-11-06 09:14
I tried it with tensorflow 1.13.1 and keras 2.3.1 but it doesn't solve the problem in my case

**Comment by Huangziyi1994** [comment] 2019-11-07 18:55
The network structure I implemented is Unet with 3 decoders & encoders.

It does not work when I use conv functions from keras.layers. The layer function I used is: slim.conv2d. More details about versions: windows 10 + 2080ti + cudnn 7.4.2.24 + cuda 10.0 .

Another interesting thing is that it works for the code only based on keras.

**Closed** 2021-06-24 22:25 UTC
Labels: type:support
