### ISSUE TITLE
Add EfficientNet lite option [from tensorflow closed PR]

### ISSUE THREAD

**Issue by davinnovation** [keras-team/keras#16835] opened 2022-07-26 17:05 UTC
**System information**.

TensorFlow version (you are using): 2.9.1
Are you willing to contribute it (Yes/No) : No

**Describe the feature and the current behavior/state**.

Add EfficientNet Lite option which is PRed in [Added Lite option to EfficientNets. #48400] https://github.com/tensorflow/tensorflow/pull/48400/ already

**Will this change the current api? How?**
Yes. `tf.keras.applications.efficientnet.EfficientNetB0(lite=True)`

**Who will benefit from this feature?**
- EfficientNet Lite Users

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**

- Do you want to contribute a PR? (yes/no): no
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

**Comment by tilakrayal** [comment] 2022-07-27 09:12
@davinnovation,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by davinnovation** [comment] 2022-07-28 02:23
Hi! Thanks for your response. For clearance, efficientnet lite PR is not my credit - it was PRed by @[sebastian-sz](https://github.com/sebastian-sz) to the TensorFlow repo in 2021 Q3.
This feature is adding "lite:bool" parameter to `tf.keras.applications.efficientnet.EfficientNet` and it makes loadable TF2-TFlite ready [efficientnet-lite keras model](https://github.com/sebastian-sz/efficientnet-lite-keras). 

EfficientNet lite is in [TF-Hub](https://tfhub.dev/s?deployment-format=lite&q=efficientnet%20lite), but it is for TF1 so it can't be easily ported with TF2-TFLite

If this feature is added, lots of users can easily port efficient-lite with the latest TF2-TFLite

**Comment by sebastian-sz** [comment] 2022-07-29 13:05
@davinnovation Hi, sorry for not reopening the PR in Keras repository as promised. 

If it will be accepted I am planning to add these models to [keras-cv](https://github.com/keras-team/keras-cv) - I think this is the target place to add new vision `keras.applications`.

**Comment by gadagashwini** [comment] 2022-08-01 06:02
Hi @sebastian-sz, It would be great if you raise PR in this repo. Thank you!

**Comment by sebastian-sz** [comment] 2022-08-01 06:12
@gadagashwini in "this" repo, do you mean keras-cv or keras?

**Comment by gadagashwini** [comment] 2022-08-16 06:42
Hi @sebastian-sz, Apologies for delayed response. Please raise PR on Keras repo. Thank you!

**Comment by sebastian-sz** [comment] 2022-08-16 14:23
@gadagashwini thanks, I will try to have a PR ready by the end of the week.

**Comment by tilakrayal** [comment] 2022-11-30 14:18
@davinnovation,
Could you please take a look at the related PR's where one PR was [closed](https://github.com/keras-team/keras/pull/16905) and the other one was [merged](https://github.com/keras-team/keras-cv/pull/921). Also please take a look at this doc [link](https://paperswithcode.com/model/tf-efficientnet-lite?variant=tf-efficientnet-lite0) and let us know if it serves the purpose. Thank you!

**Comment by davinnovation** [comment] 2022-12-01 05:03
@tilakrayal Thanks for the noti. Merged PR is good enough :)

**Comment by tilakrayal** [comment] 2022-12-01 05:21
@davinnovation,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status. Thank you!

**Closed** 2022-12-01 07:05 UTC
Labels: type:feature, stat:awaiting response from contributor
