### ISSUE TITLE
ValueError: Unknown layer:name 

### ISSUE THREAD

**Issue by Aryanr64x** [keras-team/keras#11617] opened 2018-11-11 08:46 UTC
I am getting 
**ValueError: Unknown layer:name**
when I use the following code
`model = load_model('cartpole.h5')`
**_This is a bit strange as I am not using any custom objects in my model.It_** might be a bug.
The full error 
` File "E:\New folder\tensorflow\core\venv\app\deepq\main.py", line 24, in <module>
    model = load_model('cartpole.h5'')
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\engine\saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\engine\saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\engine\sequential.py", line 292, in from_config
    custom_objects=custom_objects)
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "E:\New folder\tensorflow\core\venv\lib\site-packages\keras\utils\generic_utils.py", line 165, in deserialize_keras_object
    ':' + function_name)
ValueError: Unknown layer:name`
I have keras version 2.2.2
Thanks for the feedback

**Comment by Aryanr64x** [comment] 2018-11-11 12:18
Its ok ... The Error has been fixed in  **keras 2.2.4**
Hence someone should close this issue

**Comment by palikar** [comment] 2018-11-11 23:39
I had the same issue with **keras 2.2.0**. I updated it with pip and my current version is **2.2.4** and in fact now the issue is not there.

**Comment by wt-huang** [comment] 2018-11-12 23:29
Closing as this is resolved

**Closed by wt-huang** 2018-11-12 23:29 UTC
Labels: To investigate

**Comment by suryatejabandlamudi** [comment] 2019-02-11 17:23
> Mine having the same issue...But not when loading the model but when converting the Keras model .H5 to .tflite. I've downgraded my keras(2.2.4) and TensorFlow (1.10). Still facing the same error command. Im using Ubuntu for the conversion and GPU to train my mode. Any feedback or comments would be helpful..

I'm facing the same issue . Did you Solve this @naris96 ??

**Comment by sklipnoty** [comment] 2019-02-25 12:02
File "venv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Slice

**Comment by sklipnoty** [comment] 2019-02-25 12:06
File "venv/lib/python3.6/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "venv/lib/python3.6/site-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "venv/lib/python3.6/site-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "venv/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "venv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "venv/lib/python3.6/site-packages/keras/engine/network.py", line 1022, in from_config
    process_layer(layer_data)
  File "venv/lib/python3.6/site-packages/keras/engine/network.py", line 1008, in process_layer
    custom_objects=custom_objects)
  File "venv/lib/python3.6/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "venv/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 138, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Slice

**Comment by Ffarsian** [comment] 2019-03-26 16:03
I have Keras 2.2.4 but still, I am facing the same issue, any suggestion?
Thanks

**Comment by sklipnoty** [comment] 2019-03-26 19:20
> I have Keras 2.2.4 but still, I am facing the same issue, any suggestion?
> Thanks

If I am not mistaken, I was trying to load a model with custom (Self-defined layers). You should pass these layers in the load_model call as custom objects.

**Comment by aendrs** [comment] 2019-04-05 17:29
Can someone post a working example on how to solve this issue?  I updated to Keras 2.2.4 and I'm still experiencing it.

**Comment by adamkc** [comment] 2019-05-06 20:20
I am still having this issue with Version 2.2.4.1

Maybe this issue needs to be reopened?

**Comment by adamkc** [comment] 2019-05-08 01:20
I would like to add another vote on this issue still being a problem in 2.2.4.  Has anyone found a solution?

**Comment by adamkc** [comment] 2019-05-08 19:38
For folks still struggling with this issue. I resolved it by updating CUDA (10.0) and cuDNN (7.4).

**Comment by faizaan22** [comment] 2019-07-09 04:48
You can do this -
If your custom layer's name is XYZ and I assume you have imported this XYZ layer in your project

import XYZ
# your whole code
model = load_model('model.h5', custom_objects={'XYZ' : XYZ})

**Comment by faizaan22** [comment] 2019-07-09 04:52
You can do this -
If your custom layer's name is XYZ and I assume you have imported this XYZ layer in your project

import XYZ
///your whole code///
model = load_model('model.h5', custom_objects={'XYZ' : XYZ})

**Comment by dtuggener** [comment] 2019-11-05 18:09
Thanks @faizaan22, this actually saved my problem!

**Comment by DevaDinesh21** [comment] 2020-02-05 07:08
import XYZ how to implement this ?

**Comment by dtuggener** [comment] 2020-02-05 09:01
> import XYZ how to implement this ?

@DevaDinesh21 `XYZ` in an example for a custom keras layer. E.g. I have an attention layer in a file called `attn_layer.py`. So the solution for loading my model `model.h5` that uses this layer looks like this (omitting the keras imports):

```
from attn_layer import AttentionLayer
[...]
model = load_model('model.h5', custom_objects={'AttentionLayer': AttentionLayer}))
```

**Comment by bhooshan1996** [comment] 2020-03-11 09:00
I was using conda package "keras ==2.2.3" and I was having same error for layers.
I uninstalled this package and installed latest one from PYPI "Keras == 2.3.1" using command "pip install Keras". It was solved...

**Comment by limgye77** [comment] 2020-03-14 03:23
import tensorflow.python.keras
from PIL import Image, ImageOps
import numpy as np

# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model

model = tensorflow.keras.models.load_model("C:\Projects\keras_talk\zzz\converted_keras\keras_model.h5")

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

# Replace this with the path to your image
image = Image.open("C:\Projects\keras_talk\zzz\converted_keras\test_photo.jpg")

#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)

# display the resized image
image.show()

# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)

//How can

**Comment by limgye77** [comment] 2020-03-14 03:26
import tensorflow.python.keras
from PIL import Image, ImageOps
import numpy as np

np.set_printoptions(suppress=True)

model = tensorflow.keras.models.load_model("C:\Projects\keras_talk\zzz\converted_keras\keras_model.h5")

//How can apply in this code
