### ISSUE TITLE
once gain:  tf.2.16.1 fails to recognize GPUs 

### ISSUE THREAD

**Issue by JuanVargas** [keras-team/keras#19276] opened 2024-03-09 15:17 UTC
OS = Linux Ubuntu  22.04.04 LTS
python = 3.10.12
CUDA = 12.4

According to the most recent "install instructions" I coud issue the line below in a python venv to get TF installed with GPU support

python -m pip install tensorflow**

I did that and it failed  
>> tf.__version__
'2.16.1'
>>> tf.config.list_physical_devices('GPU')
[ ]

so I created another python venv wherein I tried 

python -m pip install tensorflow[and-cuda]

that failed too, same error messages.

BTW, my system works wonderfully well with the GPUs when I use pytorch and Julia.

**Comment by SuryanarayanaY** [comment] 2024-03-11 11:25
Hi @JuanVargas ,

Have you installed Cuda driver ? Please verify and confirm the output of `nvidia-smi `command.

Verified the same on colab and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/808553205834b3043b619980c9ae3ffc/63362.ipynb) here.

Thanks!

**Comment by sampathweb** [comment] 2024-03-11 12:32
Please open this issue in TensorFlow GitHub where you might get better responses. This issue is not related to Keras.

**Comment by JuanVargas** [comment] 2024-03-11 12:41
yes, cuda driver is

NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA
Version: 12.4

**Comment by SuryanarayanaY** [comment] 2024-03-12 04:19
Hi @JuanVargas ,

There is duplicate of # [63362](https://github.com/tensorflow/tensorflow/issues/63362) on tensorflow repo for same issue.Could you please close it here and track it there.It seems the issue is related to CUDA driver compatibility which we can discuss at TF repo.

Thanks!

**Comment by JuanVargas** [comment] 2024-03-12 13:03
Done.

**Comment by mihaimaruseac** [comment] 2024-03-12 15:40
This was not closed, instead the issue on TF was closed (and reopened)

**Comment by chaudharyachint08** [comment] 2024-03-22 22:25
# Almost final and automated fix below

* Where I found the resolution
    * [TF 2.16.1 Fails to work with GPUs](https://github.com/tensorflow/tensorflow/issues/63362)
        * Solution proposed by "sh-shahrokhi", improved by "ChristofKaufmann"
        * See specially [Comment by COntributor](https://github.com/tensorflow/tensorflow/issues/63362#issuecomment-1990133275)
    * Related Issues
        * [GPU not detected on WSL2](https://github.com/tensorflow/tensorflow/issues/63341), where I have post some comments
        * [Tensorflow WSL GPU CUDA recognition issue RTX3090](https://github.com/tensorflow/tensorflow/issues/63948)
        * [Once gain: tf.2.16.1 fails to recognize GPUs](https://github.com/keras-team/keras/issues/19276)
    * Other mention on social media
        * [Reddit issue](https://www.reddit.com/r/bashonubuntuonwindows/comments/1bb0xqg/your_kernel_may_have_been_built_without_numa/)

* Exact solution
    * Temporary fix (after activating environment in which Tensorflow 2.16.1 is installed)
        <pre>
        export NVIDIA_DIR=$(dirname $(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)")))
        export LD_LIBRARY_PATH=$(echo ${NVIDIA_DIR}/*/lib/ | sed -r 's/\s+/:/g')${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
        </pre>
    * Automating the variable set/unset process with Anaconda (one-time setup)
        * Activate your environement in which TF 2.16.1 is installed
        * Two files to be created in "anaconda3/envs/<ENV_NAME>/etc/conda"
            * anaconda3/envs/<ENV_NAME>/etc/conda/activate.d/env_vars.sh
            <pre>
            #!/bin/sh
            export NVIDIA_DIR=$(dirname $(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)")))
            export LD_LIBRARY_PATH=$(echo ${NVIDIA_DIR}/*/lib/ | sed -r 's/\s+/:/g')${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
            </pre>
            * anaconda3/envs/<ENV_NAME>/etc/conda/deactivate.d/env_vars.sh
            <pre>
            #!/bin/sh
            unset NVIDIA_DIR
            unset LD_LIBRARY_PATH
            </pre>
        * Official documentation to do this via [conda.io](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux)
        * Stack-overflow question where I got this [Set environment vars when activating conda env](https://stackoverflow.com/questions/31598963/how-to-set-specific-environment-variables-when-activating-conda-environment)


* What else helped me
    * [How to list all variables names and their current values?](https://askubuntu.com/questions/275965/how-to-list-all-variables-names-and-their-current-values)
    * [Conda documenation for "env_vars.sh" for activate/deactivate](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux)

**Comment by SuryanarayanaY** [comment] 2024-04-01 07:44
Hi @JuanVargas ,

Since the issue is related to tensorflow repo which is still open there. To avoid duplicacy could you please track the issue there at TF repo and close it here. Thanks in advance.

**Closed** 2024-04-01 13:26 UTC
Labels: type:support, stat:awaiting response from contributor

**Comment by JuanVargas** [comment] 2024-04-01 13:28
done
