### ISSUE TITLE
Verbosity not functioning in Callbacks API / ModelCheckpoint

### ISSUE THREAD

**Issue by loewenm** [keras-team/keras#14591] opened 2021-04-13 19:27 UTC
Hi there - I believe this might be a bug, but it could be intentional... (would be very strange if it was intentional)

Request: Please prevent ModelCheckpoint from printing "INFO:tensorflow:Assets written to:" when verbose is set to '0'.

It appears that setting verbose = 0 when using ModelCheckpoint in the Keras Callbacks API is not working as intended (i.e. not actually preventing printing that statement).

Using the following callbacks

```
    my_callbacks = [
                    tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',
                                                    #  min_delta=0,
                                                     patience=10,
                                                     verbose=0,
                                                     mode="max",
                                                    #  baseline=None,
                                                     restore_best_weights=True),
                    tf.keras.callbacks.ModelCheckpoint(filepath=modelname,                                                        
                                                       verbose=0,
                                                       save_best_only=True),
                    tf.keras.callbacks.TensorBoard(log_dir=logdir, 
                                                   histogram_freq=1)
                    ]
```

Will result in the follow output message for every, single, epoch... even though verbose is set to '0'

```
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
INFO:tensorflow:Assets written to: ./models/20210413-192421/.h5/assets
```

**Comment by jvishnuvardhan** [comment] 2021-07-21 04:48
@loewenm Can you please share a simple standalone code to reproduce the issue?

I tried with `ModelCheckpoint` callback with `verbose=0` and I don't see the `INFO` as you mentioned. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/f26ba6386efd0294e6a0de876184da81/untitled.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment] 2021-08-05 16:25
Closing due to lack of recent activity. Please feel free to reopen when you have more information. Thanks!

**Closed by jvishnuvardhan** 2021-08-05 16:25 UTC
Labels: type:support, stat:awaiting response
