### ISSUE TITLE
ModelCheckpoint files not closed

### ISSUE THREAD

**Issue by jonasrundberg** [keras-team/keras#16964] opened 2022-08-30 12:38 UTC
**System information**.
[tf_env.txt](https://github.com/keras-team/keras/files/9452786/tf_env.txt)

- Custom code (see below)
- MacOS 12.3.1
- TensorFlow installed via pip
- TensorFlow version:  2.9.1
- Python version: 3.8.11
- GPU model and memory: 8-Core Intel Core i9, 2,3 GHz, 16 GB RAM

**Describe the problem**.
When loading weights for a model and `tf.keras.callbacks.ModelCheckpoint` to store weights after each epoch in training, the checkpoint files remains open. With many repetitions I eventually run out of resources (too many open files).
(My dataset is large and split into batches)

**Describe the current behavior**.
After training is completed (using `model.fit`) the checkpoint files is never closed.

**Describe the expected behavior**.
After `model.fit` has completed the checkpoint files is should be closed.

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**.
This snipped will write all checkpoint files stil open after `model.fit` has completed

```
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model, Sequential
import psutil

print('tf version: ', tf.version.VERSION)

def train(model, X, y):
    model_dir = './test'
    model_path = './test/cp.ckpt'
    checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(filepath=model_path, save_weights_only=True, verbose=0)
    try: 
        latest = tf.train.latest_checkpoint(model_dir)
        model.load_weights(latest)
    except AttributeError:
        print('First run -not reading checkpoint')
    history = model.fit(X, y, batch_size=32, epochs=10, verbose=0, callbacks=[checkpoint_callback])


X = pd.DataFrame([1],[2],[3])
y = pd.DataFrame([1],[2],[3])
model = Sequential(
    [
        Input(shape=(1,)),
        Dense(1)
    ]
)
model.compile(loss='binary_crossentropy', metrics=['accuracy'])

for _ in range(5):
    history = train(model, X, y)

print('Open files:')
proc = psutil.Process()
for file in proc.open_files():
    print(file[0])

```

**Output**.
```
Open files:
/test/cp.ckpt.index
/test/cp.ckpt.data-00000-of-00001
/test/cp.ckpt.index
/test/cp.ckpt.data-00000-of-00001
/test/cp.ckpt.index
/test/cp.ckpt.data-00000-of-00001
/test/cp.ckpt.index
/test/cp.ckpt.data-00000-of-00001
/test/cp.ckpt.index
/test/cp.ckpt.data-00000-of-00001

```

**Comment by sushreebarsa** [comment] 2022-09-01 15:42
@gadagashwini I was able to reproduce the issue in TF2.9. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/90182373a0f116882ce5dad3bc7fb2c6/untitled111.ipynb) here. Thank you!

**Comment by gadagashwini** [comment] 2022-09-05 09:59
Hi @jonasrundberg,  To close the ModelCheckpoint file, workaround is, use `shutil.rmtree`
to delete the directory. 
`shutil.rmtree(path, onerror = handler)`
Thank you!

**Comment by jonasrundberg** [comment] 2022-09-07 20:49
Not sure how that would help? It would either remove the checkpoints that I need when iterating over a large dataset.

**Comment by hertschuh** [comment] 2022-10-14 16:21
@jonasrundberg 
After a bit of investigation, it turns out that the open files come from `model.load_weights(latest)` and not `ModelCheckpoint`.

I'll keep investigating why this happens.

**Comment by hertschuh** [comment] 2022-10-27 19:12
@jonasrundberg 
So what is happening is that `model.load_weights` keeps some object around, which is then not deleted. Only once the model itself is deleted are all the files closed. This leak is an actual bug and we're working on it.

I'm not sure what your workflow is that you keep loading the model. But here's a workaround for now:

```python
status = model.load_weights(latest)
del status._checkpoint.reader
```

**Comment by jonasrundberg** [comment] 2022-12-09 09:46
Thanks!

**Comment by hertschuh** [comment] 2023-01-12 19:08
@jonasrundberg ,

This bug is now fixed (by this commit https://github.com/tensorflow/tensorflow/commit/d34f9176f2424e6424e2debbe97b2b198cd37bcf ).
The fix will be part of the next Tensorflow release (2.12), but you can already get by installing TF nightly `pip install tf-nightly`.

Thanks

**Closed by hertschuh** 2023-01-12 19:08 UTC
Labels: type:support
