### ISSUE TITLE
TorchModuleWrapper and mixed precision

### ISSUE THREAD

**Issue by dmus** [keras-team/keras#18650] opened 2023-10-19 10:19 UTC
It looks like TorchModuleWrapper and setting mixed precision via keras do not work together. See

```
import os
os.environ['KERAS_BACKEND'] = 'torch'

import numpy as np
from monai.networks.nets import SwinUNETR
import keras_core as keras


if __name__ == '__main__':
    keras.mixed_precision.set_global_policy('mixed_float16')
    input_shape = (2, 96, 96, 96)
    inputs = keras.layers.Input(shape=input_shape)
    net = SwinUNETR(img_size=(96,96,96), in_channels=2, out_channels=1, feature_size=48)
    x = keras.layers.TorchModuleWrapper(net)(inputs)
    # x = keras.layers.Conv3D(filters=1, kernel_size=(1, 1, 1))(inputs)
    outputs = keras.layers.Activation('linear', dtype='float32')(x)

    model = keras.models.Model(inputs=inputs, outputs=outputs)

    my_input = np.random.rand(4, 2, 96, 96, 96)
    prediction = model(my_input)

    model.summary()

```

This results in 

> RuntimeError: Exception encountered when calling TorchModuleWrapper.call().
> 
> Could not automatically infer the output shape / dtype of 'torch_module_wrapper' (of type TorchModuleWrapper). Either the `TorchModuleWrapper.call()` method is incorrect, or you need to implement the `TorchModuleWrapper.compute_output_spec() / compute_output_shape()` method. Error encountered:
> 
> Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
> 
> Arguments received by TorchModuleWrapper.call():
>   • args=('<KerasTensor shape=(None, 2, 96, 96, 96), dtype=float16, sparse=None, name=keras_tensor>',)
>   • kwargs=<class 'inspect._empty'>

**Comment by haifeng-jin** [comment] 2023-12-07 19:20
Hi @dmus , Thanks for the issue!
It seems it is more of an issue of the `TorchModuleWrapper` or the `SwinUENTR` itself.
It fails with or without the mixed precision setting.

Do you have a code snippet using the `SwinUENTR` just with torch?
I am having trouble running it even without Keras.

**Comment by haifeng-jin** [comment] 2024-04-11 23:15
Closing since unable to reproduce the error.
Feel free to reopen if anyone finds the bug still exists.

**Closed by haifeng-jin** 2024-04-11 23:15 UTC
