### ISSUE TITLE
VAE example code unrecognized arguments error

### ISSUE THREAD

**Issue by the-kiki** [keras-team/keras#12028] opened 2019-01-11 23:43 UTC
I am getting an unrecognized arguments error at args = parser.parse_args():
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    help_ = "Load h5 model trained weights"
    parser.add_argument("-w", "--weights", help=help_)
    help_ = "Use mse loss instead of binary cross entropy (default)"
    parser.add_argument("-m",
                        "--mse",
                        help=help_, action='store_true')
    **args = parser.parse_args()**

usage: ipykernel_launcher.py [-h] [-w WEIGHTS] [-m]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\ralan\AppData\Roaming\jupyter\runtime\kernel-902d569d-b446-4f8e-a967-53f845ae989c.json

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\ralan\Anaconda3\envs\tensorflow-gpu\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
In [2]:

%tb

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-1-435875ea2bc1> in <module>()
    169                         "--mse",
    170                         help=help_, action='store_true')
--> 171     args = parser.parse_args()
    172     models = (encoder, decoder)
    173     data = (x_test, y_test)

~\Anaconda3\envs\tensorflow-gpu\lib\argparse.py in parse_args(self, args, namespace)
   1731         if argv:
   1732             msg = _('unrecognized arguments: %s')
-> 1733             self.error(msg % ' '.join(argv))
   1734         return args
   1735 

~\Anaconda3\envs\tensorflow-gpu\lib\argparse.py in error(self, message)
   2387         self.print_usage(_sys.stderr)
   2388         args = {'prog': self.prog, 'message': message}
-> 2389         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

~\Anaconda3\envs\tensorflow-gpu\lib\argparse.py in exit(self, status, message)
   2374         if message:
   2375             self._print_message(message, _sys.stderr)
-> 2376         _sys.exit(status)
   2377 
   2378     def error(self, message):

SystemExit: 2
[Keras VAE GitHub Example Code.docx](https://github.com/keras-team/keras/files/2751464/Keras.VAE.GitHub.Example.Code.docx)

Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [ x] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ x] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

**Comment by jvishnuvardhan** [comment] 2019-06-03 21:25
Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-06-18 22:19
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2019-06-18 22:19 UTC
Labels: backend:tensorflow, stat:awaiting response, type:support
