### ISSUE TITLE
   rv = reductor(4) TypeError: can't pickle module objects

### ISSUE THREAD

**Issue by ianferreira** [keras-team/keras#11856] opened 2018-12-12 04:36 UTC
Seems to be an issue serializing a model returned from 
tensorflow-gpu==1.11.0
keras==2.2.4

from keras.utils.training_utils import multi_gpu_model
..
..

gpu_model = multi_gpu_model(model,gpus=2)
gpu_model.compile(loss="binary_crossentropy", optimizer=opt,metrics=["accuracy"])
..
..
fit
..

print("[INFO] serializing model...")
gpu_model.save(config.MODEL_PATH, overwrite=True)

[INFO] serializing model...
Traceback (most recent call last):
  File "train_alexnet.py", line 70, in <module>
    gpu_model.save(config.MODEL_PATH, overwrite=True)
  File "C:\Users\ianfe\Envs\dl4cv\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Users\ianfe\Envs\dl4cv\lib\site-packages\keras\engine\saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "C:\Users\ianfe\Envs\dl4cv\lib\site-packages\keras\engine\saving.py", line 83, in _serialize_model
    model_config['config'] = model.get_config()
  File "C:\Users\ianfe\Envs\dl4cv\lib\site-packages\keras\engine\network.py", line 931, in get_config
    return copy.deepcopy(config)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "C:\Users\ianfe\Envs\dl4cv\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects

**Comment by ymodak** [comment] 2018-12-12 17:58
Probably a duplicate of #8123 , #8446 .

**Comment by harshini-gadige** [comment] 2018-12-17 17:33
Closing this as it is in "awaiting response" status for more than 3 days. Feel free to add your comments and we will reopen.

**Closed by harshini-gadige** 2018-12-17 17:33 UTC
Labels: stat:awaiting response
