### ISSUE TITLE
Issue with input_shape

### ISSUE THREAD

**Issue by shubhamsakhuja** [keras-team/keras#14586] opened 2021-04-09 09:40 UTC
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers import Input, Dense, Embedding, SpatialDropout1D, add, concatenate, Conv1D
from keras.callbacks import ModelCheckpoint, EarlyStopping

model = Sequential()
model.add(SpatialDropout1D(0.2))
model.add(Conv1D(60,32, strides=1, activation='relu',padding='causal',input_shape=(None, 20055)))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2, return_sequences=True))
model.add(Dense(13, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

epochs = 5
batch_size = 64

history = model.fit(text_bow_train, y_train, epochs=epochs, batch_size=batch_size,callbacks=[EarlyStopping(monitor='val_loss', patience=3, min_delta=0.0001)])

Error 

ValueError: in user code:

    G:\Installations\lib\site-packages\tensorflow\python\keras\engine\training.py:806 train_function  *
        return step_function(self, iterator)
    G:\Installations\lib\site-packages\tensorflow\python\keras\engine\training.py:796 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    G:\Installations\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1211 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    G:\Installations\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2585 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    G:\Installations\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2945 _call_for_each_replica
        return fn(*args, **kwargs)
    G:\Installations\lib\site-packages\tensorflow\python\keras\engine\training.py:789 run_step  **
        outputs = model.train_step(data)
    G:\Installations\lib\site-packages\tensorflow\python\keras\engine\training.py:747 train_step
        y_pred = self(x, training=True)
    G:\Installations\lib\site-packages\tensorflow\python\keras\engine\base_layer.py:975 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs,
    G:\Installations\lib\site-packages\tensorflow\python\keras\engine\input_spec.py:176 assert_input_compatibility
        raise ValueError('Input ' + str(input_index) + ' of layer ' +

    ValueError: Input 0 of layer sequential_32 is incompatible with the layer: expected ndim=3, found ndim=2. Full shape received: [None, 20055]

**Comment by bguetarni** [comment] 2021-04-11 20:17
```
Input shape:
3D tensor with shape: (samples, timesteps, channels)
```
According to the keras documentation, SpatialDropout1D can only be applied to 3-dimensional vectors (see [doc](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SpatialDropout1D)). However, it seems that the input is a 2-diensional vector of shape `(None,20055)`.

If you specify your intentions maybe we can help you.

**Comment by jvishnuvardhan** [comment] 2021-07-16 17:41
@bguetarni Thanks for the answer. @shubhamsakhuja Did you update your `input_shape` based on the suggestion? 
If this is still an issue, please share a standalone code (with a data) to reproduce the issue. Thanks!

**Comment by jvishnuvardhan** [comment] 2021-07-27 07:40
Closing due to lack of recent activity. I am assuming the issue was resolved. If not, please feel free to reopen the issue. Thanks!

**Closed by jvishnuvardhan** 2021-07-27 07:40 UTC
Labels: stat:awaiting response, type:support
