### ISSUE TITLE
Cannot load model from Json or from Yaml. I get the error: AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by CostasMalonas** [keras-team/keras#14294] opened 2020-12-08 15:15 UTC
When I try to load my model from Json or from I get the following error:
AttributeError: 'str' object has no attribute 'decode'

#CODE OF MY MODEL:

print('Build model...')
main_input = Input(shape=(maxlen, num_features), name='main_input')

l1 = LSTM(100, implementation=2, kernel_initializer='glorot_uniform', return_sequences=True, dropout=0.2)(main_input) # the shared layer

b1 = BatchNormalization()(l1)

l2_1 = LSTM(100, implementation=2, kernel_initializer='glorot_uniform', return_sequences=False, dropout=0.2)(b1) # the layer specialized in activity prediction

b2_1 = BatchNormalization()(l2_1)

l2_2 = LSTM(100, implementation=2, kernel_initializer='glorot_uniform', return_sequences=False, dropout=0.2)(b1) # the layer specialized in time prediction

b2_2 = BatchNormalization()(l2_2)
act_output = Dense(len(target_chars), activation='softmax', kernel_initializer='glorot_uniform', name='act_output')(b2_1)

time_output = Dense(1, kernel_initializer='glorot_uniform', name='time_output')(b2_2)

model = Model(inputs=[main_input], outputs=[act_output, time_output])

opt = Nadam(lr=0.002, beta_1=0.9, beta_2=0.999, epsilon=1e-08, schedule_decay=0.004, clipvalue=3)

model.compile(loss={'act_output':'mae', 'time_output':'mae'}, optimizer=opt)
early_stopping = EarlyStopping(monitor='val_loss', patience=42)

lr_reducer = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, verbose=0, mode='auto', min_delta=0.0001, cooldown=0, min_lr=0)

#SAVE MODEL
model_json = model.to_json()
with open('C:/Users/path_to_json/model.json', "w") as json_file:
    json_file.write(model_json)
model.save_weights("C:/Users/path_to_json/model_json_1.h5")
print("Saved model to disk")

#CODE FOR LOADING:

json_file = open('C:/Users/path_to_json/model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights("C:/Users/path_to_json/model_json_1.h5")
print("Loaded model from disk")

When I try to execute the command:

loaded_model.load_weights("C:/Users/path_to_json/model_json_1.h5")

I get the error:

AttributeError: 'str' object has no attribute 'decode'

**Comment by daniloguimaraes71** [comment] 2020-12-14 07:49
I reproduced it and it worked fine for me. The only difference is that the argument min_delta in ReduceLROnPlateau was giving me the issue

TypeError: __init__() got an unexpected keyword argument 'min_delta'

so I deleted it:

lr_reducer = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=10, verbose=0, mode='auto', cooldown=0, min_lr=0)

my python and keras versions:

Python 3.5.2
Keras                2.1.2
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
keras-segmentation   0.2.0
keras-utils          1.0.13
tensorboard          1.14.0
tensorflow-estimator 1.14.0
tensorflow-gpu       1.14.0

My imports and variables:

from keras.models import Model, model_from_json
from keras.layers import LSTM, BatchNormalization, Dense, Input
from keras.optimizers import Nadam
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
#CODE OF MY MODEL:

maxlen = 10
num_features = 5
target_chars = ['a','b']

Can you try reproducing it?

**Comment by yozhikoff** [comment] 2021-02-10 11:08
Try downdrading the `h5py` package to `2.10.0`.
More details [here](https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi)

**Comment by sushreebarsa** [comment] 2021-07-29 14:12
@CostasMalonas Could you please try as per the above comment and let us know if this issue still persists? Thanks!

**Comment by sushreebarsa** [comment] 2021-08-03 07:00
Closing this issue due to lack of recent activity .Please feel free to reopen if you still have concern.Thanks!

**Closed by sushreebarsa** 2021-08-03 07:00 UTC
Labels: stat:awaiting response, type:support
