### ISSUE TITLE
Jit_compile = True, does not work with mirrored strategy on multiple gpus. what's the alternative?

### ISSUE THREAD

**Issue by keertika-11** [keras-team/keras#18145] opened 2023-05-21 10:27 UTC
**System information**.
- TensorFlow version (use command below): 2.10
- Python version: 3.9
- GPU model and memory: A100 

**Describe the problem**.

`jit_comile=ture ` does not work on multiple gpus with mirrored strategy

**Source code / logs**.
```
import tensorflow as tf
import tensorflow_hub as hub
import os
import numpy as np
from glob import glob
import random
import matplotlib.pyplot as plt
import pandas as pd
import os
import yaml
import time


stream = open("params.yaml")
print(stream)
gen = yaml.load(stream, Loader=yaml.FullLoader)
print(gen["params"])
params = gen["params"]

# os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"
# os.environ["CUDA_VISIBLE_DEVICES"]="0,1,2,3"
# tf.debugging.set_log_device_placement(True)

gpus = tf.config.list_physical_devices('GPU')
# gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
strategy = tf.distribute.MirroredStrategy(['GPU:0','GPU:1','GPU:2','GPU:3','GPU:4','GPU:5','GPU:6','GPU:7'])
train_dir = params['train_dir']
val_dir = params["val_dir"]
train_batch_size = params["train_batch_size"]
BATCH_SIZE_PER_REPLICA = 4
global_batch_size = (BATCH_SIZE_PER_REPLICA *
                    strategy.num_replicas_in_sync)

val_batch_size = params["val_batch_size"]

EPOCHS = params["EPOCHS"]
WARMUP_STEPS = params["WARMUP_STEPS"]
INIT_LR = params["INIT_LR"]
WAMRUP_LR = params["WAMRUP_LR"]

# print("Number of Accelerators: ", strategy.num_replicas_in_sync)
class WarmUpCosine(tf.keras.optimizers.schedules.LearningRateSchedule):
    def __init__(
        self, learning_rate_base=0.03, total_steps=13000, warmup_learning_rate=0.006, warmup_steps=10
    ):
        super(WarmUpCosine, self).__init__()

        self.learning_rate_base = learning_rate_base
        self.total_steps = total_steps
        self.warmup_learning_rate = warmup_learning_rate
        self.warmup_steps = warmup_steps
        self.pi = tf.constant(np.pi)

    def __call__(self, step):
        if self.total_steps < self.warmup_steps:
            raise ValueError("Total_steps must be larger or equal to warmup_steps.")
        learning_rate = (
            0.5
            * self.learning_rate_base
            * (
                1
                + tf.cos(
                    self.pi
                    * (tf.cast(step, tf.float32) - self.warmup_steps)
                    / float(self.total_steps - self.warmup_steps)
                )
            )
        )

        if self.warmup_steps > 0:
            if self.learning_rate_base < self.warmup_learning_rate:
                raise ValueError(
                    "Learning_rate_base must be larger or equal to "
                    "warmup_learning_rate."
                )
            slope = (
                self.learning_rate_base - self.warmup_learning_rate
            ) / self.warmup_steps
            warmup_rate = slope * tf.cast(step, tf.float32) + self.warmup_learning_rate
            learning_rate = tf.where(
                step < self.warmup_steps, warmup_rate, learning_rate
            )
        return tf.where(
            step > self.total_steps, 0.0, learning_rate, name="learning_rate"
        )
    def get_config(self):
        config = {
            'warmup_steps': self.warmup_steps,
            'total_steps': self.total_steps}
        return config


def dataset(path, batch_size):

    def configure_for_performance(dataset, batch_size):
        """
        examples.prefetch(2) will prefetch two elements (2 examples),
        while examples.batch(20).prefetch(2) will prefetch 2 elements
        (2 batches, of 20 examples each)

        train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
        """
        # dataset = dataset.shuffle(buffer_size=1025)
        # dataset = dataset.cache('/tmp/dump.tfcache_eff')
        # dataset = dataset.repeat()
        dataset = dataset.batch(batch_size)
        dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
        # dataset = strategy.experimental_distribute_dataset(dataset)
        return dataset

    def read_filename(filename):
        # tf.py_function(tf.print, inp=[filename], Tout=[])
        image = tf.io.read_file(filename)
        image = tf.io.decode_jpeg(image, channels=3)
        # image = tf.image.random_flip_up_down(image)
        image = tf.image.resize(image, [224, 224])
        return image

    def custom_tf_dataset(path, batch_size):
        classes = os.listdir(path)
        num_classes = len(classes)
        print("number of classes are", num_classes)
        filenames = glob(path + '/*/*')
        num_examples = len(filenames)
        print("number of examples are", num_examples)
        random.shuffle(filenames)
        labels = [classes.index(name.split('/')[-2]) for name in filenames]
        # labels = tf.one_hot(labels, len(classes))
        labels = tf.data.Dataset.from_tensor_slices(labels)
        image_data = tf.data.Dataset.from_tensor_slices(filenames)
        image_data = image_data.map(read_filename)
        options = tf.data.Options()
        options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
        image_data = image_data.with_options(options)
        image_label_dataset = tf.data.Dataset.zip((image_data, labels))
        image_label_dataset = configure_for_performance(image_label_dataset, batch_size)
        return image_label_dataset, num_classes, num_examples

    return custom_tf_dataset(path, batch_size)

train_ds, num_train_class, num_train_examples = dataset(train_dir,global_batch_size)
train_ds = strategy.experimental_distribute_dataset(train_ds)
val_ds, num_val_class, num_val_examples = dataset(val_dir, val_batch_size)
val_ds = strategy.experimental_distribute_dataset(val_ds)
TOTAL_STEPS = int((num_train_examples / train_batch_size) * EPOCHS)



def load_model(model_path, num_classes: int):
    inputs = tf.keras.Input((224, 224, 3))
    if model_path.startswith("https:"):
        print("Loading from TF-hub")
        norm_layer = tf.keras.layers.Rescaling(scale=1.0 / 127.5, offset=-1)(inputs)
        hub_module = hub.KerasLayer(model_path, trainable=True)
        x = hub_module(norm_layer, training=True)
    else:
        print("Retraining the model")
        model = tf.keras.models.load_model(model_path, custom_objects={"WarmUpCosine": WarmUpCosine})
        model = tf.keras.Model(inputs=model.input, outputs=model.get_layer('keras_layer').output)
        x = model.output 
    # dropout = tf.keras.layers.Dropout(0.2)(x)
    if num_classes > 1:
        outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)
    else:
        outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    if model_path.startswith("https:"):

        model = tf.keras.Model(inputs, outputs)
    else:
        model = tf.keras.Model(inputs=model.input,outputs=outputs)
    return model
        
scheduled_lrs = WarmUpCosine(
    learning_rate_base=INIT_LR,
    total_steps=TOTAL_STEPS,
    warmup_learning_rate=WAMRUP_LR,
    warmup_steps=WARMUP_STEPS,
)



lrs = [scheduled_lrs(step) for step in range(TOTAL_STEPS)]
plt.figure(figsize=(10, 6))
plt.plot(lrs)
plt.xlabel("Step", fontsize=14)
plt.ylabel("LR", fontsize=14)
plt.savefig("learning_rate.png")



with strategy.scope():
    model = load_model('https://tfhub.dev/sayakpaul/vit_l16_fe/1',params["classes"])
    optimizer = tf.keras.optimizers.SGD(scheduled_lrs)
    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(reduction=tf.keras.losses.Reduction.NONE)
    train_loss = tf.keras.metrics.Mean()
    train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()
    model.compile(loss=loss_fn, optimizer=optimizer, metrics=["accuracy"],jit_compile=True) 
    print("model compiled")
    # tf.get_logger().setLevel(tf.compat.v1.logging.DEBUG)
    # model.compile(loss=loss_fn, optimizer=optimizer, metrics=["accuracy"],jit_compile=True)
    # model.summary()

callback = tf.keras.callbacks.ModelCheckpoint(params["save_model"] + '_{epoch:02d}-{val_loss:5f}', save_best_only=False, monitor='val_loss', mode='min')
history = model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS,steps_per_epoch=num_train_examples/train_batch_size,validation_steps=num_val_examples,callbacks=[callback])
model.save(params["save_model"])
    # result = pd.DataFrame(history.history)
    # fig, ax = plt.subplots(2, 1, figsize=(10, 10))
    # result[["accuracy", "val_accuracy"]].plot(xlabel="epoch", ylabel="score", ax=ax[0])
    # result[["loss", "val_loss"]].plot(xlabel="epoch", ylabel="score", ax=ax[1])

```

Error:
The training starts and ends in the middle of the first epoch with this error
`
terminate called after throwing an instance of 'std::system_error' terminate called recursively terminate called recursively`

**Comment by keertika-11** [comment] 2023-05-22 18:11
> @keertika-11, While executing the mentioned code, I was facing the indentation error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c21f66b20648e0cb4bc84adb16287010/untitled1168.ipynb). And also when you use predict() it triggers a bunch of validations and data conversions, for example your random_inputs was converted to an iterable first, called data adapter object, see:
> 
> https://github.com/keras-team/keras/blob/302b8da880d5589a4e206d61b97f1c6b848d751b/keras/engine/data_adapter.py#L220
> 
> I expect some speed-up if you use tf.data in predict like this:
> 
> ```
> tf.keras.backend.clear_session()
> 
> mobilenet = tf.keras.applications.MobileNetV3Large()
> mobilenet.compile(jit_compile=True)
> random_inputs = tf.data.Dataset.from_tensor_slices(tf.random.normal((10, 224, 224, 3))).batch(10)
> 
> # Warm-up
> _ = mobilenet.predict(random_inputs)
> print("XLA:", timeit.timeit(
>     lambda: mobilenet.predict(random_inputs, verbose=0),
>     number=10)
> ```
> 
> ) #17187
> 
> Thank you!

hey, thanks for the reply. but i am not using predict() anywhere in the code.

**Comment by keertika-11** [comment] 2023-05-22 18:13
> > @keertika-11, While executing the mentioned code, I was facing the indentation error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c21f66b20648e0cb4bc84adb16287010/untitled1168.ipynb). And also when you use predict() it triggers a bunch of validations and data conversions, for example your random_inputs was converted to an iterable first, called data adapter object, see:
> > https://github.com/keras-team/keras/blob/302b8da880d5589a4e206d61b97f1c6b848d751b/keras/engine/data_adapter.py#L220
> > 
> > I expect some speed-up if you use tf.data in predict like this:
> > ```
> > tf.keras.backend.clear_session()
> > 
> > mobilenet = tf.keras.applications.MobileNetV3Large()
> > mobilenet.compile(jit_compile=True)
> > random_inputs = tf.data.Dataset.from_tensor_slices(tf.random.normal((10, 224, 224, 3))).batch(10)
> > 
> > # Warm-up
> > _ = mobilenet.predict(random_inputs)
> > print("XLA:", timeit.timeit(
> >     lambda: mobilenet.predict(random_inputs, verbose=0),
> >     number=10)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ) #17187
> > Thank you!
> 
> hey, thanks for the reply. but i am not using predict() anywhere in the code.

This code works perfectly without mirrored strategy but only uses one gpu
, the only issue is it does not work with mirrored strategy

**Comment by Frightera** [comment] 2023-05-22 21:40
@keertika-11 Can you share the whole traceback? 

Also can you confirm it works using `jit_compile=False` with multiple GPUs?

**Comment by keertika-11** [comment] 2023-05-23 04:57
> @keertika-11 Can you share the whole traceback?
> 
> Also can you confirm it works using `jit_compile=False` with multiple GPUs?

Yes, it works using jit_compile=False, but takes 12 hours for 1 epoch on 8 GPUs but with `jit_compile=True` and no mirrored strategy one epoch completes in 18 minutes but only one 1 gpu

```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)
```
![jit_compile](https://github.com/keras-team/keras/assets/75610397/e5c37ec2-7735-4ac8-a01f-e0deb85fdd51)

**Comment by Frightera** [comment] 2023-05-23 08:29
This error indicates memory leak (most of the times) but I couldn't see an obvious issue with the code. Can you provide a reproducible example?

**Comment by keertika-11** [comment] 2023-05-28 11:34
```
import tensorflow as tf
import tensorflow_hub as hub
import os
import numpy as np
from glob import glob
import random
import matplotlib.pyplot as plt
import pandas as pd
import os
import time


gpus = tf.config.list_physical_devices('GPU')
# gpus = tf.config.experimental.list_physical_devices('GPU')
print(gpus)
strategy = tf.distribute.MirroredStrategy(['GPU:4','GPU:5','GPU:6','GPU:7'])
train_dir = "flowers_ds/train/"
val_dir = "flowers_ds/validation/" 
train_batch_size = 8


val_batch_size = 1

EPOCHS = 2
WARMUP_STEPS = 10
INIT_LR = 0.003
WAMRUP_LR = 0.0002

# print("Number of Accelerators: ", strategy.num_replicas_in_sync)
class WarmUpCosine(tf.keras.optimizers.schedules.LearningRateSchedule):
    def __init__(
        self, learning_rate_base=0.03, total_steps=13000, warmup_learning_rate=0.006, warmup_steps=10
    ):
        super(WarmUpCosine, self).__init__()

        self.learning_rate_base = learning_rate_base
        self.total_steps = total_steps
        self.warmup_learning_rate = warmup_learning_rate
        self.warmup_steps = warmup_steps
        self.pi = tf.constant(np.pi)

    def __call__(self, step):
        if self.total_steps < self.warmup_steps:
            raise ValueError("Total_steps must be larger or equal to warmup_steps.")
        learning_rate = (
            0.5
            * self.learning_rate_base
            * (
                1
                + tf.cos(
                    self.pi
                    * (tf.cast(step, tf.float32) - self.warmup_steps)
                    / float(self.total_steps - self.warmup_steps)
                )
            )
        )

        if self.warmup_steps > 0:
            if self.learning_rate_base < self.warmup_learning_rate:
                raise ValueError(
                    "Learning_rate_base must be larger or equal to "
                    "warmup_learning_rate."
                )
            slope = (
                self.learning_rate_base - self.warmup_learning_rate
            ) / self.warmup_steps
            warmup_rate = slope * tf.cast(step, tf.float32) + self.warmup_learning_rate
            learning_rate = tf.where(
                step < self.warmup_steps, warmup_rate, learning_rate
            )
        return tf.where(
            step > self.total_steps, 0.0, learning_rate, name="learning_rate"
        )
    def get_config(self):
        config = {
            'warmup_steps': self.warmup_steps,
            'total_steps': self.total_steps}
        return config


def dataset(path, batch_size):

    def configure_for_performance(dataset, batch_size):
        """
        examples.prefetch(2) will prefetch two elements (2 examples),
        while examples.batch(20).prefetch(2) will prefetch 2 elements
        (2 batches, of 20 examples each)

        train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
        """
        # dataset = dataset.shuffle(buffer_size=1025)
        # dataset = dataset.cache('/tmp/dump.tfcache_eff')
        # dataset = dataset.repeat()
        dataset = dataset.batch(batch_size)
        dataset = dataset.prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
        # dataset = strategy.experimental_distribute_dataset(dataset)
        return dataset

    def read_filename(filename):
        # tf.py_function(tf.print, inp=[filename], Tout=[])
        image = tf.io.read_file(filename)
        image = tf.io.decode_jpeg(image, channels=3)
        # image = tf.image.random_flip_up_down(image)
        image = tf.image.resize(image, [224, 224])
        return image

    def custom_tf_dataset(path, batch_size):
        classes = os.listdir(path)
        num_classes = len(classes)
        print("number of classes are", num_classes)
        filenames = glob(path + '/*/*')
        num_examples = len(filenames)
        print("number of examples are", num_examples)
        random.shuffle(filenames)
        labels = [classes.index(name.split('/')[-2]) for name in filenames]
        # labels = tf.one_hot(labels, len(classes))
        labels = tf.data.Dataset.from_tensor_slices(labels)
        image_data = tf.data.Dataset.from_tensor_slices(filenames)
        image_data = image_data.map(read_filename)
        options = tf.data.Options()
        options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.OFF
        image_data = image_data.with_options(options)
        image_label_dataset = tf.data.Dataset.zip((image_data, labels))
        image_label_dataset = configure_for_performance(image_label_dataset, batch_size)
        return image_label_dataset, num_classes, num_examples

    return custom_tf_dataset(path, batch_size)

train_ds, num_train_class, num_train_examples = dataset(train_dir,train_batch_size)
train_ds = strategy.experimental_distribute_dataset(train_ds)
val_ds, num_val_class, num_val_examples = dataset(val_dir, val_batch_size)
val_ds = strategy.experimental_distribute_dataset(val_ds)
TOTAL_STEPS = int((num_train_examples / train_batch_size) * EPOCHS)



def load_model(model_path, num_classes: int):
    inputs = tf.keras.Input((224, 224, 3))
    if model_path.startswith("https:"):
        print("Loading from TF-hub")
        norm_layer = tf.keras.layers.Rescaling(scale=1.0 / 127.5, offset=-1)(inputs)
        hub_module = hub.KerasLayer(model_path, trainable=True)
        x = hub_module(norm_layer, training=True)
    else:
        print("Retraining the model")
        model = tf.keras.models.load_model(model_path, custom_objects={"WarmUpCosine": WarmUpCosine})
        model = tf.keras.Model(inputs=model.input, outputs=model.get_layer('keras_layer').output)
        x = model.output 
    # dropout = tf.keras.layers.Dropout(0.2)(x)
    if num_classes > 1:
        outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)
    else:
        outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
    if model_path.startswith("https:"):

        model = tf.keras.Model(inputs, outputs)
    else:
        model = tf.keras.Model(inputs=model.input,outputs=outputs)
    return model
        
scheduled_lrs = WarmUpCosine(
    learning_rate_base=INIT_LR,
    total_steps=TOTAL_STEPS,
    warmup_learning_rate=WAMRUP_LR,
    warmup_steps=WARMUP_STEPS,
)



lrs = [scheduled_lrs(step) for step in range(TOTAL_STEPS)]
plt.figure(figsize=(10, 6))
plt.plot(lrs)
plt.xlabel("Step", fontsize=14)
plt.ylabel("LR", fontsize=14)
plt.savefig("learning_rate.png")



with strategy.scope():
    model = load_model('https://tfhub.dev/sayakpaul/vit_l16_fe/1',num_train_class)
    optimizer = tf.keras.optimizers.SGD(scheduled_lrs)
    loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(reduction=tf.keras.losses.Reduction.NONE)
    train_loss = tf.keras.metrics.Mean()
    train_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()
    model.compile(loss=loss_fn, optimizer=optimizer, metrics=["accuracy"],jit_compile=False) 
    print("model compiled")
    # tf.get_logger().setLevel(tf.compat.v1.logging.DEBUG)
    # model.compile(loss=loss_fn, optimizer=optimizer, metrics=["accuracy"],jit_compile=True)
    # model.summary()

callback = tf.keras.callbacks.ModelCheckpoint("flowers_test"+ '_{epoch:02d}-{val_loss:5f}', save_best_only=False, monitor='val_loss', mode='min')
history = model.fit(train_ds, validation_data=val_ds, epochs=EPOCHS,steps_per_epoch=num_train_examples/train_batch_size,validation_steps=num_val_examples,callbacks=[callback])
model.save("flowers_test")
[flowers_ds_25mb.zip](https://github.com/keras-team/keras/files/11584388/flowers_ds_25mb.zip)

```

**Comment by Frightera** [comment] 2023-06-03 20:06
@keertika-11 Sorry for the delay.

This looks like a memory leak when `jit_compile=True` with MirroredStrategy. As far as I traced, gradient updates probably causing this, I'll work on a fix in the upcoming days.

**Comment by qlzh727** [comment] 2023-06-08 00:03
Thanks @Frightera, I will close this issue for Keras, since it is related to distribute and XLA. We can track it in  https://github.com/tensorflow/tensorflow/issues/56423.

Feel free to reopen this issue if there is anything related to Keras need to be addressed.

**Closed by qlzh727** 2023-06-08 00:03 UTC
Labels: type:bug/performance, keras-team-review-pending
