### ISSUE TITLE
Broken Docs

### ISSUE THREAD

**Issue by Tejaswgupta** [keras-team/keras#13784] opened 2020-02-16 07:42 UTC
I was going through the docs in 
> examples/README.md

and many of the links there are broken which would cause problem to the people are new and don't know about the scripts.

I would like to help on this :))

**Comment by Saduf2019** [comment] 2021-07-05 11:06
@Tejaswgupta 
Moving this to closed status as the issue is resolved.

**Closed by Saduf2019** 2021-07-05 11:06 UTC
Labels: type:docs
