### ISSUE TITLE
"classes" not working on flow_from_dataframe 

### ISSUE THREAD

**Issue by ymodak** [keras-team/keras#15206] opened 2021-08-19 20:08 UTC
```python
from tensorflow import keras
from tensorflow.keras.preprocessing import image
import pandas as pd

gen = image.ImageDataGenerator()

f = gen.flow_from_directory('data', classes=['A', 'B'])
print(f.class_indices)
f = gen.flow_from_directory('data', classes=['B', 'A'])
print(f.class_indices)

# with "data/A.jpg" and "data/B.jpg" on disk
df = pd.DataFrame([['A','data/A.jpg',],['B','data/B.jpg']], columns=['class','filename'])
print(df)
f = gen.flow_from_dataframe(df, classes=['A', 'B'])
print(f.class_indices)
f = gen.flow_from_dataframe(df, classes=['B', 'A'])
print(f.class_indices)

----------
Found 0 images belonging to 2 classes.
{'A': 0, 'B': 1}
Found 0 images belonging to 2 classes.
{'B': 0, 'A': 1}
  class    filename
0     A  data/A.jpg
1     B  data/B.jpg
Found 0 validated image filenames belonging to 2 classes.
{'A': 0, 'B': 1}
Found 0 validated image filenames belonging to 2 classes.
{'A': 0, 'B': 1}  # expected {'B': 0, 'A': 1}
/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/dataframe_iterator.py:282: UserWarning: Found 2 invalid image filename(s) in x_col="filename". These filename(s) will be ignored.
  .format(n_invalid, x_col)
/usr/local/lib/python3.7/dist-packages/keras_preprocessing/image/dataframe_iterator.py:282: UserWarning: Found 2 invalid image filename(s) in x_col="filename". These filename(s) will be ignored.
  .format(n_invalid, x_col)
```
related issue #https://github.com/keras-team/keras/issues/13637
TensorFlow version - 2.6.0
Keras Version - 2.6.0
Keras-Preprocessing Version - 1.1.2

**Comment by kurchi1205** [comment] 2021-08-20 11:01
I am a first time contributer . Can I work on this issue?

**Comment by kurchi1205** [comment] 2021-08-20 11:02
Also it will be helpful if you could tell wht is the expected output .

**Comment by tilakrayal** [comment] 2021-08-24 12:10
@jvishnuvardhan ,
I was able to reproduce the issue tf v2.5, v2.6 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/89c05883c44906cdf514cdefea6ce074/untitled59.ipynb).

**Comment by ymodak** [comment] 2021-12-20 22:16
This is fixed in master [branch code base](https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/dataframe_iterator.py#L255-L265) but the fix is not part of Keras-Preprocessing 1.1.2

**Comment by gery9999** [comment] 2022-02-28 13:03
Hi, I encounter a similar problem when working with flow_from_dataframe in class_mode='sparse'.

**Documentation (http://49.235.228.196/keras/api/preprocessing/image.html#flowfromdataframe-method) says that one should use a list of integers as label input in sparse mode (see doc: "sparse": 1D numpy array of integer labels). However, if I plug in integer labels I get `TypeError: If class_mode="sparse", y_col="Label" column values must be strings.`** Not sure if documentation should be updated or if it is a bug in the code.

Not a big issue using string labels instead - unless you have more than 10 classes! Then, the class_indices become shifted from the integer label due to that sorting strings differs from sorting integers. i.e. I get the class_indices as follows
 `datagen = tf.keras.preprocessing.image.ImageDataGenerator(
            rescale=1./255
        )
 dataset = datagen.flow_from_dataframe(
    df,
    x_col = "PathToImage",
    y_col = "Label", #string values
    target_size = (80,80),
    batch_size=32,
    class_mode="sparse")
dataset.class_indices`
OUTPUT
`{'0': 0,
 '1': 1,
 '10': 2,
 '11': 3,
 '2': 4,
 '3': 5,
 '4': 6,
 '5': 7,
 '6': 8,
 '7': 9,
 '8': 10,
 '9': 11}`
 
 Next, I tried to work around this issue by using the classes input:
 `datagen = tf.keras.preprocessing.image.ImageDataGenerator(
            rescale=1./255
        )
 dataset = datagen.flow_from_dataframe(
    df,
    x_col = "PathToImage",
    y_col = "Label", #string values
    target_size = (80,80),
    batch_size=32,
    class_mode="sparse",
    classes = ['0','1','2','3','4','5','6','7','8','9','10','11'])`
The shifted labels remain.
 
Reading the above discussion, it seems like the at least the classes issue should be fixed (at least for class_mode='categorical'). Will this fix be in the next Keras-Preprocessing version? When will that go live? As seen above it would be nice to work with integer labels in the sparse case. Will this be considered for the next version too?

TensorFlow version - 2.6.0
Keras Version - 2.6.0
Keras-Preprocessing Version - 1.1.2

**Comment by mattdangerw** [comment] 2022-04-27 18:38
The fix is now on keras nightly https://github.com/keras-team/keras/blob/master/keras/preprocessing/image.py#L962, and will be in stable keras in 2.9.0 (within a few weeks).

Note that keras-preprocessing as a standalone repository/pip is now deprecated. All functionality has been moved into the main keras repo.

**Closed by mattdangerw** 2022-04-27 18:38 UTC
Labels: type:bug/performance
