### ISSUE TITLE
Modifying a model from a callback is different between jax and other backends.

### ISSUE THREAD

**Issue by albertaillet** [keras-team/keras#19054] opened 2024-01-12 18:17 UTC
### Problem

Difference between `jax` backend and the other backends when modifying the model from a callback.
The model does not get updated when using `jax` as backend while it does when using `torch` or `tensorflow`.

### How to reproduce

keras version: 3.0.2

```python
import keras


class WeightChangeCallback(keras.callbacks.Callback):
    def __init__(self, change: float):
        super().__init__()
        self.change = change

    def on_train_batch_end(self, epoch: int, logs):
        for weight in self.model.weights:
            weight.assign(self.change * weight)


model = keras.Sequential([
    keras.Input(shape=(1,)),
    keras.layers.Dense(1, kernel_initializer="ones", use_bias=False),
])


def loss(y_true, y_pred):
    """Return 0, but connected to the input of the computational graph to make it work with PyTorch."""
    return 0 * keras.ops.sum(y_pred)


change = 0.5
x = keras.ops.ones((1, 1))
y = keras.ops.ones((1, 1))

model.compile(loss=loss, optimizer="sgd", jit_compile=False, run_eagerly=True)
model.fit(x, y, epochs=1, callbacks=[WeightChangeCallback(change)])

weight = model.weights[0].numpy()[0, 0]
assert keras.ops.isclose(weight, change), f"Weight should be {change}, but is {weight}"
```

This code snipped does not raise an `AssertionError` with the `torch` backend but does when using `jax`. This persits 
for both `run_eagerly=False` and `run_eagerly=True` and both `jit_compile=True` and `jit_compile=False`.

### Is there a recommended way?

In case this is an expected behaviour, what is the recommended way to modify the model from a callback when using jax?

**Comment by SuryanarayanaY** [comment] 2024-01-16 17:42
Hi @albertaillet ,

I have replicated the reported behaviour with jax. Tensorflow and torch have same behaviour which is different to jax. [Gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/2b6ead7e83ad26e112e96d0190e49b55/19054.ipynb)

AFAIK, the behaviour should be same for all backends. Need to dig more and come back. Thanks!

**Comment by fchollet** [comment] 2024-02-01 19:39
The nature of the issue is that, since JAX is stateless, the model state is detached from the model in `fit()`. It gets reattached at the epoch boundary, so that epoch-level callbacks (like `ModelCheckpoint`) work fine. However in your case you are trying to modify a variable at the batch boundary, which won't work.

We cannot by default reattach the state at the batch boundary because that would create significant performance overhead. I will work on a workaround.

**Comment by fchollet** [comment] 2024-02-01 21:59
This is now fixed at HEAD. Note that updating state at the batch boundary like this will force a state sync, which may cause performance overhead.

**Closed by fchollet** 2024-02-01 21:59 UTC
Labels: To investigate, backend:jax
