### ISSUE TITLE
Performance issue on Macbook Pro M1

### ISSUE THREAD

**Issue by OriAlpha** [keras-team/keras#15003] opened 2021-07-26 07:33 UTC
**System information**
- Script can be found below
- MacBook Pro M1 (Mac OS Big Sir (11.5))
- TensorFlow installed from (source)
- TensorFlow version (2.5 version) with Metal Support
- Python version: 3.9
- GPU model and memory: MacBook Pro M1 and 16 GB

Steps needed for installing Tensorflow with metal support.
https://developer.apple.com/metal/tensorflow-plugin/

I am trying to train a model on Macbook Pro M1, but the performance is so bad and the train doesn't work properly. It takes a ridiculously long time just for a single epoch. 

Code needed for reproducing this behavior.

```
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.layers import Embedding, Dense, LSTM
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Model configuration
additional_metrics = ['accuracy']
batch_size = 128
embedding_output_dims = 15
loss_function = BinaryCrossentropy()
max_sequence_length = 300
num_distinct_words = 5000
number_of_epochs = 5
optimizer = Adam()
validation_split = 0.20
verbosity_mode = 1

# Disable eager execution
tf.compat.v1.disable_eager_execution()

# Load dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=num_distinct_words)
print(x_train.shape)
print(x_test.shape)

# Pad all sequences
padded_inputs = pad_sequences(x_train, maxlen=max_sequence_length, value = 0.0) # 0.0 because it corresponds with <PAD>
padded_inputs_test = pad_sequences(x_test, maxlen=max_sequence_length, value = 0.0) # 0.0 because it corresponds with <PAD>

# Define the Keras model
model = Sequential()
model.add(Embedding(num_distinct_words, embedding_output_dims, input_length=max_sequence_length))
model.add(LSTM(10))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=optimizer, loss=loss_function, metrics=additional_metrics)

# Give a summary
model.summary()

# Train the model
history = model.fit(padded_inputs, y_train, batch_size=batch_size, epochs=number_of_epochs, verbose=verbosity_mode, validation_split=validation_split)

# Test the model after training
test_results = model.evaluate(padded_inputs_test, y_test, verbose=False)
print(f'Test results - Loss: {test_results[0]} - Accuracy: {100*test_results[1]}%')
```

I have noticed this same problem with LSTM layers

**Comment by jvishnuvardhan** [comment] 2021-07-26 17:44
Duplicate of #https://github.com/keras-team/keras/issues/14967

**Comment by OriAlpha** [comment] 2021-07-26 17:46
I wouldn't consider this as duplicate, because I could run the code of https://github.com/keras-team/keras/issues/14967 faster than LSTM.

**Comment by jvishnuvardhan** [comment] 2021-07-26 21:01
@OriAlpha I ran your code in colab and I see the runtime as shown below. What is the runtime with `M1`. 

```
Epoch 1/5
20000/20000 [==============================] - ETA: 0s - loss: 0.5699 - accuracy: 0.7099/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/training.py:2426: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
20000/20000 [==============================] - 19s 936us/sample - loss: 0.5699 - accuracy: 0.7099 - val_loss: 0.4316 - val_accuracy: 0.8064
Epoch 2/5
20000/20000 [==============================] - 18s 901us/sample - loss: 0.3450 - accuracy: 0.8649 - val_loss: 0.3272 - val_accuracy: 0.8642
Epoch 3/5
20000/20000 [==============================] - 18s 899us/sample - loss: 0.2563 - accuracy: 0.9035 - val_loss: 0.3063 - val_accuracy: 0.8728
Epoch 4/5
20000/20000 [==============================] - 18s 908us/sample - loss: 0.2189 - accuracy: 0.9219 - val_loss: 0.3067 - val_accuracy: 0.8702
Epoch 5/5
20000/20000 [==============================] - 18s 895us/sample - loss: 0.1934 - accuracy: 0.9332 - val_loss: 0.3149 - val_accuracy: 0.8702
Test results - Loss: 0.3238884867286682 - Accuracy: 86.74399852752686%
```

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/4e9d3d229c552957b4cec017e1b48010/untitled1013.ipynb).

I think this is more related to `M1` than `TF` as it was running in 18s each epoch on a `cpu`. I also ran it on my Mac and see similar results. Thanks!

**Comment by OriAlpha** [comment] 2021-07-26 22:14
I tried for few hours, due to slow training I only trained for 1 epochs, this is a log 
```
Epoch 1/1
20000/20000 [==============================] - loss: 0.5489 - accuracy: 0.6923
--- 6894.8485770225524902 seconds ---
```

Just for one epoch, it takes around 2 hours that's a nightmare

**Comment by jvishnuvardhan** [comment] 2021-07-26 22:21
@OriAlpha Thanks for quick response with test results. 
I don't have access to `M1` but will check with other team members. Thanks

**Comment by OriAlpha** [comment] 2021-07-26 22:23
You can use this link for GPU support for m1 mac. Steps needed for installing Tensorflow with metal support.
https://developer.apple.com/metal/tensorflow-plugin/

**Comment by tomerk** [comment] 2021-07-29 17:37
Unfortunately no one on our team has an M1 macbook to test this with. We suggest asking on the apple developer forum:
https://developer.apple.com/forums/tags/tensorflow-metal

I also notice you're disabling eager execution (`tf.compat.v1.disable_eager_execution()`), which means you're actually running legacy no-longer-maintained/supported codepaths. It's possible the tensorflow metal plugin was only designed to work well with TF2 / eager execution (though I can't say for sure)

**Comment by OriAlpha** [comment] 2021-07-30 08:26
Oh really, its bad news hope its fixed in future release

**Comment by jvishnuvardhan** [comment] 2021-08-19 05:40
@OriAlpha As mentioned above this is more related to M1 than TensorFlow. I think it is better to post it in apple developer forum or Stackoverflow.

I am closing this issue. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2021-08-19 05:40 UTC
Labels: type:bug/performance, stat:awaiting response
