### ISSUE TITLE
Dense Layer: Different inference results with different BS

### ISSUE THREAD

**Issue by gombru** [keras-team/keras#16615] opened 2022-05-27 10:54 UTC
I've seen that I get different results out of a Dense layer during inference with batched inference vs single inference. As in this simple example:

```
model = tf.keras.layers.Dense(8, activation="relu")
x = tf.ones((128, 8))
x_single = tf.ones((1, 8))
y = model(x)
y_single = model(x_single)

np.testing.assert_almost_equal(y[0,:].numpy(), y_single[0,:].numpy(), 8)
```
[Colab reproducing error](https://colab.research.google.com/drive/12yjxNyiOr-Mmg5Ir69Tt6UvQ3xYWMYSp?usp=sharing).

In some runs the outputs do not match.

- The difference gets substantially amplified when inputs are high precison floats.
- The difference seems to vanish when comparing bigger BS: i.e. BS 16 and BS 128 get the same results.

This is tested with Keras 2.8.0

**Comment by tilakrayal** [comment] 2022-05-30 10:52
@gadagashwini,
I was able to reproduce the issue in tf [v2.8](https://colab.research.google.com/gist/tilakrayal/76f8a4e117415cf762b341f7b8c0b644/2-8-16615.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/dd00057005555a6deec9a6a32374f318/2_9_16615.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/5d1e8c5cd6304a0030eaa212d2328f63/2_10_16615.ipynb). Kindly find the gist of it here.

**Comment by qlzh727** [comment] 2022-06-08 19:36
Note that the numerical difference threshold TF/Keras usually use is 1e-6, which is larger than the current difference. The difference is  caused by lower level ops and hardward. You might see bigger difference if you try to run it on GPU. 

I am going to close this issue since this is working as intended, and we don't have anything need to address here.

**Closed by qlzh727** 2022-06-08 19:36 UTC
Labels: type:bug/performance, keras-team-review-pending
