### ISSUE TITLE
AttributeError: 'gevent._local.local' object has no attribute 'value'

### ISSUE THREAD

**Issue by bharat-patidar** [keras-team/keras#13346] opened 2019-09-19 19:59 UTC
Hi,

I have a Sequential model which was running perfectly fine till last week.
I recently updated keras to 2.3.0 and when I try to run model.predict command on my trained model it throws error:
```

Traceback (most recent call last):
 File "/opt/program/predictor.py", line 69, in predict
    a=model.predict(x_input, verbose=0)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1456, in predict
    self._make_predict_function()
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 378, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/network.py", line 323, in __setattr__
    super(Network, self).__setattr__(name, value)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 1215, in __setattr__
    if not _DISABLE_TRACKING.value:
  File "src/gevent/local.py", line 408, in gevent._local.local.__getattribute__

AttributeError: 'gevent._local.local' object has no attribute 'value'
```
**It got resolved when I switched keras back to 2.2.5**

**Comment by fchollet** [comment] 2019-09-24 20:25
You can also install Keras from the `master` branch on GitHub which has a fix for this issue.

**Closed by fchollet** 2019-09-24 20:25 UTC

**Comment by v123582** [comment] 2019-11-30 15:33
Hi, @fchollet. The problem is occurred when I use this master branch. Is it fix ?

**Comment by vonmike** [comment] 2020-03-18 12:39
Same error with keras==2.3.1

**Comment by brett--anderson** [comment] 2020-04-19 02:34
I used the master branch as well, the problem is still there. This is a major issue when trying to use Keras in a Flask app that used gevent, as documented all over the net. Please fix this problem.

**Comment by brett--anderson** [comment] 2020-04-20 00:12
I set the following value before loading the model, using keras 2.3.1, and it solved the problem for me:
```
            import keras.backend.tensorflow_backend as tb
            tb._SYMBOLIC_SCOPE.value = True 
```
Without this code and just using the master branch as suggested did not solve the problem for me.
