### ISSUE TITLE
load_model - the two structures don't have the same nested structure

### ISSUE THREAD

**Issue by eyalshafran** [keras-team/keras#14345] opened 2021-01-04 20:47 UTC
I trained a model and saved it using:
`model.save("model_name") `
I then call
`model = tf.keras.models.load_model("model_name")`
and get a "**The two structures don't have the same nested structure.**" error. The structure that the model is expecting upon loading is not what I defined in the model.

My model:
```
roberta_layer = TFRobertaModel.from_pretrained('roberta-base')

ids = tf.keras.layers.Input((64,), dtype=tf.int32)
att = tf.keras.layers.Input((64,), dtype=tf.int32)

roberta_inputs = [ids, att]

sequence_output,pooled_output = roberta_layer(roberta_inputs)

# unigram
x1 = tf.keras.layers.Conv1D(32,1,activation='relu')(sequence_output)
x1 = tf.keras.layers.GlobalMaxPool1D()(x1)

# bigram
x2 = tf.keras.layers.Conv1D(32,2,activation='relu')(sequence_output)
x2 = tf.keras.layers.GlobalMaxPool1D()(x2)

# trigram
x3 = tf.keras.layers.Conv1D(32,3,activation='relu')(sequence_output)
x3 = tf.keras.layers.GlobalMaxPool1D()(x3)

concat = tf.keras.layers.Concatenate()([x1,x2,x3])
concat = tf.keras.layers.Dropout(0.5)(concat)

outputs = tf.keras.layers.Dense(11, activation='sigmoid')(concat)

model = tf.keras.Model(inputs=roberta_inputs, outputs=outputs)
```
I'm using tf 2.4.0
and transformers 3.5.1

The full error is:
The two structures don't have the same nested structure.

First structure: type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='inputs/input_ids')}

Second structure: type=list str=[TensorSpec(shape=(None, 64), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 64), dtype=tf.int32, name='inputs/1')]

More specifically: The two namedtuples don't have the same sequence type. First structure type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='inputs/input_ids')} has type dict, while second structure type=list str=[TensorSpec(shape=(None, 64), dtype=tf.int32, name='inputs/0'), TensorSpec(shape=(None, 64), dtype=tf.int32, name='inputs/1')] has type list

During handling of the above exception, another exception occurred:

**Comment by wildangunawan** [comment] 2021-01-28 03:55
I'm having the same issue with TF 2.4.1 and Transformers 4.2.2.

First structure also have shape=(None, 5) while second structure is shape=(None, maximum length of a sequence).

**Comment by tarrade** [comment] 2021-05-07 07:54
Same issue with TF 2.5.0-rc3 and Transformer 4.5.1. 

Using out of the box Bert classifier:
`model = TFBertForSequenceClassification.from_pretrained(bert-base-multilingual-uncased',num_labels=2)`
then traning the model and then trying to save it give me the same error
```
TypeError: The two structures don't have the same nested structure.

First structure: type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}

Second structure: type=list str=[TensorSpec(shape=(None, 128), dtype=tf.int32, name='input_ids/0')]
```
saving the mode .hd5 results in the error we reloading the model:
`model.save('bert_input.hd5')`

**Comment by tarrade** [comment] 2021-05-07 20:09
Same issue with `tensorflow 2.5.0-rc3`
Using Huggingface save/load is working fine
```
model.save_pretrained('bert_input')
 reconstructed_model = TFBertForSequenceClassification.from_pretrained('bert_input')
```

But this is not weI need for tf.serving.

It seems some class/function definition are not saved with the model so reloading the model will not work. Maybe there are some paramters to set to have this working ? ([Stackoverflow](https://stackoverflow.com/questions/67391794/saved-model-after-reloading-with-tf-keras-models-load-model-request-different-in))

**Comment by chenlongzhen** [comment] 2021-05-08 05:46
Same issue

**Comment by samsatp** [comment] 2021-08-12 10:17
Same issue with transformers 4.6.1 and tensorflow 2.4.1 

I built the model as the following. 
```
Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_4 (InputLayer)            [(None, 512)]        0                                            
__________________________________________________________________________________________________
input_3 (InputLayer)            [(None, 512)]        0                                            
__________________________________________________________________________________________________
tf_distil_bert_model_1 (TFDisti TFBaseModelOutput(la 66362880    input_4[0][0]                    
                                                                 input_3[0][0]                    
__________________________________________________________________________________________________
bidirectional_1 (Bidirectional) (None, 128)          320256      tf_distil_bert_model_1[1][7]     
__________________________________________________________________________________________________
dense_2 (Dense)                 (None, 16)           2064        bidirectional_1[0][0]            
__________________________________________________________________________________________________
dropout_58 (Dropout)            (None, 16)           0           dense_2[0][0]                    
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 10)           170         dropout_58[0][0]                 
==================================================================================================
Total params: 66,685,370
Trainable params: 322,490
Non-trainable params: 66,362,880
__________________________________________________________________________________________________
```
Then, it's trained and save as SavedModel. But when load it back, it's an error.
```
The two structures don't have the same nested structure.

First structure: type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}

Second structure: type=dict str={'input_ids': TensorSpec(shape=(None, 512), dtype=tf.int32, name='input_ids/input_ids'), 'attention_mask': TensorSpec(shape=(None, 512), dtype=tf.int32, name='input_ids/attention_mask')}

More specifically: The two dictionaries don't have the same set of keys. First structure has keys type=list str=['input_ids'], while second structure has keys type=list str=['input_ids', 'attention_mask']
Entire first structure:
{'input_ids': .}
Entire second structure:
{'input_ids': ., 'attention_mask': .}
```

**Comment by jvishnuvardhan** [comment] 2021-09-21 22:57
@eyalshafran Can you share a simple standalone code to reproduce the issue? Did you try recent TF/Keras versions? Thanks!

**Comment by GiovanniGedosal** [comment] 2021-10-03 06:23
Same issue

**Comment by Kdev369** [comment] 2021-10-03 10:29
I am also facing the same issue
![image](https://user-images.githubusercontent.com/82885255/135749607-87bf9987-d4c9-49e6-84d1-897d72fd9eb8.png)

and after applying saved_model instead of save.... again this error appeared 
tf.saved_model.save(intent_model,'/content/model')

![image](https://user-images.githubusercontent.com/82885255/135749630-9e377181-fcaf-48a3-81fb-f3e72a139c80.png)

Do tell me about this if someone has solved this issue.

**Comment by jvishnuvardhan** [comment] 2021-10-05 17:57
Is it possible for anyone of you to share a simple standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2021-10-06 19:13
@Nash2325138 I am facing different error. Can you please check this [gist](https://colab.research.google.com/gist/jvishnuvardhan/4073e69e08dd8ad2c4e603e27ff0fc71/untitled.ipynb) and let us know what version you are using. Thanks!

**Comment by Nash2325138** [comment] 2021-10-07 08:22
Update: if I change
```
sequence_output,pooled_output = roberta_layer(roberta_inputs)
```
to 
```
sequence_output,pooled_output = roberta_layer.roberta(roberta_inputs)
```
as @eyalshafran suggested, the problem is magically solved.
I wonder what's the cause

**Comment by shreyas-jk** [comment] 2021-11-24 11:21
Even I am facing the same issue.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-3a1d333d606b> in <module>()
----> 1 ner_model_2 = pickle.load(open('ner_model_2.pkl', 'rb'))

2 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py in assert_same_structure(nest1, nest2, check_types, expand_composites)
    533                   "Entire first structure:\n%s\n"
    534                   "Entire second structure:\n%s"
--> 535                   % (str(e), str1, str2))
    536 
    537 

ValueError: The two structures don't have the same nested structure.

First structure: type=tuple str=(({'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}, None, None, None, None, None, None, None, None, None, None, None, None, False), {})

Second structure: type=tuple str=((TensorSpec(shape=(None, 384), dtype=tf.int32, name='input_ids'), TensorSpec(shape=(None, 384), dtype=tf.int32, name='attention_mask'), TensorSpec(shape=(None, 384), dtype=tf.int32, name='token_type_ids'), None, None, None, None, None, None, None, None, None, None, False), {})

More specifically: Substructure "type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}" is a sequence, while substructure "type=TensorSpec str=TensorSpec(shape=(None, 384), dtype=tf.int32, name='input_ids')" is not
Entire first structure:
(({'input_ids': .}, ., ., ., ., ., ., ., ., ., ., ., ., .), {})
Entire second structure:
((., ., ., ., ., ., ., ., ., ., ., ., ., .), {})
```

**Comment by shreyas-jk** [comment] 2021-11-26 13:57
> Even I am facing the same issue.
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-10-3a1d333d606b> in <module>()
> ----> 1 ner_model_2 = pickle.load(open('ner_model_2.pkl', 'rb'))
> 
> 2 frames
> /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py in assert_same_structure(nest1, nest2, check_types, expand_composites)
>     533                   "Entire first structure:\n%s\n"
>     534                   "Entire second structure:\n%s"
> --> 535                   % (str(e), str1, str2))
>     536 
>     537 
> 
> ValueError: The two structures don't have the same nested structure.
> 
> First structure: type=tuple str=(({'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}, None, None, None, None, None, None, None, None, None, None, None, None, False), {})
> 
> Second structure: type=tuple str=((TensorSpec(shape=(None, 384), dtype=tf.int32, name='input_ids'), TensorSpec(shape=(None, 384), dtype=tf.int32, name='attention_mask'), TensorSpec(shape=(None, 384), dtype=tf.int32, name='token_type_ids'), None, None, None, None, None, None, None, None, None, None, False), {})
> 
> More specifically: Substructure "type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}" is a sequence, while substructure "type=TensorSpec str=TensorSpec(shape=(None, 384), dtype=tf.int32, name='input_ids')" is not
> Entire first structure:
> (({'input_ids': .}, ., ., ., ., ., ., ., ., ., ., ., ., .), {})
> Entire second structure:
> ((., ., ., ., ., ., ., ., ., ., ., ., ., .), {})
> ```

I have figured out a way to overcome this problem. Instead of saving the model using `model.save` or `tf.keras.models.save_model()`, try saving the model weights using `model.save_weights('model_weight.h5')` during the training process.

At the prediction or testing phase, you need to create the model (architecture) manually, the same way you did in the training phase, and then load the weights to it.

**Comment by Allen-Qiu** [comment] 2021-12-04 04:05
Yes, model.save_weights('model_weight.h5') is a right way.
My model contains a bert huggingface bert. This model cannot be saved by model.save.
However, I can save weights.
When I try to restore the model. I first build the model again and then load the weights.
I successfully restore the model.

**Comment by Allen-Qiu** [comment] 2021-12-04 04:37
Yes, as introduced by shreyas-jk,  model.save_weights('model_weight.h5') can deal with this problem.
My model contains a huggingface bert. It cannot be saved.
However, I can save the weights. Subsequently, I build the model again in other files and load the weights.

**Comment by dschwalm** [comment] 2022-01-05 07:43
Same issue.
tf 2.7.0
transformers 4.14.1
pretrained model: bert-base-cased

**Comment by jungohyoon-29cm** [comment] 2022-01-12 19:19
tensorflow 2.7.0
keras 2.7.0
transformers 4.15.0
pretrained model: "bert-base-multilingual-cased"

I also had the same issue when using `model.save()` & `keras.model.load_model()`.
but, I change my python code to `model.save_weights()` & `model.load_weights()`, this issue resolved.
thanks to @Allen-Qiu & @shreyas-jk

**Comment by yoonnoon** [comment] 2022-01-12 19:25
tensorflow 2.7.0
keras 2.7.0
transformers 4.15.0
pretrained model: "bert-base-multilingual-cased"

I also had the same issue when using model.save() & keras.model.load_model().
but, I change my python code to model.save_weights() & model.load_weights(), this issue resolved.
thanks to @Allen-Qiu  & @shreyas-jk

**Comment by christophmeyer** [comment] 2022-05-05 13:42
In case this is still relevant for people, here is what I think is going on:

Keras saves the input specs on the first call of the model [here](https://github.com/tensorflow/tensorflow/blob/8b54374d803496667b1cc3d9dfcfa3bd8861581b/tensorflow/python/keras/engine/base_layer.py#L3013). When loading a pretrained model with transformers using the `from_pretrained` class classmethod of `TFPretrainedModel`, the networks is first fed dummy inputs [here](https://github.com/huggingface/transformers/blob/99289c08a1b16a805dd4ee46de029e9fd23cba3d/src/transformers/modeling_tf_utils.py#L1803). So the saved models expect their input tensors to be of sequence length 5, because that is the length of the dummy inputs.

In order to change that behaviour, you can reset the input specs before saving to a saved model like this:

```
# This is just a toy example of an input with sequence length 8 (as opposed to 5), just use a dictionary of your actual features instead. 
features = {"input_ids": tf.constant([[1,2,3,4,5,6,7,8]]), "attention_mask": tf.constant([[1,1,1,1,1,1,1,1]]), "token_type_ids": tf.constant([[0,0,0,0,0,0,0,0]])}

model._saved_model_inputs_spec = None
model._set_save_spec(features)

tf.saved_model.save(model, "./out_dir")
```

**Comment by gowthamkpr** [comment] 2022-05-17 17:10
@eyalshafran @yoonnoon @dschwalm @Allen-Qiu @shreyas-jk  Can you please try the above proposed [solution](https://github.com/keras-team/keras/issues/14345#issuecomment-1118569356) and let me know if it works. Thanks!

**Comment by YanlongLai** [comment] 2022-05-17 22:05
> 

It is not working for me. The first structure is still fixed on 5 
```First structure: type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids')}

Second structure: type=dict str={'attention_mask': TensorSpec(shape=(None, 32), dtype=tf.int32, name='inputs/attention_mask'), 'input_ids': TensorSpec(shape=(None, 32), dtype=tf.int32, name='inputs/input_ids')}```

**Comment by Mohamed-Aziz-Ben-Nessir** [comment] 2022-05-28 15:07
tf.saved_model.load() instead of tf.keras.models.load_model() on Kaggle TPUs did the job for me.

**Comment by gowthamkpr** [comment] 2022-06-04 23:16
@eyalshafran I tried to replicate this issue with transformers 4.11.3 and tensorflow 2.8.2 and running into a different error. Here's the [gist](https://colab.research.google.com/gist/gowthamkpr/88ddf4a8d4af70546e3fc9ed77ba5156/untitled363.ipynb). Also as mentioned [above](https://github.com/keras-team/keras/issues/14345#issuecomment-1140280521) can you please use `tf.saved_model.load()` instead of `tf.keras.models.load_model()` . Thanks!

**Closed** 2022-06-19 00:44 UTC
Labels: type:bug/performance, stat:awaiting response, stalled

**Comment by MrKZZ** [comment] 2022-08-03 06:53
> > Even I am facing the same issue.
> > ```
> > ---------------------------------------------------------------------------
> > ValueError                                Traceback (most recent call last)
> > <ipython-input-10-3a1d333d606b> in <module>()
> > ----> 1 ner_model_2 = pickle.load(open('ner_model_2.pkl', 'rb'))
> > 
> > 2 frames
> > /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/nest.py in assert_same_structure(nest1, nest2, check_types, expand_composites)
> >     533                   "Entire first structure:\n%s\n"
> >     534                   "Entire second structure:\n%s"
> > --> 535                   % (str(e), str1, str2))
> >     536 
> >     537 
> > 
> > ValueError: The two structures don't have the same nested structure.
> > 
> > First structure: type=tuple str=(({'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}, None, None, None, None, None, None, None, None, None, None, None, None, False), {})
> > 
> > Second structure: type=tuple str=((TensorSpec(shape=(None, 384), dtype=tf.int32, name='input_ids'), TensorSpec(shape=(None, 384), dtype=tf.int32, name='attention_mask'), TensorSpec(shape=(None, 384), dtype=tf.int32, name='token_type_ids'), None, None, None, None, None, None, None, None, None, None, False), {})
> > 
> > More specifically: Substructure "type=dict str={'input_ids': TensorSpec(shape=(None, 5), dtype=tf.int32, name='input_ids/input_ids')}" is a sequence, while substructure "type=TensorSpec str=TensorSpec(shape=(None, 384), dtype=tf.int32, name='input_ids')" is not
> > Entire first structure:
> > (({'input_ids': .}, ., ., ., ., ., ., ., ., ., ., ., ., .), {})
> > Entire second structure:
> > ((., ., ., ., ., ., ., ., ., ., ., ., ., .), {})
> > ```
> 
> I have figured out a way to overcome this problem. Instead of saving the model using `model.save` or `tf.keras.models.save_model()`, try saving the model weights using `model.save_weights('model_weight.h5')` during the training process.
> 
> At the prediction or testing phase, you need to create the model (architecture) manually, the same way you did in the training phase, and then load the weights to it.

I try your mention, save_weights, create the model, and load_weights, but get this error:

ValueError: Unable to load weights saved in HDF5 format into a subclassed Model which has not created its variables yet. Call the Model first, then load the weights.

Similar, I build my model using transformers. In init function, I build a albert and load weight by from_pretrained()
