### ISSUE TITLE
predict next value lstm abnormal

### ISSUE THREAD

**Issue by Lay4U** [keras-team/keras#12810] opened 2019-05-11 08:06 UTC
here is my model
```
model = Sequential()
model.add(LSTM(256, input_shape=(None, 1),return_sequences=True))
model.add(Dropout(0.3))

model.add(LSTM(256, input_shape=(None, 1)))
model.add(Dropout(0.3))


model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])


model.summary()
model.fit(x_train, y_train, epochs=10, batch_size=32, verbose=2, validation_data=(x_val, y_val))
```

and I want to know next time series So, I did

![a busy cat](https://imgur.com/hVB2NBH.png)

```y_test[-1]``` and  predicted ```lastY``` gap is too large

am I wrong? or something error code?

I do not know why this happened. The difference between the last value and the next predicted value is very large.

https://gist.github.com/Lay4U/e1fc7d036356575f4d0799cdcebed90e is full source code

**Comment by jvishnuvardhan** [comment] 2019-05-12 05:08
Please fill the issue template [here](https://github.com/keras-team/keras/issues/new/choose). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-21 05:15
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Closed by jvishnuvardhan** 2019-05-21 05:15 UTC
Labels: stat:awaiting response, type:support
