### ISSUE TITLE
Error with the example BinaryCrossentropy : InvalidArgumentError: Invalid reduction dimension (-1 for input with 0 dimension(s)

### ISSUE THREAD

**Issue by AlexandreBourrieau** [keras-team/keras#15120] opened 2021-08-06 14:29 UTC
Hello,

When I try the example given at : [keras doc](https://keras.io/api/losses/probabilistic_losses/#binarycrossentropy-class)

```
y_true = [0, 1, 0, 0]
y_pred = [-18.6, 0.51, 2.94, -12.8]
bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
bce(y_true, y_pred).numpy()
```

I got the following error 

`InvalidArgumentError: Invalid reduction dimension (-1 for input with 0 dimension(s)`

Thanks in advance for your help

**Comment by jvishnuvardhan** [comment] 2021-08-09 23:08
@AlexandreBourrieau I cannot reproduce the issue with `TF2.5`. Can you please check [this gist](https://colab.research.google.com/gist/jvishnuvardhan/46ea2f3be1bffcc5c11db3e5ca48a5e5/untitled1025.ipynb) and let us know what you think? Thanks!

I got the following output
`0.865458`

**Comment by jvishnuvardhan** [comment] 2021-08-19 02:20
Closing this issue as this was resolved. Please feel free to reopen if I am mistaken. Thanks!

**Closed by jvishnuvardhan** 2021-08-19 02:20 UTC
Labels: type:support, stat:awaiting response
