### ISSUE TITLE
Calling Keras layers on TensorFlow tensors

### ISSUE THREAD

**Issue by sumedhvdatar** [keras-team/keras#10914] opened 2018-08-15 06:39 UTC
Please make sure that the boxes below are checked before you submit your issue. If your issue is an implementation question, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [join the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) and ask there instead of filing a GitHub issue.

Thank you!

- [x] Check that you are up-to-date with the master branch of Keras. You can update with:
pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps

- [x] If running on TensorFlow, check that you are up-to-date with the latest version. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [x] If running on Theano, check that you are up-to-date with the master branch of Theano. You can update with:
pip install git+git://github.com/Theano/Theano.git --upgrade --no-deps

- [x] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

I am trying to use Keras model architecture and only use tensorflow tf session at the last step to train a model.

I am using the keras sample tutorial provided here : https://blog.keras.io/keras-as-a-simplified-interface-to-tensorflow-tutorial.html

The example has MNIST tutorials. Is there a way to use custom data and how we have to input custom data tensor?

**Comment by ymodak** [comment] 2018-11-21 23:47
Its hard to figure your exact ask. Please may be you can elaborate more on your issue. For example: 
What is the current behavior and your expected behavior?.
Closing this issue due to lack of information to work with. Feel free to reopen the issue when additional information becomes available. Thanks!

**Closed by ymodak** 2018-11-21 23:47 UTC
Labels: type:tensorFlow
