### ISSUE TITLE
UpSampling2D Error: interpolation should be one of "nearest" or "bilinear".

### ISSUE THREAD

**Issue by yifeipet** [keras-team/keras#16952] opened 2022-08-27 22:39 UTC
UpSampling2D has an error if I set interpolation='bicubic'.  
The Keras and Tensorflow documents say that UpSampling2D support "area", "bicubic", "bilinear", "gaussian", "lanczos3", "lanczos5", "mitchellcubic", "nearest" but it actually only supports "bilinear" and "nearest" interpolations. 

I used Colab. 

Please fix it and add other interpolation methods. Thanks!

------------------------------------------------------------------------------------------------------
I checked the tensorflow version on Colab again. It's v.2.8.2. I updated Tensorflow version to v.2.9.1 and the error has gone. If I still have issues, please let me come here again. Thank you!

**Comment by sushreebarsa** [comment] 2022-08-30 05:58
@yifeipet 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Could you please confirm if the issue is resolved in latest TF version?
Thank you!

**Closed** 2022-09-13 06:52 UTC
Labels: type:support, stat:awaiting response from contributor, stalled
