### ISSUE TITLE
"rgb" misspelled as "rbg" in Keras documentation for flow_from_directory()

### ISSUE THREAD

**Issue by andrewferlitsch** [keras-team/keras#11952] opened 2018-12-31 01:51 UTC
Please make sure that the boxes below are checked before you submit your issue.
If your issue is an **implementation question**, please ask your question on [StackOverflow](http://stackoverflow.com/questions/tagged/keras) or [on the Keras Slack channel](https://keras-slack-autojoin.herokuapp.com/) instead of opening a GitHub issue.

Thank you!

- [NA ] Check that you are up-to-date with the master branch of Keras. You can update with:
`pip install git+git://github.com/keras-team/keras.git --upgrade --no-deps`

- [ NA] Check that your version of TensorFlow is up-to-date. The installation instructions can be found [here](https://www.tensorflow.org/get_started/os_setup).

- [NA ] Provide a link to a GitHub Gist of a Python script that can reproduce your issue (or just copy the script here if it is short).

The documentation for flow_from_directory() has a spelling error. Under arguments, 'rgb' is misspelled as  'rbg':

color_mode: One of "grayscale", "rbg", "rgba". Default: "rgb". Whether the images will be converted to have 1, 3, or 4 channels.

**Comment by benjaminr** [comment] 2018-12-31 20:19
Happy to look at this one.

**Comment by amanagr** [comment] 2019-01-02 03:33
This is already fixed on master and can be closed now?

**Comment by KDercksen** [comment] 2019-01-02 15:10
https://github.com/keras-team/keras-preprocessing/blob/master/keras_preprocessing/image/image_data_generator.py#L451

fixed here, for reference

**Comment by DeepManuPy** [comment] 2019-06-30 18:52
Why is this issue still open? Is this fixed?

**Comment by Navan0** [comment] 2019-08-01 21:25
The issue is fixed, right ? But why is this still open

**Closed** 2019-08-01 21:36 UTC
Labels: Good first issue, stat:contributions welcome, type:docs
