### ISSUE TITLE
keras model.save() TypeError

### ISSUE THREAD

**Issue by skymeteorite** [keras-team/keras#12849] opened 2019-05-22 10:17 UTC
I wrote a simple CNN model, when I use model.save('model.h5'), it came an error 
"
Traceback (most recent call last):
  File "D:/py_code/testCNN/CNN_Conv2d_train.py", line 95, in <module>
    model.save('model.h5')
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\engine\saving.py", line 114, in _serialize_model
    layer_group[name] = val
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\keras\utils\io_utils.py", line 218, in __setitem__
    dataset = self.data.create_dataset(attr, val.shape, dtype=val.dtype)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\h5py\_hl\group.py", line 136, in create_dataset
    dsid = dataset.make_new_dset(self, shape, dtype, data, **kwds)
  File "F:\Anaconda3\envs\tensorflow\lib\site-packages\h5py\_hl\dataset.py", line 117, in make_new_dset
    dtype = numpy.dtype(dtype)
TypeError: data type not understood
"
I had h5py2.9 in my list,  what's that mean?

**Comment by ymodak** [comment] 2019-05-23 20:32
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2019-05-28 19:36
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-05-28 19:36 UTC
Labels: backend:tensorflow, stat:awaiting response
