### ISSUE TITLE
Train and test data that has different channel size

### ISSUE THREAD

**Issue by 01bui** [keras-team/keras#10786] opened 2018-07-26 15:05 UTC
Hi!

Is there a way I can use pre-trained weights from a model that takes input_shape of (batch_size, 50, 50, 4) to be initialized for another model that takes input_shape of  (batch_size, 50, 50, 1)? Output_shape has size of (50, 50, 1).

AND

Is there a way I can train a model that takes input_shape of (batch_size, 50, 50, 4) and test on data that has input_shape of  (batch_size, 50, 50, 1)? Output_shape has size of (50, 50, 1).

Thank you!

**Comment by chriskoups** [comment] 2018-07-27 08:19
Here is not a place for help and this is not a bug or feature.
Please do not post here this type of questions but use stackoverflow.
In your question, the short answer is no.
The long one is:
You have 50x4 weights and you want to just use 50x1, from simple maths that is impossible.
You can sellect just one of the 4 channels (by using individual weight extraction) and use it but the results may not make any sense.
Please close the issue by pressing the close button under the reply/comment section.

**Comment by tomastheod-ITI** [comment] 2018-07-27 09:01
@01bui Maybe you can change your second model to take as input (50, 50, 4) as well and add an extra layer `Conv2D(filters=1, kernel_size=(1,1))` that learns to map the 4 input features into 1 new feature. You would also have to change the layer after this one because it has learned to process 4 input variables instead of 1.

**Closed** 2021-06-24 22:31 UTC
