### ISSUE TITLE
Missing comma in test results in unexpected string concatenation 

### ISSUE THREAD

**Issue by code-review-doctor** [keras-team/keras#15854] opened 2022-01-04 15:18 UTC
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): NA
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NA
- TensorFlow installed from (source or binary): NA
- TensorFlow version (use command below): NA
- Python version: NA
- Bazel version (if compiling from source): NA
- GPU model and memory: NA
- Exact command to reproduce: NA

**Describe the problem**.

Absent comma results in unwatned string concatenation on line 330:
https://github.com/keras-team/keras/blob/f1e9c76675981ee6683f54a3ce569212d551d12d/keras/engine/training_generator_test.py#L326-L332

So `'matmul'` gets appended with 'Yaks are also quite nice' resulting in `matmulYaks are also quite nice` being used in the test.

**Describe the current behavior**.

`'matmulYaks are also quite nice'` is used in the test

**Describe the expected behavior**.

`'matmul', 'Yaks are also quite nice'` is used in the test

**[Contributing](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md)**.

- Do you want to contribute a PR? (yes/no): yes
- If yes, please read [this page](https://github.com/keras-team/keras/blob/master/CONTRIBUTING.md) for instructions
- Briefly describe your candidate solution(if contributing):

Add the missing comma

**Standalone code to reproduce the issue**.

NA

**Source code / logs**.

NA

**Comment by kumariko** [comment] 2022-01-05 05:38
@code-review-doctor In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by code-review-doctor** [comment] 2022-01-05 09:08
I don't have one as I am a static analysis tool that does not run your code - I just analyze it to detect bugs.

here's an explanation of the problem: https://codereview.doctor/features/python/best-practice/avoid-missing-comma

**Comment by sachinprasadhs** [comment] 2022-01-10 17:42
Closing this issue since the PR is merged, Thanks for reporting the bug.

**Closed by sachinprasadhs** 2022-01-10 17:42 UTC
Labels: type:bug/performance, type:docs
