### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_keras_history'

### ISSUE THREAD

**Issue by HGamalElDin** [keras-team/keras#14464] opened 2021-02-18 01:28 UTC
I'm faceing this error while fitting the model:

```
AttributeError: in user code:

    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py:533 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\keras\engine\compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\keras\losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\tensorflow\python\keras\losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    C:\Users\Heba Gamal El-Din\anaconda3\lib\site-packages\keras_contrib\losses\crf_losses.py:54 crf_loss
        crf, idx = y_pred._keras_history[:2]
AttributeError: 'Tensor' object has no attribute '_keras_history'
```
without concatenation function at all
Model Architecture:

```
from keras.models import Model, Input
from tensorflow.keras.layers import LSTM, Embedding, Dense, TimeDistributed, Bidirectional
import tensorflow.keras as k
from keras_contrib.layers import CRF

input = Input(shape=(maxlen,))
word_embedding_size = 150

MODEL = Embedding(input_dim=n_words, output_dim=word_embedding_size, input_length=140)(input)

MODEL = Bidirectional(LSTM(units=word_embedding_size, 
                           return_sequences=True, 
                           dropout=0.5, 
                           recurrent_dropout=0.5, 
                           kernel_initializer=k.initializers.he_normal()))(MODEL)
MODEL = LSTM(units=word_embedding_size * 2, 
             return_sequences=True, 
             dropout=0.5, 
             recurrent_dropout=0.5, 
             kernel_initializer=k.initializers.he_normal())(MODEL)

MODEL = TimeDistributed(Dense(n_tags, activation="relu"))(MODEL)  

CRF_LAYER = CRF(n_tags)

OUTPUT = CRF_LAYER(MODEL)  # OUTPUT
MODEL = Model(input, OUTPUT)
```
Spec:
Keras=2.4.3
python=3.7
Windows

**Comment by HGamalElDin** [comment] 2021-02-20 03:54
as mentioned by "Lê Hoàng" in https://www.kaggle.com/nikkisharma536/ner-with-bilstm-and-crf#1209677
 notebook, the solution is to use:
tensorflow==1.13.1
keras==2.2.4
keras-contrib by: pip install git+https://www.github.com/keras-team/keras-contrib.git

**Comment by lijiayi980130** [comment] 2021-03-10 13:25
I am facing the same error, can you help me? Would I have to replace the version of keras and tensorflow ? thank you

**Comment by meerajsph** [comment] 2021-04-15 14:00
I am trying to tune my Bi-LSTM CRF model using keras tuner, in that case Keras tuner requires Tensor flow Python 3.6
TensorFlow 2.0 , but sadly keras contrib has conflicts with tensor flow 2.0 due to this "y_pred does not have _keras_history". Is there a work around for this . A fix in the keras contrib crf_losses would maybe fix that and we could use tensorflow version 2.0 consistently . Could you please help as to how to fix this??

**Comment by gitclem** [comment] 2021-07-05 21:33
> as mentioned by "Lê Hoàng" in https://www.kaggle.com/nikkisharma536/ner-with-bilstm-and-crf#1209677
> notebook, the solution is to use:
> tensorflow==1.13.1
> keras==2.2.4
> keras-contrib by: pip install git+https://www.github.com/keras-team/keras-contrib.git

I'm not able to pip install TF 1.13.1
```
pip install tensorflow==1.13.1 
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.6.0rc0)
ERROR: No matching distribution found for tensorflow==1.13.1

```

**Comment by jvishnuvardhan** [comment] 2021-07-21 23:00
@HGamalElDin Thanks for creating the issue and also solution. 

One of the reason for `_keras_history` error was due to mixing different methods from tensorflow and keras. 

I have updated your code (consistently using all methods under tensorflow.keras  and also removed `contrib`) and tried using `TF2.5`. However, there are some variable definition is missing, it is throwing different error. If you want to use recent `keras`, then please provide standalone code to reproduce issue so that I can help.

Please close the issue if this was resolved. If it was not resolved for anyone, please provide a standalone code. Thanks!

**Comment by Karthik-Ragunath** [comment] 2021-07-26 18:47
Actually, crf layer must be imported as 
`from tensorflow_addons.layers import CRF as crf`

Even after replacing the above crf layer in your gist, still compiler throws
`TypeError: Keras symbolic inputs/outputs do not implement `__len__`. You may be trying to pass Keras symbolic inputs/outputs to a TF API that does not register dispatching, preventing Keras from automatically converting the API call to a lambda layer in the Functional Model. This error will also get raised if you try asserting a symbolic input/output directly.`

**Comment by jvishnuvardhan** [comment] 2021-07-26 20:46
@Karthik-Ragunath Are you referring to my gist? I didn't face that `TypeError`. Can you please share a standalone code to reproduce the issue? Thanks!

**Comment by jvishnuvardhan** [comment] 2021-08-04 08:11
Closing due to lack of recent activity. Please feel free to reopen when you have more info and standalone code to reproduce the issue. Thanks!

**Closed by jvishnuvardhan** 2021-08-04 08:11 UTC
Labels: stat:awaiting response, type:support

**Comment by arijit8** [comment] 2021-08-15 16:31
@HGamalElDin, We do not need to downgrade any of the versions. Can utilize tensorflow-add to build CRF layer. Hope this helps :)

`
from tensorflow_addons.layers import CRF

x = ....
crf_layer = CRF(n_tags)
_, output_layer, _, _ = crf_layer(x)

model = Model(input_layer, output_layer)
mode.summary()
`
