### ISSUE TITLE
Initializing the val_loss with not Inf value

### ISSUE THREAD

**Issue by easadi** [keras-team/keras#12803] opened 2019-05-08 21:18 UTC
Can anybody help me in finding a way to resume training for an LSTM model with fit_generator without restating the loss value to inf? 

**Background:** I am training an LSTM model and I have a very big time series data (many sample times) and only 2 features. Therefore the shape of my time series x data is N by 2 where N is a very large number. I use a batch generator to randomly segment my data in smaller batches of batch_N by 2 (where batch_N is much smaller than N):

    def batch_generator(batch_size, sequence_length): 
    ...
        for i in range(batch_size):
            ...
           x_batch[i] = batch_x_train_scaled[idx:idx+sequence_length]
           y_batch[i] = batch_y_train_scaled[idx:idx+sequence_length] 
     yield (x_batch, y_batch)

I use also a ModelCheckpoint to save the best-trained model

    callback_checkpoint = ModelCheckpoint(filepath=path_checkpoint, 
    monitor='val_loss', verbose=1,save_weights_only=False, save_best_only=True)
Also, every time I want to resume the training, first I load the last saved model:

    if True:
        try:
    #         model.load_weights(path_checkpoint)
            model = load_model(path_checkpoint)

        except Exception as error:
            print("Error trying to load checkpoint.")
            print(error)

**What is the Problem?** Every time I resume the training, a new batch file is loaded first into the fit_generator and the model would use the last save weights. the loss value is reset to inf. Therefore, at the end of the first resumed training epoch, no matter how good or bad is the training outcomes, the model reports that the val_loss is improved from inf to some number and thus overwrites the new weights. The problem is that sometimes the new weights are not as optimal as the previous ones (due to the fact that this time the model is using new batch data for training) and thus I will lose some optimum weights.

**What I have done so far to fix this issue?** 

**Approach one (unsuccessful)**: defining custom loss function:

    def my_loss(y_true, y_pred):
        train_loss = binary_crossentropy(y_true, y_pred)
        validation_loss = 2*binary_crossentropy(y_true, y_pred)
        temp=tf.keras.backend.cast(validation_loss,'float16')
        if temp>1:  # update 1 to last best val_loss before resume training
            validation_loss=validation_loss+np.inf
    # validation_loss=np.inf
        return tf.keras.backend.in_train_phase(train_loss, validation_loss)

    model.compile(loss=my_loss, optimizer=optimizer)

**results of approach one:**

    Error:
    ---> 12     if temp>1:
    TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

**Approach two (unsuccessful)**: defining a custom callback to save model:

    best_val_loss = 1 # update 1 to last best val_loss before resume training

    def saveModel(epoch,logs):
        val_loss = logs['val_loss']
        if val_loss < best_val_loss:
            best_val_loss=val_loss
            model.save('my_model.hdf5')

    my_callback = LambdaCallback(on_epoch_end=saveModel)

**results of approach two:**
    
    UnboundLocalError: local variable 'best_val_loss' referenced before assignment

**Approach three(unsuccessful)**: defining a custom callback to save model:

    best_val_loss = 1 # update 1 to last best val_loss before resume training

    def saveModel(epoch,logs,best_val_loss):
        val_loss = logs['val_loss']
        if val_loss < best_val_loss:
            best_val_loss=val_loss
            model.save('my_model.hdf5')

    my_callback = LambdaCallback(on_epoch_end=saveModel)

**results of approach three:**

    TypeError: saveModel() missing 1 required positional argument: 'best_val_loss'

**Comment by jvishnuvardhan** [comment] 2019-05-09 21:51
Please fill the issue [template](https://github.com/keras-team/keras/issues/new?template=a--tensorflow-backend-users.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. . Thanks!

**Comment by jvishnuvardhan** [comment] 2019-05-21 05:02
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!

**Comment by paapu88** [comment] 2020-01-17 08:14
Would also need this, because I feed in subsequent training samples and read in old best weights (which have associated val_loss).

**Comment by anegm** [comment] 2020-11-13 22:02
I have faced the same problem when saving only the weights of the model. Instead, I tried to save the whole model, not just the weights, as an h5 file using the save command.
When I loaded the saved model, val_loss started from the last value and not inf when I continued the training.

**Comment by ravikumar2209** [comment] 2020-12-10 17:05
@micbia - Thanks a zillion. Your code snippet came very handy. I wonder keras team is yet not worried about this issue. Working with Google Colab is a challenge as it timesout in few mins of inactivity and to restart the model from previous check point, loss is always calculated from inf. 

I wish Keras team tries to focus on this very basic lack of capability and fix it as soon as possible and provide this functionality out of the box.

**Comment by ghylander** [comment] 2021-02-05 11:27
i too have this problem

for the keras team to consider that this is a real issue::
in my model, i begin training a classifying layer with the rest of the model frozen
next, i unfreeze the last 25 layers (25 layers previous to the classifying layer)
next, the following 25, etc

in this process i use the keras callback to save the best checkpoints and later load them back for the next stage

after every training stage and upon beginning a new one, the val_loss of the previous stage is lost and val_loss is initialized to inf

thanks for the custom callback @micbia!

**Comment by AI-public** [comment] 2021-05-01 15:15
Still no solution from keras team???

**Comment by helpforsoftware** [comment] 2022-01-13 08:45
i need this too

**Comment by jvishnuvardhan** [comment] 2022-01-13 17:44
Reopening it. Can one of you please provide a standalone code to reproduce the issue?

**Comment by micbia** [comment] 2022-01-13 22:08
@jvishnuvardhan the issue can be replicated with any code. For instance, I can suggest you use the simple [CNN on MNIST](https://keras.io/examples/vision/mnist_convnet/) provided by Keras API.

 It is enough to run the network, let it save a model with the standard [ModelCheckpoint](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/callbacks.py#L1057) callback, stop the training before it is finished and then resume the network training from the stopped epoch while loading the previously best-saved model. 

You will notice that after the first resumed epoch, no matter what loss you get a new model will be saved just because the monitored variable [best](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/callbacks.py#L1196) is reset to np.inf (or -np.inf).

I proposed a quick fix by passing the variable **best=None** (the epoch of the best-saved model before the stop), such that the user can define it in case of resumed training. Have a look at my callback [here](https://github.com/micbia/SegU-Net/blob/master/utils_network/callbacks.py#L141).

To notice that also the [ReduceLROnPlateau](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/callbacks.py#L2270) callback has this problem. Once resumed the training the [wait](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/python/keras/callbacks.py#L2332) variable is reset to 0. As a quick fix, I pass this variable so that the user can define it as the difference between the resume epoch and the epoch of the best-saved model, in case of resumed training. Check out my code where I use the callbacks [here](https://github.com/micbia/SegU-Net/blob/master/segUNet.py#L150). You can find the modified callback [here](https://github.com/micbia/SegU-Net/blob/master/utils_network/callbacks.py#L59).

Thank you for reopening the post.
Cheers

**Comment by ghylander** [comment] 2022-01-21 14:08
any comments from the keras team?

**Comment by jvishnuvardhan** [comment] 2022-01-21 20:07
@rchao Can you please take a loot at it. Thanks!

**Comment by haifeng-jin** [comment] 2022-02-03 04:48
Summary: The `ModelCheckpoint` would save the model after the first epoch regardless of if the model has improved or not because it is always comparing with the initial `val_loss`, which is set to `inf`, even if the model was loaded from disk and has good performance.

**Comment by deketh** [comment] 2022-03-24 14:33
`ModelCheckpoint` should have the ability to set `self.best` (as @micbia pointed out) to checkpoint file's. There's no point on saving the best-weight checkpoint if you cannot resume the training without losing monitored metric's value.

**Comment by deketh** [comment] 2022-03-24 14:36
`ModelCheckpoint` should have the ability to set `self.best` (as @micbia pointed out) to checkpoint file's. There's no point on saving the best-weight checkpoint if you cannot resume the training without losing monitored metric's value.

**Comment by micbia** [comment] 2022-03-24 17:09
as mentioned above by @deketh, to fix this you require very little change to `ModelCheckpoint`. I think you just need to add `best` as a variable. As a reference, here is my custom checkpoint [SaveModelCheckpoint](https://github.com/micbia/SegU-Net/blob/v2.0/utils_network/callbacks.py#L129). 

The changes I implemented consist simply in passing `best` with the [initiation](https://github.com/micbia/SegU-Net/blob/v2.0/utils_network/callbacks.py#L142) variables (None [otherwise](https://github.com/micbia/SegU-Net/blob/v2.0/utils_network/callbacks.py#L133)) and adding a few if-else [between lines 148 and 164](https://github.com/micbia/SegU-Net/blob/v2.0/utils_network/callbacks.py#L148-L164) for initiation of `best` and the operation on the monitor

**Comment by ghylander** [comment] 2022-08-11 07:59
It seems like this was silently implemented with the release of tf API v2.8.

I just checked the [tf docs for the ModelCheckpoint callback](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint) and it now shows the following:
![image](https://user-images.githubusercontent.com/74593034/184089175-7e93e62b-03f1-4ae9-8ebc-6b57f220d871.png)

**Comment by gowthamkpr** [comment] 2022-08-16 18:20
@easadi Can we close this issue as it has been implemented as shown [above](https://github.com/keras-team/keras/issues/12803#issuecomment-1211666760). Thanks!

**Comment by easadi** [comment] 2022-08-16 18:29
> @easadi Can we close this issue as it has been implemented as shown [above](https://github.com/keras-team/keras/issues/12803#issuecomment-1211666760). Thanks!

Yes please.

**Closed** 2022-09-05 08:01 UTC
Labels: type:bug/performance, stat:awaiting response from contributor, stalled
