### ISSUE TITLE
[BUG]Some Errors : using multi_gpu : can't save_model

### ISSUE THREAD

**Issue by Entonytang** [keras-team/keras#8253] opened 2017-10-26 12:46 UTC
Using multi_gpu to train model : 
def multi_gpu_test_simple_model():
    print('####### test simple model')
    num_samples = 1000
    input_dim = 10
    output_dim = 1
    hidden_dim = 10
    gpus = 2
    epochs = 8
    model = keras.models.Sequential()
    model.add(keras.layers.Dense(hidden_dim,
                                 input_shape=(input_dim,)))
    model.add(keras.layers.Dense(output_dim))

    x = np.random.random((num_samples, input_dim))
    y = np.random.random((num_samples, output_dim))
    parallel_model = multi_gpu_model(model, gpus=gpus)
    from keras.callbacks import ModelCheckpoint
    parallel_model.compile(loss='mse', optimizer='rmsprop')
    parallel_model.fit(x, y, epochs=epochs)

    from keras.models import save_model
    save_model(parallel_model, '1.h5', overwrite=True, include_optimizer=True)

Error : can't pickle NoImplementedType objects 
please solve this problem

**Comment by gabrielleyr** [comment] 2017-11-01 20:03
I had the same error when saving the whole model. Try saving the weights only: 

```
from keras.models import save_weights
save_weights(parallel_model, '1.h5', overwrite=True, include_optimizer=True)
```

**Comment by fchollet** [comment] 2017-11-01 20:04
I general I recommend only saving the "template model" (the model built on
CPU that you passed to `multi_gpu_model`).

**Comment by kuba-lilz** [comment] 2017-11-02 04:07
@fchollet I tried doing exactly that. Created a simple custom version of ModelCheckpoint that saves original model on epoch end. It breaks with `Type error: can't pickle module objects` error

```
Epoch 1/100
27/28 [===========================>..] - ETA: 0s - loss: 0.4386
Validation loss decreased from inf to 0.12643371584514776, saving model
Traceback (most recent call last):
  File "./scripts/fcn/train_model.py", line 91, in <module>
    main()
  File "./scripts/fcn/train_model.py", line 85, in main
    callbacks=get_callbacks(model, model_path)
  File "/home/kuba/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/kuba/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2117, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/kuba/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 73, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "./scripts/fcn/train_model.py", line 35, in on_epoch_end
    self.model.save(self.path, overwrite=True)
  File "/home/kuba/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2556, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/kuba/anaconda3/lib/python3.6/site-packages/keras/models.py", line 107, in save_model
    'config': model.get_config()
  File "/home/kuba/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 2397, in get_config
    return copy.deepcopy(config)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/kuba/anaconda3/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects
```

**Comment by kuba-lilz** [comment] 2017-11-02 04:21
Here's a minimal code (with parts irrelevant to the problem ignored) I used to saved the base model while training multi_gpu_model:

```python
class CustomModelCheckpoint(keras.callbacks.Callback):

    def __init__(self, model, path):

        super().__init__()

        self.model = model
        self.path = path

        self.best_loss = np.inf

    def on_epoch_end(self, epoch, logs=None):

        loss = logs['val_loss']

        if loss < self.best_loss:

            print("\nValidation loss decreased from {} to {}, saving model".format(self.best_loss, loss))
            self.model.save_weights(self.path, overwrite=True)
            self.best_loss = loss


def main():

    model = get_model()
    multi_gpu_model = keras.utils.training_utils.multi_gpu_model(model, gpus=2)
    multi_gpu_model.compile(optimizer='adam', loss='binary_crossentropy')

    multi_gpu_model.fit_generator(
        // ...
        callbacks=[CustomModelCheckpoint(model, model_path)])
```

When I use `model.save_weights(...)` in callback, like in code above, model can be successfully saved. When using just `model.save(...)`, code breaks with error from previous post.

However, even when using `model.save_weights(...)`, loading model with `model.load_weights(...)` fails with 

```python
ValueError: You are trying to load a weight file containing 1 layers into a model with 19 layers.
```

**Comment by kuba-lilz** [comment] 2017-11-02 04:30
Looking at `keras.callbacks.ModelCheckpoint` class, it uses `self.model` object in `on_epoch_end(...)` and calls its `save(...)` and `save_weights(...)` functions, as appropriate. I don't see how does it obtain the `self.model` object though. 

Please correct me if I'm wrong, but I suspect that some magic is going under the hood that dynamically assigns meaning to `model` object based on Tensorflow graph variables. That makes me wonder whether `model.save_weight()` is looking at `model`  object at all - maybe it's fetching leaf tensors from Tensorflow graph? In that case even if I do provide a valid CPU-build model object, there is a chance that what gets saved is what magic inside `save_weight()` found, which might be multi_gpu_model tensors.

**Comment by kuba-lilz** [comment] 2017-11-02 05:29
To check my premonition, I moved up code creating callbacks objects so that it is called BEFORE multi_gpu_model object is created and that worked like a charm ^^
Pretty sure otherwise Callback object is scanning Tensorflow graph for latest nodes to decide what belong to a model ^^

**Comment by PBehr** [comment] 2017-11-04 10:39
#8123

**Comment by PBehr** [comment] 2017-11-04 10:48
As mentioned in #8123 the problem is the: import tensorflow as tf line in the multi_gpu_model function.

**Comment by jmcconnell** [comment] 2017-11-08 21:00
I've followed fchollet's advice about saving the model and weights separately. Wound up with this, which is working fine:

**Comment by jmcconnell** [comment] 2017-11-08 21:04
I've followed fchollet's advice about saving the model and weights separately. Wound up with this, which is working fine. You'll have to update `original_model()` to pull the correct layer for your architecture.
```
def original_model(parallel_model):
    return parallel_model.get_layer('sequential_1')

class ParallelModelCheckpoint(ModelCheckpoint):
    def __init__(self, path):
        super().__init__(path, save_weights_only=True)

    def set_model(self, model):
        super().set_model(original_model(model))

model = get_model()
parallel_model = multi_gpu_model(model, gpus=2)

model.compile(...)
model.save(...)

checkpoint = ParallelModelCheckpoint('out/weights.{epoch:02d}-{val_loss:.2f}.hdf5')

parallel_model.compile(...)
parallel_model.fit(..., callbacks=[checkpoint])
```

**Comment by shu-hai** [comment] 2017-11-12 05:39
@jmcconnell , I use functional API to create the model, when I use your code blow, it gives error:
No such layer: sequential_1.

I am frustrated to save the model/weight of each epoch when using multi_gpu_model. It always gives some kinds of errors.

```
def original_model(parallel_model):
    return parallel_model.get_layer('sequential_1')

class ParallelModelCheckpoint(ModelCheckpoint):
    def __init__(self, path):
        super().__init__(path, save_weights_only=True)

    def set_model(self, model):
        super().set_model(original_model(model))

model = get_model()
parallel_model = multi_gpu_model(model, gpus=2)

model.compile(...)
model.save(...)

checkpoint = ParallelModelCheckpoint('out/weights.{epoch:02d}-{val_loss:.2f}.hdf5')

parallel_model.compile(...)
parallel_model.fit(..., callbacks=[checkpoint])
```

**Comment by shu-hai** [comment] 2017-11-12 06:33
@fchollet, would you please give an example for how to save the model/weights trained by each epoch when using multi_gpu_model?
I always got some errors.

**Comment by EPellegrini87** [comment] 2017-11-13 16:02
@PBehr 's suggestion worked for me.

**Comment by jmcconnell** [comment] 2017-11-14 19:41
@shu-hai yeah, I mentioned you'll have to update `original_model()` to work with your architecture. I'm sure there is a more generalized way of grabbing the correct layer, but I am new to Keras and didn't have time to look into it.

Run a `print(parallel_model.summary())` to see what the layer for your original model is called.

**Comment by intrros** [comment] 2018-01-05 20:18
The solution by @maxim5 worked for me: https://github.com/keras-team/keras/issues/8123#issuecomment-354857044

**Comment by wt-huang** [comment] 2018-11-02 21:39
Closing as this is resolved

**Closed by wt-huang** 2018-11-02 21:39 UTC

**Comment by hovinh** [comment] 2021-09-03 09:06
Hi, here is my solution in case anyone's still interested. Thank you @jmcconnell and @maxim5 .

Problem statement: I trained UNet with 4-GPU using `multi_gpu_model`, then unable to `load_weights` during inference with a CPU or 1 GPU model.

Observation: when I print model architecture with `print(parallel_model.summary())` 
![image](https://user-images.githubusercontent.com/7614509/131978571-c2495903-28c8-4556-afd3-ed2b3576b9d3.png)

We can see that my original model is `model_1`.

My fix:
- redefine `multi_gpu_model`: [#8123 (comment)](https://github.com/keras-team/keras/issues/8123#issuecomment-354857044)
- create customModelCheckpoint to ensure whatever model saved is from the original model. Let's say my existing Checkpoint only use the following arguments: `filepath`, `verbose`, `save_best_only`, `save_weights_only`, then the new class I create is as follows:

```python
class CustomModelCheckpoint(ModelCheckpoint):
   def __init__(self, filepath):
      super().__init__(filepath, verbose=1, save_best_only=True, save_weights_only=True)

   def set_model(self, model):
      def original_model(model):
         return model.get_layer('model_1')
      super().set_model(original_model(model))

callbacks = {CustomModelCheckpoint('weight.h5')}
```
