### ISSUE TITLE
load_model fails with error ValueError: axes don't match array

### ISSUE THREAD

**Issue by littlegreenbean33** [keras-team/keras#9562] opened 2018-03-05 13:25 UTC
The model includes a custom loss and 2 outputs.

The below is the dump

In [3]: keras.__version__
Out[3]: '2.1.3'

In [5]: tf.__version__
Out[5]: '1.6.0-rc0'

In [6]: model=load_model("/home/julian/kaggle/sbowl2018/saved_models/model.h5")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     51     try:
---> 52         return getattr(obj, method)(*args, **kwds)
     53

AttributeError: 'Dataset' object has no attribute 'transpose'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-6-a81b83ffb149> in <module>()
----> 1 model=load_model("/home/julian/kaggle/sbowl2018/saved_models/model.h5")

~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/keras/models.py in load_model(filepath, custom_objects, compile)
    244
    245         # set weights
--> 246         topology.load_weights_from_hdf5_group(f['model_weights'], model.layers)
    247
    248         # Early return if compilation is not required.

~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/keras/engine/topology.py in load_weights_from_hdf5_group(f, layers)
   3151                                                        weight_values,
   3152                                                        original_keras_version,
-> 3153                                                        original_backend)
   3154         if len(weight_values) != len(symbolic_weights):
   3155             raise ValueError('Layer #' + str(k) +
~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/keras/engine/topology.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend)
   3048                 weights[1] = conv_utils.convert_kernel(weights[1])
   3049         if K.int_shape(layer.weights[0]) != weights[0].shape:
-> 3050             weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
   3051             if layer.__class__.__name__ == 'ConvLSTM2D':
   3052                 weights[1] = np.transpose(weights[1], (3, 2, 0, 1))

~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py in transpose(a, axes)
    573
    574     """
--> 575     return _wrapfunc(a, 'transpose', axes)
    576
    577

~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     60     # a downstream library like 'pandas'.
     61     except (AttributeError, TypeError):
---> 62         return _wrapit(obj, method, *args, **kwds)
     63
     64

~/virtualenvs/tensorflowgpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py in _wrapit(obj, method, *args, **kwds)
     40     except AttributeError:
     41         wrap = None
---> 42     result = getattr(asarray(obj), method)(*args, **kwds)
     43     if wrap:
     44         if not isinstance(result, mu.ndarray):

ValueError: axes don't match array

**Comment by trueProgrammer** [comment] 2018-07-19 17:07
+1

**Comment by Dref360** [comment] 2018-07-19 17:15
Hi,
We could work on this better if you could provide a standalone reproducible example.
Some advices:
* Don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Keras (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.

Thanks!
Dref360

**Comment by littlegreenbean33** [comment] 2018-07-19 20:33
Hi,

this has been overtaken by events / used a workaround time ago. I do no longer have the code for these tests. I regret I can't pitch in.

JC

**Comment by liketheflower** [comment] 2018-07-27 14:08
I got the similar problem when I load a model trained by 2 GPUs. However, the loading model trained by 1 GPU works good.
"ValueError: axes don't match array"

**Comment by apcode** [comment] 2018-09-15 20:13
I get the same problem. 
If I train a model using 2 GPUs, using multi_gpu_model and ModelCheckpoint callback to save best, it gives this error when calling load_model on the checkpoint saved model.
I want to train the model using multi gpus but run it again on a single GPU. this seems to fail

**Comment by PCJimmmy** [comment] 2018-10-18 14:35
model = load_model(model_to_use, custom_objects={'mean_iou': mean_iou,'iou_bce_loss':iou_bce_loss})

produces the axes don't match array error - model file from checkpoint has same result as a model saved after completion of model.fit_generator.  Two GPU's used for training.  Model ran for three days.

ValueError                                Traceback (most recent call last)
<ipython-input-11-9ab9165e68c4> in <module>
      1 #model = load_model(model_to_use, custom_objects={'mean_iou': mean_iou,'iou_bce_loss':iou_bce_loss})
----> 2 model = load_model(model_to_use)

~\Anaconda3\lib\site-packages\keras\engine\saving.py in load_model(filepath, custom_objects, compile)
    417     f = h5dict(filepath, 'r')
    418     try:
--> 419         model = _deserialize_model(f, custom_objects, compile)
    420     finally:
    421         if opened_new_file:

~\Anaconda3\lib\site-packages\keras\engine\saving.py in _deserialize_model(f, custom_objects, compile)
    272                                                        original_keras_version,
    273                                                        original_backend,
--> 274                                                        reshape=False)
    275         if len(weight_values) != len(symbolic_weights):
    276             raise ValueError('Layer #' + str(k) +

~\Anaconda3\lib\site-packages\keras\engine\saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    680         weights = convert_nested_time_distributed(weights)
    681     elif layer.__class__.__name__ in ['Model', 'Sequential']:
--> 682         weights = convert_nested_model(weights)
    683 
    684     if original_keras_version == '1':

~\Anaconda3\lib\site-packages\keras\engine\saving.py in convert_nested_model(weights)
    668                     weights=weights[:num_weights],
    669                     original_keras_version=original_keras_version,
--> 670                     original_backend=original_backend))
    671                 weights = weights[num_weights:]
    672         return new_weights

~\Anaconda3\lib\site-packages\keras\engine\saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    680         weights = convert_nested_time_distributed(weights)
    681     elif layer.__class__.__name__ in ['Model', 'Sequential']:
--> 682         weights = convert_nested_model(weights)
    683 
    684     if original_keras_version == '1':

~\Anaconda3\lib\site-packages\keras\engine\saving.py in convert_nested_model(weights)
    656                     weights=weights[:num_weights],
    657                     original_keras_version=original_keras_version,
--> 658                     original_backend=original_backend))
    659                 weights = weights[num_weights:]
    660 

~\Anaconda3\lib\site-packages\keras\engine\saving.py in preprocess_weights_for_loading(layer, weights, original_keras_version, original_backend, reshape)
    799             weights[0] = np.reshape(weights[0], layer_weights_shape)
    800         elif layer_weights_shape != weights[0].shape:
--> 801             weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
    802             if layer.__class__.__name__ == 'ConvLSTM2D':
    803                 weights[1] = np.transpose(weights[1], (3, 2, 0, 1))

~\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in transpose(a, axes)
    596 
    597     """
--> 598     return _wrapfunc(a, 'transpose', axes)
    599 
    600 

~\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     49 def _wrapfunc(obj, method, *args, **kwds):
     50     try:
---> 51         return getattr(obj, method)(*args, **kwds)
     52 
     53     # An AttributeError occurs if the object does not have

This seems to be an issue that your letting lie and festering so not going to bother spending time to further document the issue as I don't really have the skill set to get all you want.   Will try the workaround.

**Comment by liketheflower** [comment] 2018-10-18 14:50
For the solution of this problem, i got the suggestion saying that instead of saving 'multi_gpu_model' and loading  'multi_gpu_model' . I should:
1. define a model  
2. define and  compile a multi_gpu_model  
3. training using the multi_gpu_model  
4. during the saving, still saving the model instead of the multi_gpu_model  
5. load the model.  
So the trick should be:
```python
multi_gpu_model = multi_gpu_model(model, gpus=G)
model.save_model(...)
```
Instead of 
```python
multi_gpu_model = multi_gpu_model(model, gpus=G)
multi_gpu_model.save_model(...)
```
Please pay attention to the slight difference. I got this suggestion, however, I did't try it as I don't have time and I gave up using multiple GPU to train the model.  Hope it is helpful on this problem.

**Comment by PCJimmmy** [comment] 2018-10-18 15:14
Thanks jimmy shen

I have had great success over the last 6 weeks using two GPU’s to train a bunch of different models on two different PC’s.  

Today’s failure is very unique – but I did something different.  I trained the model.  Saved it and its weights.  Loaded it and ran it some more with different parameters, all within the same script.   Don’t think I have done this before.   But – to add mystery to the issue I had to do a full clean install of Windows, anaconda, etc.  So the versions of the various stuff that worked for the last 6 weeks are not the same versions as this mornings failure.  Later I will try to load the model into my 2nd PC that still has all versions from 5-6 weeks ago rather than the latest and often not the greatest versions.

Pretty new to Python – 8 weeks and counting – I am finding that keeping Python running is harder task than learning the code.  It seems to be a very unstable process.

Will try the suggestion later today.

Thanks from another Jimmy

Sent from Mail for Windows 10

**Comment by tkchris93** [comment] 2018-10-30 00:36
I just had this problem and just wanted to let any future readers know that @liketheflower and @PCJimmmy have it right. Save the `model`, not the `multi_gpu_model`.

**Comment by wt-huang** [comment] 2018-11-02 21:58
Closing as this is resolved

**Closed by wt-huang** 2018-11-02 21:58 UTC

**Comment by Golbstein** [comment] 2019-02-18 08:24
But what if I want to save the multi_gpu_model during the training? And not necessarily its last epoch?

**Comment by rex-yue-wu** [comment] 2019-03-05 08:46
Does anyone know any workaround to simply load the problematic multiple GPU weight? I mean I now know the right way to save the weights, but I don't have time to retrain a model. Is it still possible to load a (problematic) weight file?

**Comment by MakeCent** [comment] 2019-06-20 07:29
Solution of @liketheflower works well. As for someone may want to save the multi_gpu_model during the training, solution of @RaiAbhishek can helps but not that easily to implement. Here is my solution for saving model with callbacks:
class MyModelCheckPoint(ModelCheckpoint):
```
model = create_model()
parallel_model = multi_gpu_model(model, gpus=n)
parallel_model.compile(...)

class MyModelCheckPoint(ModelCheckpoint):
    def __init__(self, model, *args, **kwargs):
        self.model = model
        super(MyModelCheckPoint, self).__init__(*args, **kwargs)
checkpoint = MyModelCheckPoint(model, filepath, ...)

parallel_model.fit(..., callbacks=[checkpoint])
```

**Comment by MakeCent** [comment] 2019-06-20 08:01
For those who want to save multi_gpu model during training. You can change the model in callback to do it: (inspired by @RaiAbhishek )

```
single_model = create_model()
parallel_model = multi_gpu_model(single_model, gpus=n)
parallel_model.compile(...)

class MyModelCheckPoint(ModelCheckpoint):

    def __init__(self, singlemodel, *args, **kwargs):
        self.singlemodel = singlemodel
        super(MyModelCheckPoint, self).__init__(*args, **kwargs)
    def on_epoch_end(self, epoch, logs=None):
        self.model = self.singlemodel
        super(MyModelCheckPoint, self).on_epoch_end(epoch, logs)

checkpoint = MyModelCheckPoint(single_model, filepath, save_best_only=True, ...)
parallel_model.fit(..., callbacks=[checkpoint])
```

**Comment by tonmoyborah** [comment] 2019-09-30 10:05
The discussion moved towards multi-gpu but the problem persists in even single gpu setups. I have written a dummy script to reproduce the error as @Dref360 asked. 
First the error doesn't show up if we use only basic layers. The InceptionResNetV2 brings out the issue.
Secondly, the `load_model` takes an insanely long duration to execute. 

The code:
```
import numpy as np
import os
from keras.layers import Input, Flatten, Dense, Dropout, Lambda, Conv2D, MaxPooling2D, Concatenate
from keras.models import Model, load_model
from keras import backend as K
from keras.optimizers import RMSprop
from keras.losses import cosine_proximity
from keras.applications.inception_resnet_v2 import InceptionResNetV2

os.environ['CUDA_VISIBLE_DEVICES'] = '0'


def euclidean_distance(vects):
	x, y = vects
	sum_square = K.sum(K.square(x - y), axis=1, keepdims=True)
	return K.sqrt(K.maximum(sum_square, K.epsilon()))


def eucl_dist_output_shape(shapes):
	shape1, shape2 = shapes
	return (shape1[0], 1)


def dummy_train_case():
	tr_pairs = np.array(np.zeros((10, 2, 128, 128, 3)))
	tr_y = np.array(np.zeros((10,)))
	te_pairs = np.array(np.zeros((11, 2, 128, 128, 3)))
	te_y = np.array(np.zeros((11,)))
	input_shape = tr_pairs.shape[2:]

	input = Input(shape=input_shape)
	base_model = InceptionResNetV2(include_top=False, weights=None, input_shape=input_shape)
	x = base_model(input)
	x = Flatten()(x)
	x = Dense(1024, activation='relu')(x)
	x = Dense(128, activation='relu')(x)
	base_network = Model(input, x)

	input_a = Input(shape=input_shape)
	input_b = Input(shape=input_shape)

	processed_a = base_network(input_a)
	processed_b = base_network(input_b)
	distance = Lambda(euclidean_distance, output_shape=eucl_dist_output_shape)([processed_a, processed_b])
	model = Model([input_a, input_b], distance)
	rms = RMSprop(lr=0.001)
	model.compile(loss=cosine_proximity, optimizer=rms)

	model.fit([tr_pairs[:, 0], tr_pairs[:, 1]], tr_y,
			  batch_size=48,
			  epochs=10,
			  validation_data=([te_pairs[:, 0], te_pairs[:, 1]], te_y))
	model.save(model_save_path)


if __name__ == '__main__':
	model_save_path = '/path/to/models/siamese_models/1.hf5'
	dummy_test_case()
	print('model saved')
	model = load_model(model_save_path)
	print('model loaded. Summary: {}'.format(model.summary()))
```



The full error stack:
Traceback (most recent call last):
  File "/home/walle/PycharmProjects/keras_siamese/tests.py", line 60, in <module>
    model = load_model(model_save_path)
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    reshape=False)
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 670, in convert_nested_model
    original_backend=original_backend))
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 682, in preprocess_weights_for_loading
    weights = convert_nested_model(weights)
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 658, in convert_nested_model
    original_backend=original_backend))
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/keras/engine/saving.py", line 801, in preprocess_weights_for_loading
    weights[0] = np.transpose(weights[0], (3, 2, 0, 1))
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 639, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/walle/virtual_environments/tf1.13/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array

**Comment by LeninGF** [comment] 2019-11-27 02:03
> For the solution of this problem, i got the suggestion saying that instead of saving 'multi_gpu_model' and loading 'multi_gpu_model' . I should:
> 
> 1. define a model
> 2. define and  compile a multi_gpu_model
> 3. training using the multi_gpu_model
> 4. during the saving, still saving the model instead of the multi_gpu_model
> 5. load the model.
>    So the trick should be:
> 
> ```python
> multi_gpu_model = multi_gpu_model(model, gpus=G)
> model.save_model(...)
> ```
> 
> Instead of
> 
> ```python
> multi_gpu_model = multi_gpu_model(model, gpus=G)
> multi_gpu_model.save_model(...)
> ```
> 
> Please pay attention to the slight difference. I got this suggestion, however, I did't try it as I don't have time and I gave up using multiple GPU to train the model. Hope it is helpful on this problem.

I don't know, I am having this issue and I have proceeded as you indicate by using model.save instead of multi_gpu.save

**Comment by LeninGF** [comment] 2019-11-29 14:19
> I just had this problem and just wanted to let any future readers know that @liketheflower and @PCJimmmy have it right. Save the `model`, not the `multi_gpu_model`.

But is this really saving the trained weights? I made a little sample at https://github.com/LeninGF/Mnist_ConvNet_MultiGPU it happened that saving and loading with the model.save returned a model, was able to load it, but it had no trained weights

**Comment by sinclairnick** [comment] 2020-05-25 08:17
#10949 #13392 I came acrossed this issue and fixed it by setting the same weights to frozen as when training before loading the model. You can then unfreeze the weights and do what you like. For example
```python
def fix_this_stupid_bug():
    # get model
    model = create_model()
    
    # freeze layers that were frozen during training
    for layer in model.layers:
        if should_freeze(layer):
            layer.trainable = False

    # load weights
    model.load_weights(weights_path)

    # unfreeze model
    for layer in model.layers:
        layer.trainable = True

    # save unfrozen weights
    model.save_weights(out_path)
```

**Comment by inthirties** [comment] 2020-12-09 04:29
you can check whether the model is trainable,  if its trainable is false,  maybe encounter this error.
