### ISSUE TITLE
Performance Bug: Quadratic runtime behavior in model.fit/predict with tf.keras.layers.experimental.preprocessing.TextVectorization

### ISSUE THREAD

**Issue by aucth** [keras-team/keras#14915] opened 2021-07-13 09:37 UTC
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
O(n^2) runtime behavior when calling model.fit or model.predict with a single TextVectorization layer. E.g. calling predict 2 times with n/2 vectors is twice as fast compared to calling predict one time with n vectors. For model.fit the batch_size seems to reduce the runtime linearly. Runtime seems to be O(n * number_of_iterations).

**Describe the expected behavior**
The runtime should be linear with n (O(n))

**Standalone code to reproduce the issue**
```
import tensorflow as tf
import numpy as np

print(tf.__version__)

# generate some dummy data
n = 1000000
x = np.random.randint(1, 100, (n, 1)).astype(str)
y = np.random.uniform(0, 1, (n, 1))

input = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
vectorization = tf.keras.layers.experimental.preprocessing.TextVectorization()
vectorization.adapt(np.unique(x))
output = vectorization(input)
model = tf.keras.Model(inputs=[input], outputs=[output])
model.compile(loss="mse", optimizer="adam")

# compare runtime of model.fit with different batch_size
# -> for large n, doubling the batch_size halves the execution time!!!
model.fit(x, y, epochs=1,batch_size=32)
model.fit(x, y, epochs=1,batch_size=64)
model.fit(x, y, epochs=1,batch_size=8192)

# compare runtime of model.predict with different input size
# -> for large n, calling predict 2 times with n/2 is twice as fast!!!
pred = model.predict(x,verbose=1)
pred = model.predict(x[:int(n/2)],verbose=1)
pred = model.predict(x[int(n/2+1):],verbose=1)
```

**Other info / logs** 
Observed runtimes. Absolute values may depend on your hardware. Ratios between runtimes should be reproducible.
```
31250/31250 [==============================] - 207s 7ms/step - loss: 3416.8721 (model.fit with batch_size = 32)
15625/15625 [==============================] - 121s 8ms/step - loss: 3416.8367 (model.fit with batch_size = 64)
123/123 [==============================] - 1s 10ms/step - loss: 3416.8489 (model.fit with batch_size = 8192)
31250/31250 [==============================] - 221s 7ms/step (model.predict on n vectors)
15625/15625 [==============================] - 56s 4ms/step (model.predict on n/2 vectors)
15625/15625 [==============================] - 59s 4ms/step (model.predict on n/2 vectors)

```

**Comment by aucth** [comment] 2021-07-13 09:38
You can also find a gist [here](https://colab.research.google.com/gist/aucth/9a020572f3427ad3e0f0974be2ae4b2e/untitled50666.ipynb).

**Comment by auckenth** [comment] 2021-09-23 08:29
Any news on this issue?

**Comment by chjort** [comment] 2021-12-18 01:07
After a little investigation I have been able to conclude that the issue is completely unrelated to any specific Keras layer. It seems to have something to do with the iteration over numpy arrays of string dtype.

The O(n^2) runtime behavior only occurs when `x` is a numpy array of string dtype. If `x` is a numpy array of int or float, or a `tf.data.Dataset` of any dtype, then the runtime becomes O(n) as it should be.

In the following example a custom `DummyLayer` is used instead of any native Keras layer, and `x` is casted to `str` which becomes of numpy dtype `<U21`.

```python
import numpy as np
import tensorflow as tf

print(tf.__version__)


class DummyLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(DummyLayer, self).__init__()

    def call(self, inputs, *args, **kwargs):
        return tf.random.uniform(shape=tf.shape(inputs))


# generate some dummy data
n = 1000000
x = np.random.randint(1, 100, (n, 1)).astype(str)
y = np.random.uniform(0, 1, (n, 1))

input = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
output = DummyLayer()(input)
model = tf.keras.Model(inputs=[input], outputs=[output])
model.compile(loss="mse", optimizer="adam")

x_first_half, x_second_half = x[: int(n / 2)], x[int(n / 2 + 1) :]
y_first_half, y_second_half = y[: int(n / 2)], y[int(n / 2 + 1) :]

batch_size = 32
model.fit(x, y, epochs=1, batch_size=batch_size)
model.fit(x_first_half, y_first_half, epochs=1, batch_size=batch_size)
model.fit(x_second_half, y_second_half, epochs=1, batch_size=batch_size)

model.predict(x, verbose=1, batch_size=batch_size)
model.predict(x_first_half, verbose=1, batch_size=batch_size)
model.predict(x_second_half, verbose=1, batch_size=batch_size)
```
Runtimes are observed to not scale linearly with input size:
```
31250/31250 [==============================] - 208s 7ms/step - loss: 0.1663
15625/15625 [==============================] - 42s 3ms/step - loss: 0.1662
15625/15625 [==============================] - 44s 3ms/step - loss: 0.1669
31250/31250 [==============================] - 209s 7ms/step
15625/15625 [==============================] - 54s 3ms/step
15625/15625 [==============================] - 47s 3ms/step
```

If `x` is instead casted to `int` and input layer dtype configured to `tf.int64`, the runtimes become:
```
31250/31250 [==============================] - 12s 389us/step - loss: 0.1668
15625/15625 [==============================] - 7s 421us/step - loss: 0.1669
15625/15625 [==============================] - 12s 760us/step - loss: 0.1667
31250/31250 [==============================] - 9s 283us/step
15625/15625 [==============================] - 4s 276us/step
15625/15625 [==============================] - 7s 452us/step
```

If `x` and `y` are passed to the model as a `tf.data.Dataset` the runtime remains O(n) even when `x` has string dtype.

```python
import numpy as np
import tensorflow as tf

print(tf.__version__)


class DummyLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(DummyLayer, self).__init__()

    def call(self, inputs, *args, **kwargs):
        return tf.random.uniform(shape=tf.shape(inputs))


# generate some dummy data
n = 1000000
x = np.random.randint(1, 100, (n, 1)).astype(str)
y = np.random.uniform(0, 1, (n, 1))

input = tf.keras.layers.Input(shape=(1,), dtype=tf.string)
output = DummyLayer()(input)
model = tf.keras.Model(inputs=[input], outputs=[output])
model.compile(loss="mse", optimizer="adam")

x_first_half, x_second_half = x[: int(n / 2)], x[int(n / 2 + 1) :]
y_first_half, y_second_half = y[: int(n / 2)], y[int(n / 2 + 1) :]


def to_ds(x, y, batch_size):
    return tf.data.Dataset.from_tensor_slices((x, y)).batch(batch_size)


ds = to_ds(x, y, batch_size)
ds_first_half = to_ds(x_first_half, y_first_half, batch_size)
ds_second_half = to_ds(x_second_half, y_second_half, batch_size)

model.fit(ds, epochs=1)
model.fit(ds_first_half, epochs=1)
model.fit(ds_second_half, epochs=1)

model.predict(ds, verbose=1)
model.predict(ds_first_half, verbose=1)
model.predict(ds_second_half, verbose=1)
```

gives:
```
31250/31250 [==============================] - 19s 591us/step - loss: 3313.7195
15625/15625 [==============================] - 9s 593us/step - loss: 3314.0676
15625/15625 [==============================] - 9s 584us/step - loss: 3313.3599
31250/31250 [==============================] - 10s 333us/step
15625/15625 [==============================] - 5s 333us/step
15625/15625 [==============================] - 5s 334us/step
```

**Comment by auckenth** [comment] 2021-12-20 07:47
Thanks for investigating. This helps a lot.

**Comment by tilakrayal** [comment] 2022-10-13 15:14
@aucth,
I tried to execute the code on the latest tensorflow v2.9.2 and it was executed without any issues/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7569df19debeab4687c7971a71e493ab/untitled680.ipynb) and confirm if the issue still persists. Thank you!

**Comment by auckenth** [comment] 2022-10-14 06:50
@chjort already showed that this is not a problem of keras/tensorflow. I think we can close this issue.

**Comment by tilakrayal** [comment] 2022-10-14 07:11
@auckenth,
As commented by the user,  we are moving this issue to the closed status. Thank you!

**Closed by tilakrayal** 2022-10-14 07:11 UTC
Labels: type:bug/performance, stat:awaiting response from contributor
