### ISSUE TITLE
Unable to use load_model with Keras 2.2.3

### ISSUE THREAD

**Issue by nole-lin** [keras-team/keras#11275] opened 2018-10-02 04:21 UTC
After updating Keras to 2.2.3 and using Tensorflow version 1.11.0, I am unable to load saved models. 

I am running a script on Google Cloud's Debian machine and am able to save and load the model there, but I am facing the error "UnboundLocalError: local variable 'name' referenced before assignment" when calling load_model on my local Ubuntu machine.

**Comment by gabrieldemarmiesse** [comment] 2018-10-02 12:33
Linking to #11269

We would like to work on this, but we cannot reproduce the bug. Can anyone give us a script to reproduce?

**Comment by gabrieldemarmiesse** [comment] 2018-10-02 12:34
I'll close this in favor of #11269

**Comment by adampl** [comment] 2018-10-02 16:03
@gabrieldemarmiesse I'm not sure it's a good idea to assume it's the same error.

For now I can only provide a traceback, but it seems to explain everything:

```
model = load_model(model_name)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.6/dist-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.6/dist-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/sequential.py", line 294, in from_config
    model = cls(name=name)
UnboundLocalError: local variable 'name' referenced before assignment
```

**Comment by gabrieldemarmiesse** [comment] 2018-10-02 16:18
@adampl maybe I was too quick on closing this issue. 

You have to understand that it's very difficult to work with a traceback only.
To give you an idea of what we work with, here are all the tests which are run at every commit in keras: https://github.com/keras-team/keras/tree/master/tests

Among those tests are a lot of tests concerning saving and loading models.

So our tests are passing and users are telling us that saving and loading doesn't work. It means that users are working with use cases which are not in the tests, thus it is non-trivial to reproduce. Without a script to reproduce, there is very little that we can do.

**Comment by gabrieldemarmiesse** [comment] 2018-10-02 16:20
Furthermore, we can put your script in the test, and then we'll make sure at every commit that your script never breaks again :)

**Comment by gabrieldemarmiesse** [comment] 2018-10-02 16:21
Some advices:
* Don't use custom data or custom paths.
* Use random arrays or even np.ones, np.zeros.
* The example should run with Keras (and deps) alone.
* Should be Python3 compatible.
* Should not be OS specific.
* The file should reproduce the bug with **high* fidelity.
* Link to a gist would be appreciated.
* There is usually no need to make a big neural network to trigger bugs

**Comment by adampl** [comment] 2018-10-02 17:00
I said it's obvious from the traceback, because there's a typical error at `keras/engine/sequential.py:294`:

```
    @classmethod
    def from_config(cls, config, custom_objects=None):
        if 'name' in config:
            name = config['name']
            build_input_shape = config.get('build_input_shape')
            layer_configs = config['layers']
        model = cls(name=name) #                                  <--- HERE
        for conf in layer_configs:
            layer = layer_module.deserialize(conf,
                                             custom_objects=custom_objects)
            model.add(layer)
        if not model.inputs and build_input_shape:
            model.build(build_input_shape)
        return model
```

From the check for `name` I guess this parameter is optional, so it shouldn't be used when it's not defined. The same applies to `build_input_shape` and `layer_configs` variables, which would raise similar errors in the next lines. So apparently the tests don't cover configs without a name.

However, I have no idea if the model should have this parameter nor why it doesn't :)

**Comment by tzeppy** [comment] 2018-10-02 23:44
Ran into the same issue with my stored model.

**Comment by gabrieldemarmiesse** [comment] 2018-10-03 08:37
We cannot fix a bug without adding a unit test in the same pull request. This is because there might be further bugs down the road, and the `name` referenced before assignment might be only one of them.

We cannot know if we really fixed the bug until we have a unit test which will tell us that everything is fine and working.

**Comment by gabrieldemarmiesse** [comment] 2018-10-03 08:39
I'll flag this as bug for visibility.

**Comment by adampl** [comment] 2018-10-03 10:49
> So check for `is None` should be added for name, build_input_shape and layer_configs variables

Nope, this check would itself reference the undefined variable, throwing the same error. The correct solution is to assign these variables some default values before `if`, or to rewrite the code so that nonexistent variables would never be referenced. The first is better IMHO.

**Comment by nikitautiu** [comment] 2018-10-03 11:14
I can confirm that this occurs when trying to load in `2.2.3` models saved with an older Keras version (ie. `2.2.0` in my case). Could this be related to the following change in `2.2.3`?

> Modify the return value of` Sequential.get_config()`. Previously, the return value was a list of the config dictionaries of the layers of the model. Now, the return value is a dictionary with keys `layers`, `name`, and an optional key `build_input_shape`. The old config is equivalent to `new_config['layers']`. This makes the output of `get_config` consistent across all model classes.

If so, considering there might be people with many previously saved models, a method to use these should probably be provided, or the documentation should emphasize the incompatibility.

**Comment by nikitautiu** [comment] 2018-10-03 11:30
Here is a bash script you can run in a virtualenv to replicate the issue:

```
#!/bin/bash

cat > script.py  << EOF
import keras

def main():
    if keras.__version__ == '2.2.0':
        # create model 
        model = keras.models.Sequential()
        model.add(keras.layers.Dense(2, input_shape=(10,)))  # just so we can save
        model.compile(loss=keras.losses.categorical_crossentropy,
                      optimizer=keras.optimizers.Adam())
        model.save('./model.h5', overwrite=True)

    if keras.__version__ == '2.2.3':
        model = keras.models.load_model('./model.h5')
     
if __name__ == '__main__':
    main()
EOF

pip install keras==2.2.0
python script.py

pip install keras==2.2.3
python script.py
```

**Comment by gabrieldemarmiesse** [comment] 2018-10-03 15:42
Can somebody try master and see if it works? I think this issue has been fixed here: #11280

**Comment by puneethshankar** [comment] 2018-10-04 13:04
> Linking to #11269
> 
> We would like to work on this, but we cannot reproduce the bug. Can anyone give us a script to reproduce?

@gabrieldemarmiesse Here it is!

>> Source Code + Sample data: 
https://www.google.com/url?q=http://t.dripemail2.com/c/eyJhY2NvdW50X2lkIjoiNDc2ODQyOSIsImRlbGl2ZXJ5X2lkIjoiMzgxMTIzNDc2MiIsInVybCI6Imh0dHA6Ly9weWltZy5jby9tYnZkaz9fX3M9Y2d1ZDVodnhuc2I2NGlobnN4d2YifQ&source=gmail&ust=1538709027986000&usg=AFQjCNG8-4xIpXI8DKv5YZQgHiRAl91ENA

 >>Instructions to run it  :  
https://www.pyimagesearch.com/2018/09/10/keras-tutorial-how-to-get-started-with-keras-deep-learning-and-python/

>> Error obtained (bug):
(env) (base) C:\Windows\System32\env\Scripts>python C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/predict.py --image C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/images/panda.jpg --model C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/output/smallvggnet.model --label-bin C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/output/smallvggnet_lb.pickle --width 64 --height 64
Using TensorFlow backend.
[INFO] loading network and label binarizer...
Traceback (most recent call last):
  File "C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/predict.py", line 46, in <module>
    model = load_model(args["model"])
  File "C:\Windows\System32\env\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Windows\System32\env\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Windows\System32\env\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Windows\System32\env\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Windows\System32\env\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Windows\System32\env\lib\site-packages\keras\engine\sequential.py", line 294, in from_config
    model = cls(name=name)
UnboundLocalError: local variable 'name' referenced before assignment

(env) (base) C:\Windows\System32\env\Scripts>

**Comment by gabrieldemarmiesse** [comment] 2018-10-04 14:28
Keras 2.2.4 is available on pypi. The bug should be fixed. Can anyone confirm?

**Comment by puneethshankar** [comment] 2018-10-05 03:55
> Keras 2.2.4 is available on pypi. The bug should be fixed. Can anyone confirm?

@gabrieldemarmiesse The bug is FIXED! Thanks... Here's the output

``
(env) (base) C:\Windows\System32\env\Scripts>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
>>> keras.__version__
**'2.2.4'**
>>> ^Z


(env) (base) C:\Windows\System32\env\Scripts>python C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/predict.py --image C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/images/panda.jpg --model C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/output/smallvggnet.model --label-bin C:\Users\puneeth\Downloads\keras-tutorial\keras-tutorial/output/smallvggnet_lb.pickle --width 64 --height 64
Using TensorFlow backend.
[INFO] loading network and label binarizer...
2018-10-05 09:16:59.857450: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
C:\Windows\System32\env\lib\site-packages\sklearn\base.py:251: UserWarning: Trying to unpickle estimator LabelBinarizer from version 0.19.1 when using version 0.20.0. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(50)<module>()
-> preds = model.predict(image)
(Pdb) n
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(54)<module>()
-> i = preds.argmax(axis=1)[0]
(Pdb)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(55)<module>()
-> label = lb.classes_[i]
(Pdb)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(58)<module>()
-> text = "{}: {:.2f}%".format(label, preds[0][i] * 100)
(Pdb)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(59)<module>()
-> cv2.putText(output, text, (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.7,
(Pdb)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(60)<module>()
-> (0, 0, 255), 2)
(Pdb)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(63)<module>()
-> cv2.imshow("Image", output)
(Pdb)
> c:\users\puneeth\downloads\keras-tutorial\keras-tutorial\predict.py(64)<module>()
-> cv2.waitKey(0)
(Pdb)
``

**Comment by gabrieldemarmiesse** [comment] 2018-10-05 06:13
Thanks everyone!

**Closed by gabrieldemarmiesse** 2018-10-05 06:13 UTC
Labels: bug
