### ISSUE TITLE
Trainable variable defined inside loss function is not getting trained in keras.

### ISSUE THREAD

**Issue by codeloverdk** [keras-team/keras#12503] opened 2019-03-17 16:12 UTC
I defined some tensorflow variable inside e custom loss function by setting trainable=true but while the training is going the values of the variables are not changing but i have non zero loss.

**Comment by ymodak** [comment] 2019-03-19 23:48
Please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by ymodak** [comment] 2019-03-25 22:39
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2019-03-25 22:39 UTC
Labels: backend:tensorflow, stat:awaiting response
