### ISSUE TITLE
AttributeError: 'Node' object has no attribute 'output_masks'

### ISSUE THREAD

**Issue by GuillaumeDrillaud** [keras-team/keras#10907] opened 2018-08-14 08:29 UTC
I use Keras pretrained model VGG16. The problem is that after configuring tensorflow to use the GPU I get an error that I didn't have before when using the CPU.

The error is the following one:

   ```
 Traceback (most recent call last):
  File "/home/guillaume/Documents/Allianz/ConstatOrNotConstatv3/train_network.py",      line 109, in <module>
    model = LeNet.build(width=100, height=100, depth=3, classes=5)
  File "/home/guillaume/Documents/Allianz/ConstatOrNotConstatv3/lenet.py", line 39,    in build
    output = model(pretrainedOutput)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 443, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
mask = node.output_masks[tensor_index]
  AttributeError: 'Node' object has no attribute 'output_masks'
```

I get it after executing this code :

    pretrained_model = VGG16(
        include_top=False,
        input_shape=(height, width, depth),
        weights='imagenet'
    )
    for layer in pretrained_model.layers:
        layer.trainable = False

    model = Sequential()
    # first (and only) set of FC => RELU layers
    model.add(Flatten())
    model.add(Dense(200, activation='relu'))
    model.add(Dropout(0.5))
    model.add(BatchNormalization())
    model.add(Dense(400, activation='relu'))
    model.add(Dropout(0.5))
    model.add(BatchNormalization())

    # softmax classifier
    model.add(Dense(classes,activation='softmax'))

    pretrainedInput = pretrained_model.input
    pretrainedOutput = pretrained_model.output
    output = model(pretrainedOutput)
    model = Model(pretrainedInput, output)

I've got keras (2.2.2) and tensorflow(1.10.0rc1). I've also tried on keras 2.2.0 and same error. The thing is that the python environment I use works on others non-pretrained NN.

Moreover, I'm able to connect two homemade models. It's only whith the pretrained ones there is a problem and not only VGG16.

**Comment by kuabhish** [comment] 2018-08-17 20:55
Hi Please see the libraries you imported .. import everything of keras ..do not mix up tensorflow

**Comment by keunwoochoi** [comment] 2018-08-17 21:04
+1. Native keras doesn't go well with tf.keras.

**Comment by naoyuki-ichimura** [comment] 2018-08-24 07:55
I have the same problem.  I guess the output tensor of the vgg16 model cannot be used properly. 

I used the output tensor of the vgg16 model in the following simple code.
The versions of Keras and TensorFlow were 2.2.2 and 1.10.0rc1, respectively.

The error messages were:
```
Traceback (most recent call last):
  File "test_vgg16_1.py", line 31, in <module>
    model = Model( inputs=vgg16_conv_model.input , outputs=fc_model(vgg16_conv_model.output) )
  File "/usr/local/lib64/python3.6/site-packages/keras/engine/base_layer.py", line 443, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/usr/local/lib64/python3.6/site-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'
```
I ran the following code:

```python
#
# Setting the image attributes
#
resized_image_height = 150
resized_image_width = 150
no_image_channels = 3
max_pixel_value = 255

#
# Setting the convolutional network of the VGG16 model
#
from keras.applications.vgg16 import VGG16
vgg16_conv_model = VGG16( include_top=False , # remove the fully-connnected network
                          weights='imagenet' ,
                          input_shape=( resized_image_height , resized_image_width , no_image_channels ) )

#
# Setting the new fully-connected network
#
from keras.models import Sequential, Model
from keras.layers import Flatten, Dropout, Dense
fc_model = Sequential()
fc_model.add(Flatten(input_shape=vgg16_conv_model.output_shape[1:]))
fc_model.add(Dropout(0.2))
fc_model.add(Dense( 512 , activation='relu' ))
fc_model.add(Dense( 1 , activation='sigmoid' ))

#
# Combining the models
#
model = Model( inputs=vgg16_conv_model.input , outputs=fc_model(vgg16_conv_model.output) )
```
I would appreciate it if you could give me some advice to resolve this error.

**Comment by arquolo** [comment] 2018-08-27 09:05
Nightly TF builds are, hmm, nightly, so Keras haven't become compatible with all its features yet.
If using latest version of TF isn't important for you, downgrade to TensorFlow 1.9, there's no this bug.

**Comment by SpikeKing** [comment] 2018-08-28 06:09
@arquolo you are right! I have the same problem. I downgrade to TensorFlow 1.9 with Keras 2.2.2, it's OK!

**Comment by abdelrahmanmohamed** [comment] 2018-09-18 15:39
I have TF 1.9 and keras 2.2.2 and it's now working
C:\Users\abdo_\Anaconda3\python.exe C:/Users/abdo_/PycharmProjects/TGSChallenge/model_script.py
C:\Users\abdo_\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/abdo_/PycharmProjects/TGSChallenge/model_script.py", line 91, in <module>
    resizeInput=Lambda(function=resize)(imageInput)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 731, in __call__
    inputs, outputs, args, kwargs)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 848, in _set_connectivity_metadata_
    input_tensors=inputs, output_tensors=outputs, arguments=kwargs)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 996, in _add_inbound_node
    arguments=arguments)
  File "C:\Users\abdo_\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1665, in __init__
    layer.outbound_nodes.append(self)
AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

**Comment by KittyLiou** [comment] 2018-09-30 07:14
I had a similar problem. I was trying to use VGG16 and got this error `AttributeError: 'InputLayer' object has no attribute 'outbound_nodes' `.
My tensor flow-gpu version was 1.11 and after I downgraded it to 1.9  according to @arquolo it works now! Thanks a lot!

**Comment by felix-tracxpoint** [comment] 2018-11-12 19:09
I have encountered the same problem. The most minimal code example already reproduces it:

```
from keras.layers import GlobalAveragePooling2D
from keras.applications.inception_v3 import InceptionV3
base_model = InceptionV3(weights=None, include_top=False)
x = base_model.output
x = GlobalAveragePooling2D()(x)
```

The versions are:
Keras               2.2.4     
Keras-Applications  1.0.4     
Keras-Preprocessing 1.0.2   
tensorboard         1.12.0    
tensorflow-gpu      1.12.0  

Is there no solution save downgrading to older versions of keras and tf-gpu? 

It feels so defeatist to have to do that...

**Comment by felix-tracxpoint** [comment] 2018-11-13 07:49
@arquolo Thanks, that did the trick!!

P.S.
I had been under the impression that the main keras package upgrades the others during piping. Obviously I could not have been more wrong.

**Comment by ymodak** [comment] 2018-11-20 19:34
Closing this issue since its resolved. Feel to reopen if the issue still persists. Thanks!

**Closed by ymodak** 2018-11-20 19:34 UTC
Labels: type:tensorFlow

**Comment by ronjian** [comment] 2019-01-29 07:51
I solved this issue by reinstalling keras to the latest version(2.2.4).

**Comment by PriyankaSoni15** [comment] 2019-05-21 17:21
same issue as @abdelrahmanmohamed i am getting even after installing tensorflow-gpu 1.9.0 and keras latest version 2.2.4 as well as 2.2.2, in both the cases i am getting error saying
AttributeError: 'InputLayer' object has no attribute 'outbound_nodes'

Please help

**Comment by stefanolafs** [comment] 2019-06-04 00:16
According to [this post](https://www.depends-on-the-definition.com/sequence-tagging-lstm-crf/), it appears that keras-contrib requires Keras 2.1.1

**Comment by Raseth** [comment] 2019-06-24 09:43
I had a similar issue, but with different architecture. As people suggested, it's important not to mix keras with tensorflow.keras, so try swapping

```
from keras.preprocessing import image
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras import backend as K
```

to: 

```
from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras import backend as K
```

Also make sure, you don't use keras.something inside your code (not only imports) as well, hope it helps : )
Also, I used Keras 2.2.4 with tensorflow 1.10.0

**Comment by hichamhendy** [comment] 2019-09-05 21:13
keras | 2.2.5 | 2.2.4
keras-applications | 1.0.8 | 1.0.8
keras-preprocessing | 1.1.0 | 1.1.0

scipy | 1.3.1 | 1.3.1
-- | -- | --
setuptools | 39.1.0 | 41.0.1
six | 1.12.0 | 1.12.0
tensorboard | 1.9.0 | 1.14.0
tensorflow | 1.9.0 | 1.14.0
tensorflow-estimator | 1.14.0 | 1.14.0
tensorflow-gpu | 1.9.0 | 1.14.0
termcolor | 1.1.0 | 1.1.0
theano | 1.0.2 | 1.0.3

I have the same issue ! although I downgraded everything to be compatible with the above mentioned versions !!

**Comment by liuhh02** [comment] 2019-11-29 16:27
> keras | 2.2.5 | 2.2.4
> keras-applications | 1.0.8 | 1.0.8
> keras-preprocessing | 1.1.0 | 1.1.0
> scipy | 1.3.1 | 1.3.1
> setuptools | 39.1.0 | 41.0.1
> six | 1.12.0 | 1.12.0
> tensorboard | 1.9.0 | 1.14.0
> tensorflow | 1.9.0 | 1.14.0
> tensorflow-estimator | 1.14.0 | 1.14.0
> tensorflow-gpu | 1.9.0 | 1.14.0
> termcolor | 1.1.0 | 1.1.0
> theano | 1.0.2 | 1.0.3
> 
> I have the same issue ! although I downgraded everything to be compatible with the above mentioned versions !!

Try using either keras or tensorflow.keras, but don't mix the two of them together. This was what fixed my issue.

**Comment by unnir** [comment] 2020-05-10 13:05
extremely annoying issue, I have installed the latest versions of TF and keras. But, have the same problem. 

tf - '2.2.0'
keras - 2.3.0-tf

**Comment by luisvivasg** [comment] 2020-07-13 12:11
If you are using YOLO. This what you have to do. As Raseth said.

from keras.preprocessing import image
from keras.models import Model
from keras.layers import Dense, GlobalAveragePooling2D
from keras import backend as K
to:

from tensorflow.keras.preprocessing import image
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras import backend as K


My only solution was to fork the GIT and edit it there. 

I did not need to downgrade Keras or Tensorflow.

**Comment by Penkez** [comment] 2020-09-21 12:38
@luisvivasg  solution works. I used tensorflow.keras instead of keras.
I am using tensorflow-gpu=2.0.0

**Comment by wxs-newboy** [comment] 2022-07-20 06:30
I have same problem.

`  File "/data2/wangxinsheng/yft/yft_semantic_train_model/keras_textclassification/base/embedding.py", line 283, in build
    self.output = NonMaskingLayer()(encoder_layer)
  File "/data/anaconda3/envs/miss_torch_develop/lib/python3.7/site-packages/keras/engine/base_layer.py", line 443, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/data/anaconda3/envs/miss_torch_develop/lib/python3.7/site-packages/keras/engine/base_layer.py", line 1311, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
AttributeError: 'Node' object has no attribute 'output_masks'`


> K!
I can't get tensorflow 1.9.
There is no tensorflow 1.9 in https://pypi.org/project/tensorflow-gpu/1.15.2/#history.

Do you know how to fix it?
