### ISSUE TITLE
Error in build. 

### ISSUE THREAD

**Issue by old-school-kid** [keras-team/keras#15858] opened 2022-01-05 17:51 UTC
**System information**.
- Have I written custom code (as opposed to using a stock example script provided in Keras): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): tf_nightly-2.9.0
- Python version: 3.7
- Bazel version (if compiling from source): 4.2.2
- GPU model and memory: NVIDIA GeForce 1080Ti
- Exact command to reproduce: 

Cloned the recent version of the repo and followed the steps provided in CONTRIBUTING.md 
When tests are run using bazel errors are raised. 

Complete error log:

WARNING: The following configs were expanded more than once: [v2]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=E:/venv_dir/Scripts/python.exe
INFO: Reading rc options for 'test' from e:\venv_dir\keras\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --define open_source_build=true --define=use_fast_cpp_protos=false --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --config=short_logs --config=v2
INFO: Reading rc options for 'test' from e:\venv_dir\keras\.bazelrc:
  'test' options: --define open_source_build=true --define=use_fast_cpp_protos=false --config=v2
INFO: Found applicable config definition build:short_logs in file e:\venv_dir\keras\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file e:\venv_dir\keras\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:v2 in file e:\venv_dir\keras\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Analyzed target //keras/engine:base_layer_test (53 packages loaded, 1275 targets configured).
INFO: Found 1 test target...
ERROR: C:/users/surya prakash mishra/_bazel_surya prakash mishra/dtq74e5t/external/com_google_protobuf/BUILD:853:26: Executing genrule @com_google_protobuf//:protos_python_genrule failed: (Exit -1): bash.exe failed: error executing command c:/tools/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
Action failed to execute: java.io.IOException: ERROR: src/main/native/windows/process.cc(202): CreateProcessW("c:\tools\msys64\usr\bin\bash.exe" -c "source external/bazel_tools/tools/genrule/genrule-setup.sh; cp external/com_google_protobuf/src/google/protobuf/any.proto bazel-out/x64_windows-opt/bin/external/com_google_protobuf/python/google/protobuf/any.proto && cp external/com_google_protobuf/src/google/protobuf/api.proto bazel-out/x64_windows-opt/bin/external/com_google_protobuf/python/google/protobuf/api.proto && cp external/com_google_protobuf/src/google/protobuf/compiler/plugin.proto bazel-ou(...)): The system cannot find the file specified.
 (error: 2)
Target //keras/engine:base_layer_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/users/surya prakash mishra/_bazel_surya prakash mishra/dtq74e5t/external/com_google_protobuf/BUILD:864:17 ProtoCompile external/com_google_protobuf/python/google/protobuf/duration_pb2.py failed: (Exit -1): bash.exe failed: error executing command c:/tools/msys64/usr/bin/bash.exe -c ... (remaining 1 argument(s) skipped)
INFO: Elapsed time: 145.682s, Critical Path: 19.77s
INFO: 175 processes: 16 internal, 159 local.
FAILED: Build did NOT complete successfully
//keras/engine:base_layer_test                                  FAILED TO BUILD

FAILED: Build did NOT complete successfully

**Comment by qlzh727** [comment] 2022-01-05 18:04
Sadly we usually just verify our build process on Linux, and current we don't have a windows OSS build. Will discuss this on the triage meeting.

**Comment by AdityaKane2001** [comment] 2022-01-06 18:56
@old-school-kid 

Not sure, but I think you can try one of the following:
- Docker: use a docker container if possible, it'll make things much simpler.
- In your particular case, restarting the computer might help. In my case proto related errors disappeared after restarting. Also, don't forget to add bazel to `PATH`.

**Comment by qlzh727** [comment] 2022-01-06 19:00
Thanks @AdityaKane2001  for the reply. @old-school-kid could u check if this error is caused by any local env issue?

**Comment by old-school-kid** [comment] 2022-01-07 06:06
> In your particular case, restarting the computer might help. In my case proto related errors disappeared after restarting. Also, don't forget to add bazel to PATH.
Tests start and actually first 106 out of 165 of them pass too. So I dont think there is an issue with local env. And I restarted my computer but didn't help. 

> Docker: use a docker container if possible, it'll make things much simpler.
Will try to do this but isn't it supposed to build locally in a Windows machine.

**Comment by AdityaKane2001** [comment] 2022-01-07 06:14
> Will try to do this but isn't it supposed to build locally in a Windows machine.

Things are not really supported well on Windows. Hence the recommendation.

**Comment by qlzh727** [comment] 2022-04-07 22:38
Closing this issue since it is quite idle and probably not anything we are addressing from keras-team

**Closed by qlzh727** 2022-04-07 22:38 UTC
